Fixes from the field
uktrade/tamato pull request #100
Opened 2020-11-06 19:31 UTC by simonwo

Another mixed bag of fixes for core:

- XSD change to ensure envelopes are produced according to our ID standard.
- Fix quota definition XML to include units.
- Don't use the quota description as a string representation as it may be `None`.
- Allow Python from a envrionment variable in the Makefile.

2020-11-06 21:20 UTC, NDevox requested changes
Mostly good, just want to avoid circular imports.

2020-11-06 21:20 UTC, NDevox commented on measures/serializers.py
> +
Circular imports are generally code smell.

I won't deny that this is because the way the XML is made to be transmitted has created the circular dependency...

But instead of reproducing it in the code we can do something like:

```python


@TrackedModelSerializer.register_polymorphic_model
class MeasureSerializer(TrackedModelSerializerMixin, ValiditySerializerMixin):
    # ...
    order_number = QuotaOrderNumberSerializer(read_only=True)
    # ...

    def get_order_number(self, obj):
        if obj.order_number:
            return obj.order_number.order_number
```

That way the serializer gives direct access to the order_number value that is actually needed and there is no need to import serializer in this module like so (and can therefore remove the circular nature of the imports in the Quotas module. (could arguably do the same for that serializer too).

The XML would need to be updated to:

```xml
      {%- if record.order_number %}
      <oub:ordernumber>{{ record.order_number }}</oub:ordernumber>
      {%- endif -%}
```

2020-11-07 00:34 UTC, simonwo commented on measures/serializers.py
> +
I implemented this and then thought about it again, and realised that there is only a circular import issue because we grouped units together with measures. There's no real need to group them together like this – we could even go as far as splitting them out into a separate app. But for now I've split them into a separate serializer file and this avoids any import tomfoolery and also lets us retain the proper serializer for the quota order number. What do you think?

2020-11-07 09:45 UTC, NDevox approved these changes

2020-11-07 09:45 UTC, NDevox commented on measures/serializers.py
> +
👍  this works for me

2020-11-07 09:46 UTC, NDevox commented on measures/serializers.py
> +
I agree it may make sense to move these to a separate file. Looks like we put them together because of the commonality shared with the word "measure" but that's not really a reason to keep them in the same app.

2020-11-07 23:24 UTC, merged