Tp2000 819 importer refactor
uktrade/tamato pull request #1015
Opened 2023-08-22 13:16 UTC by dougmills-DIT

# TP-??? Your PR title here

## Why

## What

2023-11-03 08:36 UTC, a-gleeson commented on README.rst
> +Virus Scan and running locally
Is this duplicated docs from above?

2023-11-03 08:36 UTC, a-gleeson commented on commodities/tests/test_migrations.py
> +    print("last chance")
leftover print?

2023-11-03 08:38 UTC, a-gleeson commented on common/tests/test_forms.py
> -)
Was there a reason to remove the formset_factory?

2023-11-03 08:38 UTC, a-gleeson commented on importer/forms.py
> +# from importer.management.commands.run_new_import_batch import new_run_batch
left over comment?

2023-11-03 08:39 UTC, a-gleeson commented on importer/models.py
> +from taric_parsers.importer_issue import *
Should we use absolute imports?

2023-11-03 08:43 UTC, a-gleeson commented on importer/tasks.py
> +from taric_parsers.importer import *
should we use absolute imports?

2023-11-03 08:43 UTC, a-gleeson commented on importer/tasks.py
> +# noinspection PyUnresolvedReferences
excess comments?

2023-11-03 08:45 UTC, a-gleeson commented on publishing/models/envelope.py
> +    def create(self, packaged_work_basket, **kwargs):
Was there a reason to remove Type signatures?

2023-11-03 08:49 UTC, a-gleeson commented on taric_parsers/chunker.py
> +MAX_FILE_SIZE = 1024 * 1024 * 50  # Will keep chunks roughly close to 50MB
Should this be a configuration variable in settings?

2023-11-03 08:53 UTC, a-gleeson commented on taric_parsers/chunker.py
> +def get_chunk(
as it can create a chunk too should the name of the method reflect that?

2023-11-03 09:17 UTC, a-gleeson commented on taric_parsers/chunker.py
> +    def comm_code_key(transaction):
Might be my ignorance onthe taric import structure but do we need to be concerned about multiple different com codes within a single transaction?

2023-11-03 09:21 UTC, a-gleeson commented on taric_parsers/chunker.py
> +    logger.info("%d to sort, deleting old ones", len(transactions))
should we include an Id for this log as it may not be clear if we are investigating logs

2023-11-03 09:24 UTC, a-gleeson commented on taric_parsers/chunker.py
> +    chunks.delete()
what could be the implications of TAP crashing after the delete but before chunks are recreated? 
Is it just this import would be abandoned or is it picked up again?

2023-11-03 09:35 UTC, a-gleeson commented on taric_parsers/chunker.py
> +            message.remove(transmission)
Am I miss understanding this that we remove transmission if theres no value?

2023-11-08 08:17 UTC, dougmills-DIT commented on publishing/models/envelope.py
> +    def create(self, packaged_work_basket, **kwargs):
Must have been a wonky github thing - i have not changes that file. I have pulled latest and this has been updated.

2023-11-08 08:19 UTC, dougmills-DIT commented on commodities/tests/test_migrations.py
> +    print("last chance")
removed, good spot

2023-11-08 08:40 UTC, dougmills-DIT commented on common/tests/test_forms.py
> -)
no idea how this got removed - but restored!

2023-11-08 08:42 UTC, dougmills-DIT commented on importer/forms.py
> +# from importer.management.commands.run_new_import_batch import new_run_batch
yep, removed!

2023-11-08 08:43 UTC, a-gleeson commented on taric_parsers/importer.py
> +from taric_parsers.parsers.additional_code_parsers import *  # noqa
should we use absolute importers?

2023-11-08 08:43 UTC, dougmills-DIT commented on README.rst
> +Virus Scan and running locally
good spot! removed duplication

2023-11-08 08:44 UTC, dougmills-DIT commented on importer/forms.py
> +# from importer.management.commands.run_new_import_batch import new_run_batch
removed!

2023-11-08 08:56 UTC, dougmills-DIT commented on importer/models.py
> +from taric_parsers.importer_issue import *
yep - updated!

2023-11-08 08:57 UTC, dougmills-DIT commented on importer/tasks.py
> +from taric_parsers.importer import *
yep - updated!

2023-11-08 08:57 UTC, a-gleeson commented on taric_parsers/importer.py
> +            taric3_xml_string: (required if taric3_file_path not provided) str, string containing the Taric3 XML.
Doesn't seem complex enough where dependency injection is required but instead of taric3_file_path and taric3_xml_string we could initialise a "taric3_config" which could be either a file or string which has a function for returning the raw_xml. That way this init doesn't need to worry about which one we require

2023-11-08 08:57 UTC, dougmills-DIT commented on importer/tasks.py
> +# noinspection PyUnresolvedReferences
removed! black removed imports since noinspect is ignored, and should have been noqa

2023-11-08 09:06 UTC, dougmills-DIT commented on taric_parsers/chunker.py
> +    def comm_code_key(transaction):
not even sure if this is required, will investigate - was a straight copy from importer

2023-11-08 10:01 UTC, dougmills-DIT commented on taric_parsers/chunker.py
> +def get_chunk(
renamed to find_or_create_chunk

2023-11-08 10:03 UTC, dougmills-DIT commented on taric_parsers/chunker.py
> +    def comm_code_key(transaction):
removed as not used un new importer

2023-11-08 10:04 UTC, dougmills-DIT commented on taric_parsers/chunker.py
> +    logger.info("%d to sort, deleting old ones", len(transactions))
removed containing function

2023-11-08 10:06 UTC, dougmills-DIT commented on taric_parsers/chunker.py
> +    chunks.delete()
removed containing function

2023-11-08 11:20 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +from taric_parsers.parsers.additional_code_parsers import *  # noqa
yep updated in most places

2023-11-08 11:20 UTC, dougmills-DIT commented on taric_parsers/chunker.py
> +            message.remove(transmission)
yes, looks like not transmission checks that its empty and is safe to remove

2023-11-08 12:01 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +            taric3_xml_string: (required if taric3_file_path not provided) str, string containing the Taric3 XML.
good idea, will look at that.

2023-11-08 12:50 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +            taric3_xml_string: (required if taric3_file_path not provided) str, string containing the Taric3 XML.
ended up creating a xml source base class, and created two adapters to address the different source types

2023-11-09 08:05 UTC, a-gleeson commented on taric_parsers/importer.py
> +            taric3_xml_string: (required if taric3_file_path not provided) str, string containing the Taric3 XML.
Docstring requires updaing for the new base calss, looks good!

2023-11-09 08:13 UTC, a-gleeson commented on taric_parsers/importer.py
> +        envelope = Envelope.new_envelope()
This is an "old" model for envelope (seperate from the packaging envelope). Just wondering the usage of this as it seems to be just for the id in a composite key?
Thinking about it we couldn't really use the new model for this as the ids require to be sequential and if we create an envelope id for an import and then try use that id later it would be out of sequence. If this would be the goal maybe there's future work where you can create an Envelope at any point for an object but you defer the id creation until you generate the envelope for CDS.

2023-11-09 08:31 UTC, a-gleeson commented on taric_parsers/importer.py
> +                continue
should this be a break?

2023-11-09 08:34 UTC, a-gleeson commented on taric_parsers/importer.py
> +            message: (optional) str, A string describing the encountered issue / warning.
missing issue type in docs

2023-11-09 08:41 UTC, a-gleeson commented on taric_parsers/importer.py
> +                            child_matches[object_match.__class__.__name__] += 1
I might have my python wrong but is it possible to rewrite this as `child_matches.get(object_match.__class__.__name__,0) += 1`

2023-11-10 08:57 UTC, a-gleeson commented on taric_parsers/views.py
> +from importer.models import *
should we use absolute imports here?

2023-11-10 09:01 UTC, a-gleeson commented on taric_parsers/tests/test_transaction_parser.py
> +from taric_parsers.parsers.taric_parser import *
a couple star imports

2023-11-10 11:31 UTC, a-gleeson commented on taric_parsers/parsers/taric_parser.py
> +from taric_parsers.parser_model_link import *
star import

2023-11-10 11:46 UTC, a-gleeson commented on taric_parsers/parsers/taric_parser.py
> +                self.update_type_name = update_type.name.lower()
once matched would we want to break the loop?

2023-11-13 08:19 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +        envelope = Envelope.new_envelope()
This is the same as importer/taric.py:119 

I think I need a better understanding of what you are suggesting here, it's not very clear.

2023-11-13 08:23 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +        envelope = Envelope.new_envelope()
I think I need to understand the issue better. 

see importer/taric.py:119 

This is the same as the existing importer. Can you be a little more explicit on your proposition here?

2023-11-13 08:23 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +                continue
yes, minor refactor done

2023-11-13 10:56 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +            message: (optional) str, A string describing the encountered issue / warning.
done, also refactored issue type to a TextChoices parameter

2023-11-13 10:56 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +                            child_matches[object_match.__class__.__name__] += 1
its possible, but I would question if that would be an improvement :) 

It makes the code less readable.

2023-11-13 16:06 UTC, a-gleeson commented on taric_parsers/parsers/regulation_parser.py
> +from taric_parsers.parsers.taric_parser import *
should we use absolute imports?

2023-11-13 16:07 UTC, a-gleeson commented on taric_parsers/parsers/regulation_parser.py
> +    # language_id: str = None
left over comment?

2023-11-13 16:07 UTC, a-gleeson commented on taric_parsers/parsers/regulation_parser.py
> +        # "explicit_abrogation_regulation_id": "GH123123",
left over comment?

2023-11-13 16:08 UTC, a-gleeson commented on taric_parsers/parsers/regulation_parser.py
> +        # "complete_abrogation_regulation_role": "3",
left over comment?

2023-11-14 08:43 UTC, a-gleeson commented on taric_parsers/parsers/taric_parser.py
> +        for field in self.identity_fields_for_parent():
we could do `self.identity_fields_for_parent().values()` if we only need the values for this loop or `.items()` if we need `key, value` instead of calling the function twice

2023-11-14 08:52 UTC, a-gleeson commented on taric_parsers/parsers/taric_parser.py
> +                if field_data_type == str:
there's a few elifs, should we use a switch statement?

2023-11-14 09:51 UTC, a-gleeson commented on taric_parsers/parsers/taric_parser.py
> +        This method checks that the parser that represents a TARIC object can be saved to a TAP model by checking associated issues recorded during validation
Does this check against issues arising in validation?

2023-11-14 10:18 UTC, dougmills-DIT commented on taric_parsers/tests/test_parser_helper.py
> +from taric_parsers.parsers.regulation_parser import *
not so fussed about tests but done ;)

2023-11-14 10:19 UTC, a-gleeson commented on taric_parsers/parsers/quota_parser.py
> +from taric_parsers.parsers.taric_parser import *
absolute imports over star imports?

2023-11-14 10:22 UTC, a-gleeson commented on taric_parsers/parsers/quota_parser.py
> +    def data(self):
whats the purpose of this parser having this property?

2023-11-14 10:25 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +from additional_codes.models import *
absolute imports over star imports?

2023-11-14 10:27 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
leftover comment?

2023-11-14 10:27 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # handler = MeasurementUnitHandler
leftover comment?

2023-11-14 10:27 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
leftover comment?

2023-11-14 10:28 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
leftover comment?

2023-11-14 10:28 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
leftover comment?

2023-11-14 10:29 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # handler = MeasureTypeHandler
leftover comment?

2023-11-14 10:29 UTC, dougmills-DIT commented on taric_parsers/tests/test_transaction_parser.py
> +from taric_parsers.parsers.taric_parser import *
done

2023-11-14 10:29 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
comment

2023-11-14 10:29 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # handler = AdditionalCodeTypeMeasureTypeHandler
comment

2023-11-14 10:29 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # handler = MeasureConditionCodeHandler
comment

2023-11-14 10:30 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
comment

2023-11-14 10:30 UTC, a-gleeson commented on taric_parsers/parsers/measure_parser.py
> +    # handler = MeasureActionHandler
comment

2023-11-14 10:33 UTC, a-gleeson commented on taric_parsers/parsers/geo_area_parser.py
> +from geo_areas.models import *
Star imports used

2023-11-14 10:33 UTC, a-gleeson commented on taric_parsers/parsers/footnote_parser.py
> +    # language_id: str = None
leftover comment?

2023-11-14 10:33 UTC, a-gleeson commented on taric_parsers/parsers/footnote_parser.py
> +    # language_id: str = None
leftover comment?

2023-11-14 10:34 UTC, paulpepper-trade commented on README.rst
> +The new importer addresses issues with the existing importer.
Terms like "new importer" will be out of date as soon as this work is introduced as production code.

2023-11-14 10:35 UTC, a-gleeson commented on taric_parsers/parsers/commodity_parser.py
> +from commodities.models import *
Star imports

2023-11-14 10:35 UTC, a-gleeson commented on taric_parsers/parsers/commodity_parser.py
> +    # handler = GoodsNomenclatureOriginHandler
leftover comment?

2023-11-14 10:35 UTC, a-gleeson commented on taric_parsers/parsers/commodity_parser.py
> +    # language_id: str = None
leftover comment?

2023-11-14 10:36 UTC, a-gleeson commented on taric_parsers/parsers/certificate_parser.py
> +from certificates.models import *
star import

2023-11-14 10:36 UTC, a-gleeson commented on taric_parsers/parsers/additional_code_parsers.py
> +    # language_id: str = None
leftover comment?

2023-11-14 10:37 UTC, a-gleeson commented on taric_parsers/parsers/additional_code_parsers.py
> +        # "certificate_type_code": "certificate_type_sid",
leftover comment?

2023-11-14 10:37 UTC, a-gleeson commented on taric_parsers/parsers/additional_code_parsers.py
> +from additional_codes.models import *
star imports

2023-11-14 10:48 UTC, paulpepper-trade commented on README.rst
> +* Reporting on import issues in the UI, when an invalid scenario occurs, and data cant import correctly for one reason or another, there will be an error created against the import. If an issue is de
This looks like the kind of content that could go in the PR description rather than in the README. I don't think offers enduring value as readme content.

2023-11-14 10:48 UTC, paulpepper-trade commented on commodities/models/dc.py
> +        filter = Q()
Why abbreviate a descriptive / self-documenting variable name?

2023-11-14 10:48 UTC, paulpepper-trade commented on commodities/models/dc.py
> +        qs = Measure.objects.filter(filter)
Ditto re abbreviation.

2023-11-14 10:48 UTC, paulpepper-trade commented on commodities/models/dc.py
> +            .order_by("transaction")
It looks as though this is undoing a fix and naming improvement / refactor in a PR that was merged six months ago: https://github.com/uktrade/tamato/commit/211bd3ee00be9442f8e1315cbcbe6effc8f8d621. Is that intentional or a merge problem in this PR?

2023-11-14 10:58 UTC, a-gleeson commented on taric_parsers/namespaces.py
> +        return f"{{{ns}}}{self.name}"
extra curly bracket?

2023-11-14 10:59 UTC, a-gleeson commented on taric_parsers/namespaces.py
> +RE_PATTERN_TEST = re.compile(r"[^A-Za-z\.\_]")
describe the regex?

2023-11-14 11:29 UTC, dougmills-DIT commented on taric_parsers/parsers/taric_parser.py
> +from taric_parsers.parser_model_link import *
done

2023-11-14 11:30 UTC, dougmills-DIT commented on taric_parsers/parsers/taric_parser.py
> +                self.update_type_name = update_type.name.lower()
done

2023-11-14 11:55 UTC, a-gleeson commented on taric_parsers/models.py
> +# Create your models here.
file needed?

2023-11-14 14:09 UTC, a-gleeson commented on taric_parsers/namespaces.py
> +TARIC_RECORD_GROUPS: Dict[str, Sequence[str]] = dict(
Is this a repeated constant used in `importer/namespaces.py`?

2023-11-14 14:45 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # handler = MeasurementUnitHandler
removed on all parser classes

2023-11-14 14:45 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
removed

2023-11-14 14:45 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
removed

2023-11-14 14:46 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
removed

2023-11-14 14:46 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # handler = MeasureTypeHandler
removed

2023-11-14 14:46 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
removed

2023-11-14 14:46 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # handler = AdditionalCodeTypeMeasureTypeHandler
removed

2023-11-14 15:05 UTC, dougmills-DIT commented on taric_parsers/models.py
> +# Create your models here.
removed!

2023-11-14 15:14 UTC, dougmills-DIT commented on commodities/models/dc.py
> +        qs = Measure.objects.filter(filter)
looks like an update that was not pulled across when updating from master - pulled manually! should be fixed

2023-11-14 15:14 UTC, dougmills-DIT commented on commodities/models/dc.py
> +            .order_by("transaction")
looks like an update that was not pulled across when updating from master - pulled manually! should be fixed

2023-11-14 15:15 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # handler = MeasureConditionCodeHandler
removed!

2023-11-14 15:15 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
removed!

2023-11-14 15:15 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # handler = MeasureActionHandler
removed!

2023-11-14 15:15 UTC, dougmills-DIT commented on taric_parsers/parsers/geo_area_parser.py
> +from geo_areas.models import *
Updated!

2023-11-14 15:15 UTC, dougmills-DIT commented on taric_parsers/parsers/footnote_parser.py
> +    # language_id: str = None
removed!

2023-11-14 15:16 UTC, dougmills-DIT commented on taric_parsers/parsers/footnote_parser.py
> +    # language_id: str = None
removed!

2023-11-14 15:17 UTC, dougmills-DIT commented on README.rst
> +The new importer addresses issues with the existing importer.
yep - i thought that when writing it, will take a look

2023-11-14 15:17 UTC, dougmills-DIT commented on taric_parsers/parsers/commodity_parser.py
> +from commodities.models import *
updated!

2023-11-14 15:17 UTC, dougmills-DIT commented on taric_parsers/parsers/commodity_parser.py
> +    # handler = GoodsNomenclatureOriginHandler
removed!

2023-11-14 15:17 UTC, dougmills-DIT commented on taric_parsers/parsers/commodity_parser.py
> +    # language_id: str = None
removed!

2023-11-14 15:17 UTC, dougmills-DIT commented on taric_parsers/parsers/certificate_parser.py
> +from certificates.models import *
Updated!

2023-11-14 15:17 UTC, dougmills-DIT commented on taric_parsers/parsers/additional_code_parsers.py
> +    # language_id: str = None
removed!

2023-11-14 15:18 UTC, dougmills-DIT commented on taric_parsers/parsers/additional_code_parsers.py
> +        # "certificate_type_code": "certificate_type_sid",
removed!

2023-11-14 15:18 UTC, dougmills-DIT commented on taric_parsers/parsers/additional_code_parsers.py
> +from additional_codes.models import *
Updated!

2023-11-15 08:03 UTC, dougmills-DIT commented on README.rst
> +* Reporting on import issues in the UI, when an invalid scenario occurs, and data cant import correctly for one reason or another, there will be an error created against the import. If an issue is de
fair, will have a look

2023-11-15 08:08 UTC, dougmills-DIT commented on README.rst
> +* Reporting on import issues in the UI, when an invalid scenario occurs, and data cant import correctly for one reason or another, there will be an error created against the import. If an issue is de
tidied thais up.

2023-11-15 08:09 UTC, dougmills-DIT commented on README.rst
> +The new importer addresses issues with the existing importer.
updated

2023-11-15 08:13 UTC, dougmills-DIT commented on taric_parsers/namespaces.py
> +TARIC_RECORD_GROUPS: Dict[str, Sequence[str]] = dict(
yes, copying all required files and referencing within the taric_parser app (namespaces & chunker with a mind to remove importer namespaces.py in the future, at the same time as removing the old importer.

2023-11-15 08:22 UTC, dougmills-DIT commented on taric_parsers/namespaces.py
> +RE_PATTERN_TEST = re.compile(r"[^A-Za-z\.\_]")
done

2023-11-15 09:05 UTC, a-gleeson commented on taric_parsers/namespaces.py
> +TARIC_RECORD_GROUPS: Dict[str, Sequence[str]] = dict(
should we add a comment to highlight this?

2023-11-15 09:11 UTC, a-gleeson commented on taric_parsers/importer.py
> +        envelope = Envelope.new_envelope()
it may be easier to cover this on a call, I can contact you about this and I can update this after.

2023-11-15 09:13 UTC, a-gleeson commented on taric_parsers/importer.py
> +                            child_matches[object_match.__class__.__name__] += 1
Readability is imprortant, I am happy with it if you are,

2023-11-15 12:20 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +        envelope = Envelope.new_envelope()
agreed not an issue, will investigate the use of composit_key in another ticket

2023-11-15 12:32 UTC, dougmills-DIT commented on taric_parsers/parsers/taric_parser.py
> +        This method checks that the parser that represents a TARIC object can be saved to a TAP model by checking associated issues recorded during validation
update comments and add together

2023-11-15 14:29 UTC, dougmills-DIT commented on taric_parsers/parsers/taric_parser.py
> +        for field in self.identity_fields_for_parent():
updated using values

2023-11-15 14:31 UTC, dougmills-DIT commented on taric_parsers/parsers/quota_parser.py
> +    def data(self):
the object QuotaEvent has a data attribute thats is a joining of multiple properties, TAP mildly cares about. This is the way we join those properties together as a json string

2023-11-15 14:31 UTC, dougmills-DIT commented on taric_parsers/parsers/measure_parser.py
> +    # language_id: str = None
updated!

2023-11-15 14:33 UTC, dougmills-DIT commented on taric_parsers/namespaces.py
> +TARIC_RECORD_GROUPS: Dict[str, Sequence[str]] = dict(
discussed on call, will skip this one. the duplication will be removed when the current importer is decommissioned

2023-11-16 10:59 UTC, a-gleeson reviewed
Yield changes look good to me!

2023-11-21 10:21 UTC, paulpepper-trade commented on common/jinja2/layouts/layout.jinja
> +          "text": "New TARIC parser"
Could we give this parser a name other than "new" as that won't age well. Version 2 / V2 may be prefereable.

2023-11-21 15:53 UTC, paulpepper-trade commented on taric_parsers/chunker.py
> +def find_or_create_chunk(
What's the reasoning for keeping the chunker behaviour? If it's really required, then a module-level docstring would be useful to explain why.

2023-11-21 15:53 UTC, paulpepper-trade commented on taric_parsers/chunker.py
> +    before writing to the database is O(n).
I think this docstring is taken from the original importer? Are there better ways of avoiding that factoral time complexity growth (assuming that statement is about time and not space complexity) than using an object that is potentially saved on the file system!? I suspect strings aren't used because they're immutable and so you get lots of creation and garbage collection going on. If that's the reasoning, then perhaps a mutable data type such as [bytearray](https://docs.python.org/3/library/stdtypes.html#bytearray) or [StringIO](https://docs.python.org/3/library/io.html#io.StringIO), which I think are functionally equivalent for the purpose of chunking, would be preferable?

2023-11-21 16:36 UTC, a-gleeson commented on taric_parsers/tasks.py
> +    get_partition_scheme(partition_scheme_setting)
Is this call used? as the return value isn't used

2023-11-21 16:42 UTC, a-gleeson commented on taric_parsers/tasks.py
> +    get_partition_scheme(partition_scheme_setting)
Is this call used? as the return value isn't used

2023-11-21 16:46 UTC, a-gleeson commented on taric_parsers/importer.py
> +        if self.status != "FAILED":
could this be simplified to `return self.status != "FAILED"` also if status are constants you could then refer to `"FAILED"` as `constant.FAILED`

2023-11-21 16:52 UTC, a-gleeson approved these changes
Left a couple more comments but I have finished reviewing the importer and approve. While I will have missed stuff I am sure others with a fresh pair of eyes will catch them!

2023-11-21 18:08 UTC, paulpepper-trade commented on taric_parsers/namespaces.py
> +    xml.etree.ElementTree
We'd normally add these as docstrings directly beneath the attributes that they're documenting. For instance like this: https://github.com/uktrade/tamato/blob/d3d0421d147e6d8c410231a7dba41e1947453ca1/common/models/trackedmodel.py#L66-L79

2023-11-21 18:27 UTC, paulpepper-trade commented on taric_parsers/namespaces.py
> +    def pattern(self):
Return type annotation perhaps?

2023-11-23 15:39 UTC, paulpepper-trade requested changes

2023-11-23 15:39 UTC, paulpepper-trade commented on requirements.txt
> +pytest-mock==3.11.1
Is pytest-mock being used? I don't see any instances of `PyMock` in the diff - I may have missed something. Although it looks interesting and may add some value, its repo (https://github.com/diddi-/pymock) doesn't get much attention - recent commits, stars or watchers

2023-11-23 15:39 UTC, paulpepper-trade commented on taric_parsers/chunker.py
> +def find_or_create_chunk(
The main concern is that it retains some of the complexity that we're hoping to get rid of. If it offer some value in exchange for that complexity, then it would be good to explain what that is in the module docstring.

2023-11-23 15:39 UTC, paulpepper-trade commented on taric_parsers/chunker.py
Has this file been pulled into this taric_parsers app verbatim or are there changes that we should note?

2023-11-23 15:39 UTC, paulpepper-trade commented on taric_parsers/forms.py
> +class NewImportFormMixin:
The "New" prefix won't age well, but I don't think any prefix is required anyway since it's namespaced by the taric_parsers app - it won't clash with a class of the same name in the importer module.
```suggestion
class ImportFormMixin:
```

2023-11-23 15:39 UTC, paulpepper-trade commented on taric_parsers/forms.py
> +        workbasket = WorkBasket.objects.create(
Is there an opportunity to avoid creating a workbasket at this point with the new parser, creating it only when the parser has successfully parsed its TARIC input? I think the current process only require the workbasket because of a combination of difficulties with the current importer: capturing workbasket title and parser workbasket dependencies.

2023-11-23 15:45 UTC, paulpepper-trade requested changes

2023-11-23 15:45 UTC, paulpepper-trade commented on taric_parsers/importer.py
> +from taric_parsers.parsers.taric_parser import *  # noqa
We shouldn't be using star imports - they make dependency navigation difficult, they hide what's being imported, etc.

2023-11-23 17:49 UTC, paulpepper-trade requested changes

2023-11-23 17:49 UTC, paulpepper-trade commented on taric_parsers/importer.py
> +            elif not author_username:
This could just be an `if` statement since there's no dependency relationship between this conditional statement and the previous one.

2023-11-23 17:49 UTC, paulpepper-trade commented on taric_parsers/importer.py
> +            self.workbasket.save()
I think this would be unnecessary if the caller were required to pass a `WorkBasket` instance into this `__init__()`, wouldn't it? You could then ditch the `workbasket_title` and `author_username` params and associated checks (which should be done by the WorkBasket's own validation anyway, making the validation in this function a redundant duplicate of that).

2023-11-23 17:49 UTC, paulpepper-trade commented on taric_parsers/importer.py
> +        return
Redundant return.

2023-11-23 17:49 UTC, paulpepper-trade commented on taric_parsers/importer.py
> +            BatchImportError.create_from_import_issue_report_item(issue, import_batch)
It's unusual for an `__init__()` method to do so much than initialisation. I think conventionally this kind of functionality would be placed in a member function that's called after initialisation. It would be easier to extend this class, make clear there's more to it than simple initialisation, self-document the function's behaviour through its name, perhaps return a useful value, etc.

2023-11-23 17:49 UTC, paulpepper-trade commented on taric_parsers/importer.py
> +    def ordered_transactions_and_messages(self, up_to_transaction=None):
A docstring and return type annotation would be helpful I think, especially since it's yielding a tuple.

2023-11-23 18:01 UTC, paulpepper-trade commented on taric_parsers/importer.py
> +            return "FAILED"
Or constant values in a choices data type.

2023-11-24 13:39 UTC, eadpearce commented on importer/models.py
> +    object_type = models.CharField(max_length=250)
Seems to be the same as ImportIssueReportItem.object_type which is documented here https://github.com/uktrade/tamato/pull/1015/files#diff-15211b62debbd8195d1d0a6ea7621b1f010d5e4a3ea3d00a3632a8ab21e34fd9R14

2023-11-24 14:30 UTC, paulpepper-trade commented on importer/models.py
> +    object_type = models.CharField(max_length=250)
It needs a docstring to that effect.

2023-11-24 15:37 UTC, dougmills-DIT commented on importer/models.py
> +    related_object_identity_keys = models.CharField(max_length=1000)
no, some taric object use a compound key to be identified, since not all have a SID

2023-11-24 15:48 UTC, paulpepper-trade commented on importer/models.py
> +    related_object_identity_keys = models.CharField(max_length=1000)
It probably needs a docstring to explain that. Edie similarly responded to a question in another comment (thanks @eadpearce). I guess if it's necessary to ask for an explanation in the PR, then it might also suggest a need for a docstring or some other way of clarifying the code.

2023-11-27 08:32 UTC, dougmills-DIT commented on common/jinja2/layouts/layout.jinja
> +          "text": "New TARIC parser"
Updated link to be importer v2

2023-11-27 08:32 UTC, dougmills-DIT commented on importer/migrations/0015_alter_batchimporterror_issue_type.py
> +class Migration(migrations.Migration):
done

2023-11-27 08:34 UTC, dougmills-DIT commented on importer/models.py
> +    object_type = models.CharField(max_length=250)
done

2023-11-27 08:36 UTC, dougmills-DIT commented on importer/models.py
> +    object_type = models.CharField(max_length=250)
I have been through all properties and added a description for the BatchImportError class

2023-11-27 09:17 UTC, dougmills-DIT commented on common/jinja2/layouts/layout.jinja
> +          "text": "New TARIC parser"
updated to importer V2

2023-11-27 09:57 UTC, dougmills-DIT commented on importer/models.py
> +    object_type = models.CharField(max_length=250)
ok, updated - on a broader note, and worth wider discussion - we could use flake8 to wrap pycodestyle and programatically enforce this type of check (on a file changed / created basis) to automate this sort of feedback. It would speed up the review process and improve standardisation across the code base

2023-11-27 09:58 UTC, dougmills-DIT commented on importer/models.py
> +        max_length=2000,
done

2023-11-27 10:03 UTC, dougmills-DIT commented on importer/models.py
> +    object_type = models.CharField(max_length=250)
I have updated the class comments to include all attributes, and methods. This will show up when calling help(BatchImportError) which I believe is an appropriate and standardised way of presenting this information, thoughts?

2023-11-27 10:07 UTC, dougmills-DIT commented on importer/models.py
> +    related_object_identity_keys = models.CharField(max_length=1000)
no - its a string of a dict - meta information for the relationship. It displays the actual values the importer was using to find a related object. Very useful for reviewing failed imports and resolving. 

This is an import error so the info is from the XML not the database, since in most cases it can't commit because if the error.

2023-11-27 10:10 UTC, paulpepper-trade commented on importer/models.py
> +    object_type = models.CharField(max_length=250)
I'm unsure what your suggestion would do, Doug. Are you suggesting using flake8 to enfore docstrings against all class attributes?

2023-11-27 10:11 UTC, dougmills-DIT commented on importer/models.py
> +    object_details = models.TextField(default=None)
its a string representation of the objects TARIC data (dict). Typically this would be used by DE to pull out information and find / correct the XML so the file imported.

2023-11-27 10:12 UTC, dougmills-DIT commented on importer/models.py
> +    @staticmethod
done! resolving

2023-11-27 10:16 UTC, paulpepper-trade commented on importer/models.py
> +    related_object_identity_keys = models.CharField(max_length=1000)
I'm still not completely clear about what it is. Since it contains a compound value that would need unpacking, then it probably needs a docstring to explain that and perhaps accompanying example.

2023-11-27 10:17 UTC, dougmills-DIT commented on pyproject.toml
> +    "new_importer"
done! resolving

2023-11-27 10:26 UTC, paulpepper-trade commented on importer/models.py
> +    object_type = models.CharField(max_length=250)
The closer the docstring is to the thing it's documenting the better:

- It's more likely to be updated if there's a change (for instance, a naming change).
- I expect most readers of the code would be doing so directly rather than using `help()`, so an adjacent docstring is easier to see than something in the class docstring.
- Although it's a standard approach, it's not the only standard :-)

2023-11-27 10:28 UTC, dougmills-DIT commented on pyproject.toml
> +#addopts = "-n=auto"
removed

2023-11-27 10:40 UTC, paulpepper-trade commented on importer/models.py
> +    object_details = models.TextField(default=None)
If it's a dict of the TARIC data, then would a JSONField be preferable here - similar to [a previous comment](https://github.com/uktrade/tamato/pull/1015#discussion_r1405940430).

2023-11-27 12:06 UTC, dougmills-DIT commented on importer/validators.py
> +class BatchImportErrorIssueType(models.TextChoices):
I think IssueType is too generic and does not appropriately describe the use, but ImportIssueType sounds fine! will update.

2023-11-27 12:23 UTC, dougmills-DIT commented on importer/validators.py
> +class BatchImportErrorIssueType(models.TextChoices):
Updated

2023-11-27 12:27 UTC, dougmills-DIT commented on requirements.txt
> +pytest-mock==3.11.1
yep - good spot - I had it in a test but was unused. removed!

2023-11-27 12:51 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +from taric_parsers.parsers.taric_parser import *  # noqa
yeah, tried to avoid doing that one because of quantity - but fine - if it improves dev experience its a fair point.

2023-11-29 08:02 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +        return
removed!

2023-11-29 08:14 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +    def ordered_transactions_and_messages(self, up_to_transaction=None):
added

2023-11-29 08:21 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +            elif not author_username:
done

2023-11-29 08:21 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +            self.workbasket.save()
agreed, removed!

2023-11-29 09:04 UTC, dougmills-DIT commented on taric_parsers/forms.py
> +        workbasket = WorkBasket.objects.create(
yep ok - was mirroring the existing behaviour in that case, happy to update this as I didnt like it either.

2023-11-30 14:24 UTC, dougmills-DIT commented on importer/forms.py
> +
removed

2023-11-30 14:38 UTC, dougmills-DIT commented on importer/models.py
> +    object_type = models.CharField(max_length=250)
yep, ok - updated as preferred

2023-11-30 14:44 UTC, dougmills-DIT commented on importer/models.py
> +    related_object_identity_keys = models.CharField(max_length=1000)
Primarily this will be displayed in the UI for a DE / Dev to review and identify the record in XML for manual change - I can update to json field no trouble.

2023-11-30 14:52 UTC, dougmills-DIT commented on importer/models.py
> +    related_object_identity_keys = models.CharField(max_length=1000)
Done

Note: this attribute has value when resolving issues with imports, and would currently need a human to review why it's an issue in most cases, as long as the value is in the UI a DE / dev can use this info to resolve, it does not matter if its a string or a jsonfield to that end, however as json it does provide additional validation and utility future  undetermined value if we wanted to do some programmatic work around it in the future, so makes sense, to save a potential messy conversion later.

2023-11-30 15:15 UTC, dougmills-DIT commented on importer/models.py
> +    object_details = models.TextField(default=None)
yep, updated this same time as i did related_object_identity_keys

2023-11-30 15:18 UTC, dougmills-DIT commented on importer/tasks.py
> +        record_code=record_code, status=ImporterChunkStatus.RUNNING, **kwargs
will check for updates, however there is no change to the stacking, just removal of "models."

2023-11-30 15:37 UTC, dougmills-DIT commented on taric_parsers/forms.py
> +class NewImportFormMixin:
yep, thats done

2023-12-01 10:38 UTC, dougmills-DIT commented on importer/tasks.py
> +        record_code=record_code, status=ImporterChunkStatus.RUNNING, **kwargs
I have updated pre-commit hooks - I was under the impression it will update as it runs / as needed. I added a section to readme to cover pre-commit hooks also, since there was nothing.

2023-12-04 15:41 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +        if self.status != "FAILED":
Ended up adding import Status rather than const, but implemented as above.

2023-12-05 09:49 UTC, dougmills-DIT commented on taric_parsers/importer.py
> +from taric_parsers.parsers.taric_parser import TransactionParser  # noqa
no 0- its needed

2023-12-05 09:52 UTC, paulpepper-trade commented on taric_parsers/importer.py
> +from taric_parsers.parsers.taric_parser import TransactionParser  # noqa
Why is it needed? It isn't obvious (to me at least).

2023-12-05 14:35 UTC, dougmills-DIT commented on taric_parsers/parsers/additional_code_parsers.py
> +class NewAdditionalCodeTypeParser(ValidityMixin, Writable, BaseTaricParser):
yep - just finished renaming all the parsers now.

2023-12-21 16:59 UTC, paulpepper-trade approved these changes

2024-01-10 14:33 UTC, merged