Notify HMRC of data uploads
uktrade/tamato pull request #102
Opened 2020-11-10 11:31 UTC by andyhd

The second stage of our data journey to HMRC is notifying their HTTPS API that files are
available in our bucket.

This commit implements an API client class, which sends the notification to the HMRC
Secure Data Exchange Notification API. It also records the time of notification in the
database.

See https://uktrade.atlassian.net/browse/TP-295

See HMRC API documentation at https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/secure-data-exchange-notifications/1.0

2020-11-10 13:51 UTC, stuaxo approved these changes
LGTM (review was quick, but I already read the changes before it was officially requested :) )

2020-11-10 16:32 UTC, NDevox requested changes
Small things, otherwise all ok.

How does this gel with `common.Transaction` at the moment?

2020-11-10 16:32 UTC, NDevox commented on common/tests/factories.py
> +    update_type = UpdateType.UPDATE
I may have updated this to `.CREATE` in my latest PR, as it doesn't make sense to have UPDATE as the default when making an initial object. Hopefully this doesn't impact you.

2020-11-10 16:32 UTC, NDevox commented on hmrc_sdes/api_client.py
> +from apiclient import APIClient
This looks like quite a dead project, which also warns off of using it as a dep. Do we definitely want to use it?

Especially considering the code is just:

```python3
class APIClient(object):
    BASE_URL = 'http://localhost:5000/'

    def __init__(self, rate_limit_lock=None, encoding='utf8'):
        self.rate_limit_lock = rate_limit_lock
        self.encoding = encoding
        self.connection_pool = self._make_connection_pool()

    def _make_connection_pool(self):
        return urllib3.PoolManager( cert_reqs='CERT_REQUIRED',
                                    ca_certs=certifi.where())

    def _compose_url(self, path, params=None):
        return self.BASE_URL + path + '?' + urlencode(params)

    def _handle_response(self, response):
        return json.loads(response.data.decode(self.encoding))

    def _request(self, method, path, params=None):
        url = self._compose_url(path, params)

        self.rate_limit_lock and self.rate_limit_lock.acquire()
        r = self.connection_pool.urlopen(method.upper(), url)

        return self._handle_response(r)

    def call(self, path, **params):
        return self._request('GET', path, params=params)
```

2020-11-10 16:32 UTC, NDevox commented on hmrc_sdes/api_client.py
> +        print(upload.notification_payload)
print

2020-11-10 16:32 UTC, NDevox commented on hmrc_sdes/models.py
> +            self.save()
What are we trying to do here?

2020-11-10 16:32 UTC, NDevox commented on hmrc_sdes/views.py
> +# Create your views here.
DEL

2020-11-11 10:59 UTC, andyhd commented on hmrc_sdes/api_client.py
> +from apiclient import APIClient
I don't see any warnings? It seems to be active - last commit was 2 months ago. https://github.com/MikeWooster/api-client

I just wanted to remove the boilerplate from a HTTP JSON API client which this module seems to do - except for the OAuth2 stuff that I had to hand-roll.

2020-11-11 11:01 UTC, andyhd commented on common/tests/factories.py
> +    update_type = UpdateType.UPDATE
Shouldn't impact me - this was just to pacify mypy

2020-11-11 11:08 UTC, andyhd commented on hmrc_sdes/models.py
> +            self.save()
This could probably just be a boolean. I was trying to anticipate unhappy path scenarios - when retrying failed notifications we probably want to avoid resending successful ones. I was imagining we would have some async process maybe.

2020-11-11 11:13 UTC, NDevox commented on hmrc_sdes/api_client.py
> +from apiclient import APIClient
🤦  I was looking at https://github.com/shazow/apiclient

This seems fine.

2020-11-11 11:14 UTC, andyhd commented
The `taric` app models are stubs for the work on TP-371. This task was higher priority, but really depends on that and TP-112.

2020-11-11 11:14 UTC, NDevox commented on hmrc_sdes/models.py
> +            self.save()
I think `else` is only called when an exception is not raised though? in this case the `try/except` doesn't actually do anything and could all just be top level

2020-11-11 11:16 UTC, NDevox commented
Yep stubs makes sense. ok

2020-11-11 11:18 UTC, andyhd commented on hmrc_sdes/models.py
> +            self.save()
🤦

2020-11-11 11:22 UTC, andyhd commented
I really only needed to include the Envelope model stub, but I accidentally started working on TP-371 before switching to this task and this was left-over code.

2020-11-11 11:28 UTC, NDevox approved these changes
Honestly having the stubs in actually works better for what I'm doing at the moment. LGTM

2020-11-11 11:50 UTC, merged

2020-11-11 13:00 UTC, stuaxo commented on taric/models.py
> +    def __str__(self):
Hi @richtier it would be great if django-doctor could link to source docs for it's suggestions like this, e.g.   

https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style.

I opened a ticket in Django about more granular links in the docs themselves
https://code.djangoproject.com/ticket/32185#ticket