TP2000-1012: Add extra fields to quota definition edit form
uktrade/tamato pull request #1023
Opened 2023-08-30 15:47 UTC by eadpearce

# TP2000-1012: Add extra fields to quota definition edit form

## Why

* Allows users to edit more info on quota definition periods

## What

* Allows editing of: description, volume, initial volume, critical state, critical threshold, measurement unit, measurement unit qualifier
* Maximum precision is always set to 3 so this is not editable

![FireShot Capture 062 - Edit quota definition details - Manage Trade Tariffs - localhost](https://github.com/uktrade/tamato/assets/25905279/f1d4681c-e6de-4c5c-808d-f1f751c38a16)

2023-09-04 06:02 UTC, SteveCN7 commented
Screenshot looks good, would it be possible to swap Measurements and Volumes around in the list so that volume is above the unit of measurements and measurement unit qualifier options?

2023-09-06 08:47 UTC, CPrich905 commented on quotas/forms.py
> +        coerce=lambda value: value == "True",
What is the reason for using a coerced value here rather than a boolean filter?

2023-09-06 08:54 UTC, CPrich905 requested changes
One clarification for my own interest, then just the change Steve has requested to the layout

2023-09-12 16:18 UTC, eadpearce commented on quotas/forms.py
> +        coerce=lambda value: value == "True",
Annoying a BooleanField in Django doesn't let you render it as radios with Yes/No options (which is what we wanted instead of a checkbox) so we have to use a TypedChoiceField instead

2023-09-12 16:20 UTC, eadpearce commented
> Screenshot looks good, would it be possible to swap Measurements and Volumes around in the list so that volume is above the unit of measurements and measurement unit qualifier options?

This was changed after feedback from Patrick. We thought it made more sense to state the units before the volume but tariff managers may feel differently

2023-09-14 03:46 UTC, SteveCN7 commented
> > Screenshot looks good, would it be possible to swap Measurements and Volumes around in the list so that volume is above the unit of measurements and measurement unit qualifier options?
> 
> This was changed after feedback from Patrick. We thought it made more sense to state the units before the volume but tariff managers may feel differently

Good to go then :-)

2023-09-15 09:40 UTC, CPrich905 commented on quotas/forms.py
> +        coerce=lambda value: value == "True",
Thanks! I might experiment with this as well for some of the search/filter page widgets as well as the different styles there are frustrating some of the TMs

2023-09-15 10:02 UTC, CPrich905 approved these changes

2023-09-15 10:33 UTC, merged