fixing certificates filter
uktrade/tamato pull request #1064
Opened 2023-10-05 15:16 UTC by CPrich905

# Clean up of Certificates filter on Measures Search page

## Why
Some clean up of the Certificate filter implemented while investigating a bug with TAP data.

## What
The value returned by the filter is a Certificate object meaning we don't need to retrieve the certificate object with 
`certificates = Certificate.objects.filter(sid=value.sid)`
Filtering by `trackedmodel_ptr_id` saves passing the whole object.

2023-10-05 16:45 UTC, mattjamc approved these changes
Looks good to me :)

2023-10-06 09:05 UTC, paulpepper-trade requested changes

2023-10-06 09:05 UTC, paulpepper-trade commented on measures/filters.py
> +            measure_ids = MeasureCondition.objects.filter(
I think this will get al versions, which is probably not desirable. It's unusual to reference the low-level `trackedmodel_ptr_id` too.

2023-10-06 09:11 UTC, CPrich905 commented on measures/filters.py
> +            measure_ids = MeasureCondition.objects.filter(
I might be mistaken, but in the test I ran it returned the same number of results as the previous filter. I may have caught an edge case however - happy to jump on a call and we can discuss?

2023-10-06 09:16 UTC, paulpepper-trade commented on measures/filters.py
> +                required_certificate=value.trackedmodel_ptr_id,
Using `trackedmodel_ptr_id` will reference a specific version of this Measure. It's necessary to use either the `TrackedModel.identifying_fields` (`sid` in the case of `Measure`) or `TrackedModel.version_group` - they're generally, functionally equivalent when it comes to getting the versions of any `TrackedModel`. You can then use `TrackedModelQuerySet.current()` and related methods to get the correct version.

2023-10-06 09:28 UTC, paulpepper-trade commented on measures/filters.py
> +            measure_ids = MeasureCondition.objects.filter(
It looks as though `measures.tests.test_filters.test_filter_by_certificates` doesn't test for the case of measures with multiple versions - only multiple measures each with a single version.

2023-10-06 15:26 UTC, paulpepper-trade commented on measures/filters.py
> +                required_certificate=value.trackedmodel_ptr_id,
I think it would be enough to replace this with

```required_certificate=value
```

2023-10-09 12:20 UTC, merged