Add a test hitting the HMRC sandbox API
uktrade/tamato pull request #111
Opened 2020-11-19 17:47 UTC by andyhd

Run the test with `pytest hmrc_sdes --test-hmrc-api`. The test will be skipped if the
command line argument is omitted.

2020-11-19 18:25 UTC, simonwo approved these changes
I'm a fan.

2020-11-19 18:25 UTC, simonwo commented on hmrc_sdes/api_client.py
> +                "Gov-Client-User-IDs": "os=test",
Do what extent does this stuff need to be correct? E.g. do we need to be pulling `Debian/Buster` from some OS call? And does `os=test` need to change in a prod environment? Maybe not in scope for this PR but just asking.

2020-11-19 18:25 UTC, simonwo commented on hmrc_sdes/tests/test_client.py
> +        pytest.skip(msg="Not hitting HMRC API for real")
How sensible would it be in the future to run this in CI? Assuming we can load test secrets in CI… or is that against the rules? Would we need to use a private CI instance for that?

2020-11-20 09:37 UTC, andyhd commented on hmrc_sdes/api_client.py
> +                "Gov-Client-User-IDs": "os=test",
Good question, I constructed these values just to avoid errors from the Fraud Prevention Test API and I don't know what these values should be. I don't even think that these are meaningful, as we don't have an "originating device" and we're not making the request on the behalf of a user, but the test API complains if these headers are missing or blank.

2020-11-20 09:40 UTC, andyhd commented on hmrc_sdes/tests/test_client.py
> +        pytest.skip(msg="Not hitting HMRC API for real")
For infrequent builds (eg merging to master) I think it should be fine. It's only hitting the HMRC sandbox API, so no real data or effects. Just so long as we avoid spamming their API and the test doesn't run too slowly. Which reminds me - I should check that the request has a timeout.

2020-11-20 11:46 UTC, NDevox requested changes
Some minor comments otherwise all OK.

I don't have an issue with skipping a test by default - I think it's good to have tests even if they're only run in specific circumstances.

For the `.env` thing, bleh. I've added a blank `.env` file to my project now as we have a few other things requiring it.

The test currently failing would ideally be fixed 😇 .

For the test making a real HTTP request against a 3rd party. Whilst I think it's fine to have as default skipped, I wouldn't run it under any CI. I've worked on a few projects with tests like these that run on every test run. Although they are useful with the initial setup when run on every test run they become a burden. It generally only acts as a signal for one of two things:

1) The 3rd party service is down.
2) The 3rd party deprecated some feature we were using and we weren't paying attention enough to realise.

Both will be signalled, at the same time if not earlier, by production failing to communicate with the API. Whereas the test hitting the API just slows things down and adds network costs (luckily for us not so bad, I've seen a client spend thousands on tests hitting 3rd parties 🤦 ).

If you want to test that you are sending the right kind of request to the API, then a regression test will do just as well. Whereas if you want to assert the communication with the API still works truly, it can be done independently by a dev running the tests with the flag provided outside of CI.

2020-11-20 11:46 UTC, NDevox commented on hmrc_sdes/tests/test_client.py
> +        pytest.skip(msg="Not hitting HMRC API for real")
I did something similar for an old project where we split tests into unit and integration tests.

We marked all integration tests like so:

```python3
@pytest.mark.integration
def test_integration():
    # do something
```

Then if we wanted to run only the unit tests we could run `pytest -m "not integration"`. If we wanted to only run integration tests we could run `pytest -m "integration"` and so on.

I do like the custom flag approach similar to this however - seems a bit clearer. Pytest have an interesting example [here](https://docs.pytest.org/en/stable/example/markers.html#custom-marker-and-command-line-option-to-control-test-runs) where you won't have to write the skip logic within the individual test. Maybe it would be better to do that?

2020-11-20 11:46 UTC, NDevox commented on hmrc_sdes/tests/test_client.py
> +    dotenv.read_dotenv(os.path.join(os.path.dirname(__file__), "..", "..", ".env"))
`settings.BASE_DIR`?

2020-11-20 11:46 UTC, NDevox commented on hmrc_sdes/tests/test_client.py
> +    pprint(result)
print

2020-11-20 11:46 UTC, NDevox commented on hmrc_sdes/tests/test_client.py
> +    pprint(upload.notification_payload)
print

2020-11-20 11:46 UTC, NDevox commented on hmrc_sdes/tests/test_client.py
> +    }
Aren't these already defined in the settings?

2020-11-20 11:46 UTC, NDevox commented on settings/common.py
> +    "device_id": str(uuid.uuid4()),
This will change for every process. Is that ok?

2020-12-10 12:31 UTC, stuaxo commented on hmrc_sdes/api_client.py
> +                "Gov-Client-User-IDs": "os=test",
I'd add a short TODO comment along those lines, it's possible in the future we may have a better understanding of what this API wants.

2020-12-10 12:36 UTC, stuaxo reviewed
Overall I reckon hitting their API now makes sense (not only do we keep our understanding of their API up to date, but if they change it we will know quickly).

Once we have a good understanding of how the real API acts it would be good to replace this with something that doesn't hit an external API - along the lines of mocking the return value of request.get, using real data we have retrieved from their API).

2020-12-10 12:38 UTC, stuaxo commented on settings/common.py
>  }
If there are docs for these data structures from HMRC then it would be good to mention them in the comments somewhere near where they are created (further up in this file, but github makes it tricky for me to place the comment there).

2020-12-11 10:19 UTC, andyhd commented on settings/common.py
> +    "device_id": str(uuid.uuid4()),
Unknown. We don't really have a "device", as I believe it's intended to identify the client. I'm waiting for a response from HMRC on the correct values for these headers.

2020-12-11 10:24 UTC, andyhd commented on hmrc_sdes/tests/test_client.py
> +        pytest.skip(msg="Not hitting HMRC API for real")
That is nice 👍

2020-12-14 17:11 UTC, NDevox commented on settings/common.py
> +    "device_id": str(uuid.uuid4()),
👍

2020-12-14 17:12 UTC, NDevox approved these changes

2020-12-14 17:14 UTC, merged