TP2000-1152-handling-invalid-workbaskets
uktrade/tamato pull request #1123
Opened 2024-01-11 10:28 UTC by mattjamc

# TP2000-1152 Handling invalid workbaskets

## Why

Currently if a user accesses a view covered by the _require_current_workbasket_ decorator and they don't have an active workbasket, they will be assigned a different workbasket without being notified.

This is particularly problematic if a user's current workbasket gets edited/queued by someone else and it is no longer in the EDITING state. In this scenario, when the user submits their next http request their workbasket will change and they might start making updates in the wrong workbasket.

## What (part 1)

This PR:

- updates the _require_current_workbasket_ decorator. If a workbasket is required and the user doesn't have an active workbasket then it redirects them to select a new workbasket instead of assigning them a different one
- adds template, view and url for the new page
- adds tests to confirm redirect when a user's session workbasket is deleted or queued

As various tests relied on being randomly assigned a workbasket without creating one, this PR also makes the following test changes:

- adds two new fixtures similar to valid_user_client / valid_user_api_client but which also create a workbasket and add it to the session
- updates tests to use the new fixtures where a workbasket wasn't previously created in the test but was needed
- updates _workbasket_ fixture to return existing workbasket if one was already created by a different fixture rather than making a second 

<img width="1023" alt="image" src="https://github.com/uktrade/tamato/assets/97194636/3cd471a4-e00f-46fe-ac23-81039bb819e2">

## What (part 2)
In order to merge with TP2000-1130--extend-user-model this PR updates current WorkBasket methods and pytest fixtures to account for the workbasket now being stored in the user model rather than session data.

### New model methods

- assign_to_user - assigns workbasket to the user of request
- remove_users_current_workbasket - removes users assigned current workbasket 

### Removed model methods

- save_to_session - previously saved workbasket to the session of request
- load_from_session - previously queried session workbasket from database
- remove_current_from_session - previously deleted the workbasket from the session data

### New fixtures

- client_with_current_workbasket - returns a valid user client with a workbasket associated to the user (accounts for tests which did not previously have a workbasket created since now one doesn't get created automatically)
- api_client_with_current_workbasket - returns a valid user client with a workbasket associated to the user
- session_request_with_workbasket - returns a request object with a valid user, session and workbasket associated
- user_workbasket - returns a workbasket which has been assigned to a valid logged-in user with 2 footnotes in it
- user_empty_workbasket - returns an empty workbasket which bas been assigned to a valid logged in user

### Removed fixtures

- session_workbasket - previously returned a workbasket in the session
- session_empty_workbasket - previously returned an empty workbasket in the session

2024-01-18 14:31 UTC, eadpearce commented on workbaskets/models.py
> +    def remove_users_current_workbasket(cls, request):
Because of the lack of apostrophe this method name may be confusing to read (mistaking singular possessive for plural). Use 'from' instead like the old method eg `remove_current_from_user`

2024-01-18 14:34 UTC, eadpearce commented on workbaskets/migrations/0001_initial.py
> +def change_user_content_type(apps, schema_editor):
Shouldn't this be in a new migration rather than initial? I think envs that have already run the old version of this file won't rerun it with the new changes

2024-01-18 16:25 UTC, dalecannon commented on workbaskets/migrations/0001_initial.py
> +def change_user_content_type(apps, schema_editor):
Ah yes. This was meant to go in  `0009_user_current_workbasket.py` migration file so that it will be applied and performed.

2024-01-23 17:49 UTC, paulpepper-trade requested changes

2024-01-23 17:49 UTC, paulpepper-trade commented on workbaskets/models.py
> +            current_user = User.objects.get(id=request.user.id)
Redundant DB access to re-fetch `request.user` - see previous comment.

2024-01-23 17:49 UTC, paulpepper-trade commented on workbaskets/admin.py
> +
Perhaps worth including some screenshots of the User admin pages on the cover of this PR?

2024-01-23 17:49 UTC, paulpepper-trade commented on workbaskets/models.py
> +class User(AbstractUser):
I can see why an existing app has to be used, but I'm somewhat curious to understand why the `User` model has been placed in the workbaskets app, rather than, say, `common`. Were there some difficulties putting there?

2024-01-24 10:31 UTC, mattjamc commented on workbaskets/models.py
> +    def remove_current_from_user(cls, request):
I think it was just a case that the previous remove current workbasket from session function was here and it only gets used by the current() function directly below - but happy to move if that makes more sense :)

2024-01-24 10:54 UTC, dalecannon commented on workbaskets/models.py
> +class User(AbstractUser):
There's a circular dependency issue where `common.0001_initial` has `workbaskets.0001_initial` as a dependency and `workbaskets.0001_initial` requires the `User` model for foreign key fields on `WorkBasket` model.

Saying that, I wonder if the migration operation that adds the User model foreign key fields can be moved to the next migration file (workbaskets.0002...), resolving the dependency issue.

2024-01-24 12:41 UTC, dalecannon commented on commodities/tests/test_migrations.py
> +    user = User.objects.create()
Using factories seemed to cause errors in existing migration tests following the change to a custom user model. 

From what I could gather, the factories use current model definitions to create objects but the migration test sets the state of the database according to the specified migration, making it so only model definitions as they were defined at that point in migration history (`old_state.apps.get_model("app", "model")`) can be used.

This poses a problem for factories that directly or indirectly require a `UserFactory`, as the test database will complain that `current_workbasket` column doesn’t exist in the `User` table because of a mismatch between the factory model definition and the state of the test database preceding the addition of the new field on the User model.

2024-01-24 14:15 UTC, mattjamc commented on common/models/utils.py
> -
Yes I think this achieves more or less the same thing but I can bring the middleware back for extra security - it was more difficult to keep the middleware when workbasket was still in session but now it should be fine

2024-01-29 16:21 UTC, paulpepper-trade commented on commodities/tests/test_migrations.py
>      setup_content_types(old_state.apps)
Was there a problem with removing the `setup_content_types` fixture?

2024-01-29 16:23 UTC, paulpepper-trade commented on commodities/tests/test_migrations.py
>      setup_content_types(old_state.apps)
Oh, I can see it's gone now.

2024-01-29 16:31 UTC, paulpepper-trade approved these changes

2024-01-29 16:39 UTC, merged