Tp 409 add celery
uktrade/tamato pull request #113
Opened 2020-11-24 10:13 UTC by stuaxo

Initially add celery.

2020-11-24 10:29 UTC, NDevox requested changes
Small things and asking to discuss redis vs rabbit

2020-11-24 10:29 UTC, NDevox commented on docker-compose.yml
> +    command: -A celery_app.celery beat --loglevel=info
That's not a worker!

2020-11-24 10:29 UTC, NDevox commented on common/celery.py
> +app.config_from_object("django.conf:settings", namespace="CELERY")
I don't think there are any Celery settings included in this PR?

2020-11-24 10:29 UTC, NDevox commented on docker-compose.yml
> +
Do we want to use redis over rabbitmq for this? Given https://docs.celeryproject.org/en/stable/getting-started/brokers/redis.html#redis-caveats.

I do want to say I would like to use redis for caching anyway 😄  although I don't know how well we can handle mixing the concerns.

2020-11-24 10:48 UTC, stuaxo commented on docker-compose.yml
> +    command: -A celery_app.celery beat --loglevel=info
Oh no!  oops!

2020-11-24 10:49 UTC, stuaxo commented on common/celery.py
> +app.config_from_object("django.conf:settings", namespace="CELERY")
There are not, but... I probably should... I'll add some logging settings to justify this..

2020-11-24 11:28 UTC, stuaxo commented on docker-compose.yml
> +
Maybe... not, or at least YAGNI for now so I'll switch to RabbitMQ.

Good point about separation of concerns, have used this before when the concern was more "we have redis already and getting anything else is difficult" - it turns out redis was the only backend that supported some of the chord/group primitives in 4.0, so worked out well.

2020-11-24 16:37 UTC, simonwo reviewed
LGTM, but can we add some info to the README about needing to set up Redis/Rabbit? https://github.com/uktrade/tamato#running-locally

2020-11-24 18:34 UTC, stuaxo commented on docker-compose.yml
> +
After a conversation on Teams, we decided to keep Redis as it will be needed for other things fairly soon as well.

2020-11-24 18:35 UTC, stuaxo commented
> LGTM, but can we add some info to the README about needing to set up Redis/Rabbit? https://github.com/uktrade/tamato#running-locally

Will do, same for celery itself.

2020-11-26 08:59 UTC, stuaxo commented on docker-compose.yml
> +    command: -A celery_app.celery beat --loglevel=info
Sorted.

2020-11-26 08:59 UTC, stuaxo commented on common/celery.py
> +app.config_from_object("django.conf:settings", namespace="CELERY")
Sorted

2020-11-26 09:02 UTC, stuaxo commented
> > LGTM, but can we add some info to the README about needing to set up Redis/Rabbit? https://github.com/uktrade/tamato#running-locally
> 
> Will do, same for celery itself.

Ran this locally and updated, let me know if anything is missing or could be improved for clarity.

2020-11-26 09:20 UTC, NDevox approved these changes
LGTM

2020-11-26 10:33 UTC, andyhd reviewed
Still reviewing...

2020-11-26 10:33 UTC, andyhd commented on README.md
> +     ./manage.py dump_workbaskets [-o filename]
I'm not sure workbaskets should be the term used. Workbaskets are purely a user interface concept. We upload bunches of transactions.

2020-11-26 10:54 UTC, andyhd commented on conftest.py
> +pytest_plugins = ("celery.contrib.pytest",)
Just for consistency with other pytest plugins, maybe prefer adding `pytest-celery` to `requirements.txt` to this.

2020-11-26 11:03 UTC, andyhd commented on exporter/tasks.py
> +    #      command from here.
This could be clearer. Does it mean refactor the `upload_workbaskets` command `handle` method to call a new function and replace `call_command("upload_workbaskets")` here with a call to that new function?

2020-11-26 11:06 UTC, andyhd approved these changes
LGTM, except that naming quibble

2020-11-26 12:22 UTC, stuaxo commented on exporter/tasks.py
> +    #      command from here.
Yes, thanks for deciphering that :)

2020-11-26 16:53 UTC, stuaxo commented on README.md
> +     ./manage.py dump_workbaskets [-o filename]
Probably the best thing is if I change the name to `transactions` here and continue in the next ticket, which integrates this with the notification work you've done.

I think there will be further integration work once the ticket you're currently working on is in.

2020-12-08 15:30 UTC, merged

2020-12-08 15:33 UTC, andyhd commented on Dockerfile
> +RUN mkdir /home/tamato/app
Not needed - `WORKDIR` creates the directory if it doesn't exist. Best to keep the number of layers in the Dockerfile to a minimum.

2020-12-08 15:35 UTC, andyhd commented on Dockerfile
> +ADD ./ /home/tamato/app/
Is this not already done in line 36?

2020-12-08 15:36 UTC, andyhd commented on Dockerfile
> +ADD ./ /home/tamato/app/
Also, `COPY` is preferred over `ADD` unless you need the extra functionality

2020-12-08 17:25 UTC, stuaxo commented on Dockerfile
> +ADD ./ /home/tamato/app/
I'll fix these in TP-464.   Need to check the difference between ADD and COPY.  Not sure if this was the thing that let me edit the files in the web app live or not, but that's what I was aiming for.