TP-568 Search Additional Codes
uktrade/tamato pull request #151
Opened 2021-01-18 12:44 UTC by DIT-CJWaszczuk

2021-01-18 12:50 UTC, DIT-CJWaszczuk commented
Wanted to get some early looks at list, There's quite a bit going on that me and Nick have changed, would be good to get some eyes on it.

2021-01-18 14:51 UTC, stuaxo commented
On first look, LGTM - obv will get to know some of this more as time goes on.

2021-01-18 14:57 UTC, NDevox requested changes
Couple bits and pieces

2021-01-18 14:57 UTC, NDevox commented on additional_codes/filters.py
> +        help_text="Select all that apply",
This is single choice now so the label is misleading.

2021-01-18 14:57 UTC, NDevox commented on additional_codes/filters.py
> +from .forms import SearchFilterForm
Would probably be better to do an explicit import (as done above, `from additional_codes.forms import SearchFilterForm`. It will have to go between `AdditionalCode` and `TypeChoices`

2021-01-18 14:57 UTC, NDevox commented on additional_codes/jinja2/additional_codes/list.jinja
> +                  href="?page={{ page_obj.next_page_number() }}"
Loses the filters when going to next page

2021-01-18 14:57 UTC, NDevox commented on additional_codes/jinja2/additional_codes/list.jinja
> +                  href="?page={{ page_obj.previous_page_number() }}"
Loses the filters when going to previous page

2021-01-18 15:01 UTC, NDevox commented on additional_codes/jinja2/additional_codes/list.jinja
> +                  href="?page={{ page_obj.previous_page_number() }}"
You should be able to get these from the request object (`request.GET.search` and so on.)

2021-01-18 15:08 UTC, andyhd approved these changes
Looks good to me, only very minor comments

2021-01-18 15:08 UTC, andyhd commented on additional_codes/filters.py
> +        given year, but not of the previous year.
Postgres does provide the [datetime EXTRACT function](https://www.postgresql.org/docs/9.1/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT), which you could potentially use instead?

2021-01-18 15:08 UTC, andyhd commented on additional_codes/urls.py
> +from additional_codes.filters import COMBINED_ADDITIONAL_CODE_AND_TYPE_ID
Imported but not used?

2021-01-18 15:08 UTC, andyhd commented on common/static/common/scss/_layout.scss
> +  background: #f3f2f1;
Should this be `govuk-colour("light-grey")`?

2021-01-18 15:09 UTC, NDevox commented on additional_codes/filters.py
> +    for year in range(date.today().year, date.today().year - 10, -1)
Good point on the constants, I prefer this.

2021-01-18 15:26 UTC, NDevox commented on additional_codes/filters.py
> +        given year, but not of the previous year.
This is far better.

Equivalent is:

```python3
if value:
    queryset = queryset.objects.annotate(start_year=Extract(Lower("valid_between", output_field=DateTimeField()), "year")).filter(start_year__in=value)
return queryset
```

This replaces the whole function.

2021-01-18 15:49 UTC, andyhd commented on additional_codes/filters.py
> +        given year, but not of the previous year.
Ah thanks, I was too lazy to look up how to actually use the Extract function in Django 😴

2021-01-19 12:02 UTC, andyhd commented on additional_codes/forms.py
> +        super(SearchFilterForm, self).__init__(*args, **kwargs)
You can omit the arguments to `super()` in Python 3

2021-01-19 12:12 UTC, andyhd commented on additional_codes/jinja2/additional_codes/list.jinja
> +                  href="?page={{ page_obj.previous_page_number() }}"
It may be useful to add a custom filter or global function to the Jinja environment to do allow updating the current URL with the previous or next page number. [This example is of a Django template tag](https://stackoverflow.com/a/16609498), but could be easily adapted.

2021-01-19 12:13 UTC, NDevox commented on additional_codes/filters.py
> +        choices=last_10_years(),
You want to pass this in without the parens, i.e. `choice=last_10_years`. So we pass the function instead of the result of the function.

2021-01-19 14:44 UTC, NDevox commented on additional_codes/filters.py
> +        given year, but not of the previous year.
@CJWaszczuk shall we implement this one?

2021-01-19 14:44 UTC, NDevox commented on additional_codes/jinja2/additional_codes/list.jinja
> +{{update_params(request.args)}}
What does this do?

2021-01-19 15:23 UTC, NDevox approved these changes
LGTM

2021-01-19 15:27 UTC, merged