TP-580 Refactor footnote list page
uktrade/tamato pull request #169
Opened 2021-01-28 17:41 UTC by DIT-CJWaszczuk

2021-01-29 12:13 UTC, andyhd commented
If you install https://pre-commit.com/, it will run black on your files and prevent you committing files that need reformatting.

2021-01-29 12:23 UTC, DIT-CJWaszczuk commented
Will sort it now, keep meaning to and then forgetting

2021-01-29 15:46 UTC, andyhd reviewed
Odd variety of Javascript styles in one module, but no real problems. I would approve, but I'm not sure the list of footnote type IDs is correct.

2021-01-29 15:46 UTC, andyhd commented on common/static/common/js/showHideCheckboxes.js
> +        });
I feel like this would be better as an arrow function
```javascript
this.button.addEventListener('click', () => { this.revealChoices(); });
```
although could this be even more concise as
```javascript
this.button.addEventListener('click', this.revealChoices);
```

2021-01-29 15:46 UTC, andyhd commented on common/static/common/js/showHideCheckboxes.js
> +}
Is there a reason to not to use `class` style here?
```javascript
class FilterShowMore {
    constructor(module) {
        this.module = module;
        ...
    }
    init() {
        if (!this.module || !this.button) {
    ...
}
```
Even if we need to support older browsers or Internet Explorer, we can transpile.

2021-01-29 15:46 UTC, andyhd commented on common/static/common/js/showHideCheckboxes.js
> +    }
This could be
```javascript
let choices = Array.from(this.module.getElementsByClassName('app-js-hidden'));
choices.forEach((choice) => {
    choice.style.display = 'block';
});
```

2021-01-29 15:46 UTC, andyhd commented on footnotes/validators.py
> +    TORTURE_REPRESSION = "TR", "TR - Torture and repression"
These don't seem correct. For a start, these values don't all pass the regex validator for footnote_type_id (on line 50 below). Also if/when they are correct, it would be good to change the model field to a ChoiceField using these values.

2021-02-02 17:35 UTC, stuaxo commented on common/filters.py
> +    def field(self):
It looks like you are reimplementing @cached_property.

```python
    @cached_property
    def field(self):
        field_kwargs = {**self.extra.copy(), choices=self.get_field_choices()}
        field_kwargs.update(choices=self.get_field_choices())
        self.field_class(label=self.label, **field_kwargs)
```

I haven't looked at too long, but you may not even need field_kwargs as it's own variable.

2021-02-03 17:04 UTC, andyhd commented on common/static/common/js/showHideCheckboxes.js
> +            this.button.addEventListener('click', () => that.revealChoices());
Since this is now an arrow function, it isn't bound to its own `this`, so you don't need to `let that = this;` and you can do `() => this.revealChoices()` (and can that be shortened to `this.revealChoices`?)

2021-02-03 17:06 UTC, andyhd commented on footnotes/validators.py
> +from django.db.models import TextChoices
This isn't used any more - were the choices incorrect?

2021-02-03 17:09 UTC, andyhd commented on common/static/common/js/showHideCheckboxes.js
> +                    checkbox.classList.add('app-js-hidden')
We have both `app-js-hidden` and `hidden` - can we do with just one?

2021-02-03 17:10 UTC, andyhd approved these changes
Looks good to me.

2021-02-03 17:19 UTC, DIT-CJWaszczuk commented on footnotes/validators.py
> +from django.db.models import TextChoices
We chose to get them straight from the db to avoid choices with no results.

2021-02-03 17:20 UTC, andyhd commented on footnotes/validators.py
> +from django.db.models import TextChoices
Much better!

2021-02-04 11:09 UTC, DIT-CJWaszczuk commented on footnotes/validators.py
> +from django.db.models import TextChoices
Also, does black not catch unused imports?

2021-02-04 11:14 UTC, DIT-CJWaszczuk commented on common/static/common/js/showHideCheckboxes.js
> +                    checkbox.classList.add('app-js-hidden')
Switching all to just 'js-hidden', feel it's the most appropriate name.

2021-02-04 11:55 UTC, DIT-CJWaszczuk commented
Made all the  required changes, also tampered with  the table columns widths in the PR to avoid future asks. Mind taking a final check? @andyhd @stuaxo

2021-02-04 13:54 UTC, NDevox requested changes
Couple minor things

2021-02-04 13:54 UTC, NDevox commented on footnotes/filters.py
> +        choices=footnote_type_choices(),
We shouldn't call the function here (it make the "lazy" part of the filter redundant).

Instead remove the parens like so:

```python3

footnote_type = LazyMultipleChoiceFilter(
    choices=footnote_type_choices,
    ...
)
```

2021-02-04 13:54 UTC, NDevox commented on footnotes/filters.py
> +        field_name="type__sid",
I think it should be `field_name="footnote_type__footnote_type_id"`

2021-02-04 14:41 UTC, NDevox approved these changes
LGTM

2021-02-04 14:48 UTC, merged

2021-02-05 10:33 UTC, andyhd commented on common/static/common/js/showHideCheckboxes.js
> +}
You could have added `forEach` to the prototype. There's a documented [polyfill](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#polyfill).

2021-02-05 10:35 UTC, andyhd commented on footnotes/filters.py
> +            ),
```python
f"{footnote_type.footnote_type_id} - {footnote_type.description}"
```

2021-02-05 14:49 UTC, andyhd commented on footnotes/filters.py
> +    )
Since the choices now come from the database, you should use a [ModelMultipleChoiceFilter](https://django-filter.readthedocs.io/en/stable/ref/filters.html#modelchoicefilter-and-modelmultiplechoicefilter-arguments), eg:
```python
from django_filters import ModelMultipleChoiceFilter
...
class FootnoteFilter(...):
    footnote_type = ModelMultipleChoiceFilter(
        field_name="footnote_type__footnote_type_id",
        queryset=models.FootnoteType.objects.current(),
        label="Footnote Type",
        help_text="Select all that apply",
        required=False,
    )