TP-174 View / Search certificates
uktrade/tamato pull request #179
Opened 2021-02-04 16:37 UTC by DIT-CJWaszczuk

2021-02-05 10:36 UTC, NDevox requested changes
Couple small things, will have another check later

2021-02-05 10:36 UTC, NDevox commented on certificates/filters.py
> +        choices=certificate_type_choices(),
No parens here

2021-02-05 10:36 UTC, NDevox commented on certificates/views.py
> +        # .select_related("type")
should be `.select_related("certificate_type")`

2021-02-05 10:38 UTC, NDevox commented on certificates/models.py
> +            print(self.descriptions.all())
Remove print

2021-02-05 11:48 UTC, stuaxo commented on certificates/jinja2/includes/certificates_list.jinja
> +
I haven't seen this style of building tables before, where data is built up within the template and then passed to something like govukTable, but maybe it's a jinja2 style.

It does make the code quite readable, in other django projects the often data would be setup in the view, and then the table setup with {% block %} etc. 

I guess there isn't enough data for it to matter that there is an extra loop over the data with this.

2021-02-05 14:43 UTC, DIT-CJWaszczuk commented on certificates/jinja2/includes/certificates_list.jinja
> +
I see where you're going with this, I actually like the readability, but think if it was moved into the view, we could potentially move away from having a separate list file. Bit on the fence really. But yeah, the amount of data in this case is limited, so the extra loop would not cause any big issues.

2021-02-05 15:04 UTC, andyhd commented on certificates/jinja2/includes/certificates_list.jinja
> +
It's a side effect of using GOV.UK Frontend - their table macro wants a list of (JSON) rows, but if we want the row data to be calculated or styled, then we are forced to build the array either in the view and pass it via a context variable, or build it in the template (which has problems too - for example the ugly `]) or "" }}` which prevents the loop from outputting `None, None, None, ...`).

I think we could maybe write a better macro which uses [`call`](https://jinja.palletsprojects.com/en/2.11.x/templates/#call) to get something nicer, eg:
```jinja
{% call(certificate) tamato_list(object_list) %}
    <td><a class="govuk-link">{{ certificate.sid }}</a></td>
    ...
{% endcall %}

{% macro tamato_list(object_list) %}
  <table>
    ...
    {% for object in object_list %}
      <tr>{{ caller(object) }}</tr>
    {% endfor %}
  </table>
{% endmacro %}
```
but I'm not sure how we could integrate it with `govukTable`, or if it would be worth the effort.

2021-02-05 15:26 UTC, andyhd approved these changes
Looks good to me, not sure if it's worth the time to generalize the list template.

2021-02-05 15:26 UTC, andyhd commented on certificates/filters.py
> +    certificate_type = LazyMultipleChoiceFilter(
So, per [my posthumous comment on the previous PR](https://github.com/uktrade/tamato/pull/169#pullrequestreview-584407685), I think you can use `django_filters.ModelMultipleChoiceFilter` here, but you may need to investigate how to override the choice label generation.

2021-02-05 16:19 UTC, stuaxo commented on certificates/jinja2/includes/certificates_list.jinja
> +
Yeah, agree on both of these.

2021-02-08 11:16 UTC, DIT-CJWaszczuk commented
@NDevox Final check to make sure all your suggestions are sorted?

2021-02-08 11:26 UTC, NDevox approved these changes
LGTM

2021-02-08 11:27 UTC, merged