Add measure condition(s) string generation
uktrade/tamato pull request #219
Opened 2021-02-24 17:16 UTC by andyhd

When measures are listed in the UI, one of the column items is a list of conditions
associated with the measure.

This commit adds convenience methods and properties to the Measure model and associated
models to easily construct these lists.

This code was translated from the PHP prototype, which may not be complete or correct.

2021-02-24 17:34 UTC, stuaxo commented on measures/models.py
> +        print(measures, measure_types, additional_codes)
print

2021-02-24 17:36 UTC, stuaxo approved these changes
OK, cool - just remove the print statement I think ?

2021-02-24 22:48 UTC, andyhd commented
Django-treebeard reverted a change to the depth field on MP node models - hence the irrelevant migration.

2021-02-25 07:26 UTC, simonwo requested changes
I really appreciate the effort that has gone into translating this, but perhaps the PHP wasn’t as strong as it could be here! It looks like it used a bunch of hard-coded stuff that we have made space in the db for? So we instead need to solve the problem of how we get that new stuff that isn’t in TARIC XML in to the db at the right time (e.g. after the xml load but before use…)

I’m also wondering to what extent it would be appropriate to do something like the `DutySentenceMixin` here and shove a lot of this out to the DB. The reason being that this stuff will invoke a lot of queries in a loop and might be slow, whereas the overhead observed from the db version is observed to be less (for comparison, the snapshot function in the PHP takes 2 hours to output all 250,000 measures but the sql-only version can run in 3-4 minutes). Obviously we’re not displaying anything like that number in a page but if we get to some sort of bulk download feature *cough cough* it might become necessary. Would be good to hear thoughts on that!

2021-02-25 09:50 UTC, andyhd commented on measures/models.py
> +        }.get(self.code, self.code)
I knew that. I was just doing a direct port of the PHP to get something ready for Chris as soon as possible to avoid blocking the Measure UI. I can just remove this property and use `abbreviation` instead.

2021-02-25 09:52 UTC, andyhd commented on measures/validators.py
> +class MeasureConditionCode(models.TextChoices):
I didn't check that these were the same data, sorry.

2021-02-25 09:53 UTC, andyhd commented on measures/models.py
> +                out = f"{out} / {measurement.measurement_unit_qualifier.code}"
Yep, I just didn't have any examples of them to test. I'll replace this.

2021-02-25 09:56 UTC, andyhd commented
I am aware that this code is unperformant - I was just trying to get something that works without really understanding what or why the PHP does what it does. Make it work, then make it right, then make it fast 😄

2021-02-25 11:07 UTC, andyhd commented on measures/models.py
> +        return " ".join(out)
Unfortunately, `DutySentenceMixin` doesn't work with `MeasureConditionComponent` because it assumes the measurement column name is `component_measurement` when it is actually `condition_component_measurement`. It doesn't work with `MeasureCondition` either, for the same reason.

2021-02-25 11:27 UTC, andyhd commented on measures/models.py
> +        return " ".join(out)
Never mind, something weird is going on - when I directly call `MeasureCondition.objects.with_duty_sentence().first().duty_sentence` I get an error about a column `component_measurement_id` does not exist, but when I do the same thing in a test, it works.

2021-02-25 15:35 UTC, DIT-CJWaszczuk commented
Looks good to me from a FE perspective. Happy to go with it given that Simon is happy.

2021-02-25 15:35 UTC, DIT-CJWaszczuk approved these changes

2021-02-26 12:03 UTC, andyhd commented on measures/models.py
> +        return " ".join(out)
This string wasn't already handled by `DutySentenceMixin`, but I've added a similar queryset method to generate it.

2021-02-26 12:04 UTC, andyhd commented on measures/models.py
> +        )
I've hard-coded this for now - let's revisit if we need it somewhere else.

2021-02-26 15:03 UTC, simonwo approved these changes
Looks good to me! 😎

2021-02-26 15:03 UTC, simonwo commented on measures/models.py
> +                out.append(self.duty_sentence)
This seems to only output `self.duty_sentence` if any of these three conditions are met… so does it need to append to `out` or just do `return self.duty_sentence if … else ""`?

2021-02-26 15:03 UTC, simonwo commented on measures/migrations/0007_add_duty_expression_prefixes_and_measurement_unit_abbrevs.py
> +        migrations.RunSQL(
Nice 👍 We may need to work out at some point how to run this "again" if we start from a blank database and then import all of the XML, as these expressions won't exist yet. But no worries for now.

2021-02-26 15:16 UTC, andyhd commented on measures/models.py
> +                out.append(self.duty_sentence)
This is a weird bit of the PHP code. I'm not sure if we want to keep it. Here's the original:
```php
if (($this->measure_count == 1) && ($this->measure_type_count == 1) && ($this->additional_code_count == 1)) {
    foreach ($this->duty_list as $d) {
        $this->combined_duty .= $d->duty_string . " ";
    }
} else {
    if ($this->measure_type_count > 1) {
        if (in_array("105", $measure_type_list_unique)) {
            foreach ($this->duty_list as $d) {
                if ($d->measure_type_id == "105") {
                    $this->combined_duty .= $d->duty_string . " ";
                }
            }
        }
    } elseif ($this->additional_code_count > 1) {
        if (in_array("500", $additional_code_list_unique)) {
            foreach ($this->duty_list as $d) {
                if ($d->additional_code_id == "500") {
                    $this->combined_duty .= $d->duty_string . " ";
                }
            }
        }
        if (in_array("500", $additional_code_list_unique)) {
            foreach ($this->duty_list as $d) {
                if ($d->additional_code_id == "500") {
                    $this->combined_duty .= $d->duty_string . " ";
                }
            }
        }
    }
}
```
What do you think?

2021-02-26 15:17 UTC, andyhd commented on measures/models.py
> +                out.append(self.duty_sentence)
It seems to have a redundant `if (in_array("500", $addiditonal_code_list_unique))`, unless that is meant to appear twice. 🤷

2021-02-26 15:23 UTC, andyhd commented on measures/models.py
> +                out.append(self.duty_sentence)
Oh, and yes, I should clean up the logic.

2021-02-26 17:35 UTC, simonwo commented on measures/models.py
> +                out.append(self.duty_sentence)
I've just gone spelunking into the PHP to understand this and it's very odd indeed. For a start, it loads `duty_list` in one a class method but then seems to rely on attributes that are only loaded by `get_measure`… whatever. But then also the things it checks (`measure_type_id` and `additional_code_id`) don't seem to get populated anywhere.

So in short I've got no idea what this is meant to do or why it attached special meaning to measure type 105, which is to do with authorised use. 

I would advocate for dropping this logic entirely and just outputting the duty sentence if it isn't empty.

2021-02-26 17:35 UTC, simonwo commented on measures/models.py
> +                out.append(self.duty_sentence)
As ever, our users have no legacy expectations and we can iterate on this later.

2021-02-26 17:40 UTC, merged

2021-02-27 13:21 UTC, stuaxo commented
Ugh, good work diving into the PHP !