Replace object type with verbose name
uktrade/tamato pull request #248
Opened 2021-03-17 14:54 UTC by DIT-CJWaszczuk

## Summary
Apart from Quotas (we use `QuotaOrderNumber` for the data), we can remove the need for object_type and replace it with the verbose names.

2021-03-17 15:01 UTC, andyhd commented on common/jinja2/layouts/detail.jinja
> +      {"text": "Find and edit " ~ object._meta.verbose_name_plural, "href": find_edit_url},
I have a bit in my PR that allows you to do `object.get_url(action="list")` so you can get rid of `find_edit_url` too

2021-03-17 15:02 UTC, andyhd approved these changes
Looks good to me

2021-03-17 15:21 UTC, stuaxo approved these changes
Nice, there's so much handy stuff in _meta.

Good how this removes a bunch of variables.

2021-03-17 16:11 UTC, DIT-CJWaszczuk commented
This actually would not work, not in its current state anyway. If there are no results, there's no object to get the verbose name  from. Hmmm

2021-03-17 16:23 UTC, andyhd requested changes

2021-03-17 16:23 UTC, andyhd commented on common/jinja2/layouts/list.jinja
> +{% set page_title = "Find and edit " ~ object._meta.verbose_name_plural %}
This needs to be `object_list.model._meta.verbose_name_plural`

2021-03-18 08:48 UTC, simonwo approved these changes

2021-03-18 10:03 UTC, merged