TP-662 Edit additional code descriptions
uktrade/tamato pull request #267
Opened 2021-03-30 13:50 UTC by DIT-CJWaszczuk

## Summary 
Allow people to edit additional code descriptions 
## Screenshots 
### Description list
![image](https://user-images.githubusercontent.com/76431740/112998943-6b6e1400-9166-11eb-8df8-60f3e44c9d6f.png)
## Edit page 
![image](https://user-images.githubusercontent.com/76431740/112999555-f4854b00-9166-11eb-915e-25007d3d8ef3.png)
## Confirmation page 
![image](https://user-images.githubusercontent.com/76431740/112999874-38785000-9167-11eb-876d-857107584f70.png)

2021-03-31 09:23 UTC, simonwo commented on additional_codes/models.py
> +    identifying_fields = ("description_period_sid", "described_additional_code__sid")
Hm, are you sure? The `description_period_sid` should be enough to identify description models?

2021-03-31 09:26 UTC, NDevox commented on common/models/mixins.py
> +        for attr in self.__dict__:
Let's not use `__dict__`, it's pretty funky.

Best to do something like:

```python
for rel, _ in self.get_relations():
    if rel.name.startswith("described_"):
        return getattr(self, rel.name)
```

2021-03-31 09:26 UTC, NDevox commented on workbaskets/jinja2/includes/workbaskets/workbasket-detail.jinja
> +        <a class="govuk-link govuk-!-font-weight-bold" href="{{ obj.get_url() or "#" }}">{{ obj.get_described_object() if obj.get_described_object else obj.structure_code }}</a>
Is this right? And does this work when there isn't a `get_described_object`

2021-03-31 09:26 UTC, NDevox commented on additional_codes/views.py
> +        if self.request.method == "POST":
This looks like it should be something we do for all update views? Maybe a generic mixin?

2021-03-31 09:30 UTC, DIT-CJWaszczuk commented on workbaskets/jinja2/includes/workbaskets/workbasket-detail.jinja
> +        <a class="govuk-link govuk-!-font-weight-bold" href="{{ obj.get_url() or "#" }}">{{ obj.get_described_object() if obj.get_described_object else obj.structure_code }}</a>
Tried it with a list of all possible changes and it seems to hold up. I think if I tried to call the attribute it would break but the reference seems to be fine.

2021-03-31 10:00 UTC, andyhd requested changes
Looking good, just a couple of issues

2021-03-31 10:02 UTC, andyhd commented on additional_codes/views.py
> +        if self.request.method == "POST":
We tried that before, but ran into some problems with inheritance. We should take another look at some point.

2021-03-31 10:02 UTC, andyhd commented on common/models/mixins.py
> +        for attr in self.__dict__:
Much better!

2021-03-31 10:06 UTC, andyhd commented on additional_codes/models.py
> +    identifying_fields = ("description_period_sid", "described_additional_code__sid")
I think this is because `get_url` tries to build a URL using `identifying_fields`. The correct solution here is not to add to `identifying_fields`, but to override `get_url` in `AdditionalCode`.

2021-03-31 10:19 UTC, DIT-CJWaszczuk commented on additional_codes/views.py
> +        if self.request.method == "POST":
Think we had a crack at this before and it just doesn't override get_object properly, ends up breaking

2021-03-31 13:55 UTC, andyhd commented on additional_codes/models.py
> +    identifying_fields = ("description_period_sid", "described_additional_code__sid")
This is the change that is making the tests fail, btw

2021-04-01 09:30 UTC, andyhd approved these changes

2021-04-01 09:45 UTC, merged

2021-04-06 09:14 UTC, stuaxo commented on additional_codes/models.py
> +            return
Can't work out what I think about this return, normally it would be a `pass` as it's not really short-cutting any code.
Not a blocker though.

2021-04-06 09:42 UTC, andyhd commented on additional_codes/models.py
> +            return
Yeah, it should possibly be an explicit `return None`