TP-702 Edit certificate descriptions
uktrade/tamato pull request #286
Opened 2021-04-19 14:13 UTC by DIT-CJWaszczuk

## Summary 
Allow the user to edit certificate descriptions 
## Screenshots 
### List page
![image](https://user-images.githubusercontent.com/76431740/115250614-a938d980-a121-11eb-8477-714cfef128e8.png)
### Edit page
![image](https://user-images.githubusercontent.com/76431740/115250656-b229ab00-a121-11eb-89b2-aa9b5fce09ad.png)
### Confirmation page 
![image](https://user-images.githubusercontent.com/76431740/115250695-ba81e600-a121-11eb-8976-409d9f216d2a.png)
### Tariff changes page
![image](https://user-images.githubusercontent.com/76431740/115250593-a1793500-a121-11eb-8b51-7cb6c68969cf.png)

2021-04-19 15:19 UTC, simonwo reviewed
LGTM, but I'm not very familiar with Django front-end stuff so will let someone else approve.

2021-04-19 15:19 UTC, simonwo commented on additional_codes/models.py
You can actually just delete this line as `sid` is the implied default.

2021-04-19 15:19 UTC, simonwo commented on footnotes/models.py
> +    identifying_fields = ("sid",)
As per prev comment.

2021-04-19 15:19 UTC, simonwo commented on certificates/views.py
> +        return obj
This looks pretty generic… can we D.R.Y. it up somehow?

2021-04-19 16:46 UTC, andyhd commented on certificates/models.py
> +        if action == "edit" or "confirm-update":
These lines can be removed - if it's not a list view, then we need the kwargs. (Not that we have detail or list views of descriptions).

2021-04-19 16:46 UTC, andyhd commented on certificates/models.py
> +            }
You could potentially make this generic by doing something like
```python
kwargs = self.get_identifying_fields()  # this will be "sid"
rel = next(rel for rel in self.get_relations() if rel.name.startswith("described_"))
for field, value in self.get_described_object().get_identifying_fields().items():
    kwargs[f"{rel.name}__{field}"] = value
```
This could be DRYer, as `get_described_object()` does the same `for rel in self.get_relations() if ...` part. It could be factored out into a separate method and reused.

2021-04-19 16:46 UTC, andyhd commented on certificates/views.py
> +        return obj
I agree, can this be pulled into `DraftUpdateView`?

2021-04-21 09:28 UTC, andyhd commented on certificates/views.py
> +        return obj
Actually, can lines 116-120 be added to `TrackedModelDetailMixin`? I think that would solve the problem with inheritance.

2021-04-21 10:34 UTC, DIT-CJWaszczuk commented on certificates/views.py
> +        return obj
This seems to work, have pushed it up

2021-04-21 10:34 UTC, DIT-CJWaszczuk commented
@andyhd @simonwo Pushed up the changes, think this is good for a final look

2021-04-21 10:47 UTC, stuaxo commented on additional_codes/models.py
> +class AdditionalCodeDescription(DescriptionMixin, TrackedModel, ValidityMixin):
Seems weird having the concrete TrackedModel in the middle of the two mixins.   I'm sure the Mixins here are benign, but in other cases this sort of thing can cause strange behaviour.

2021-04-21 11:20 UTC, andyhd commented on additional_codes/models.py
> +class AdditionalCodeDescription(DescriptionMixin, TrackedModel, ValidityMixin):
Yes, the order usually matters, so `TrackedModel` should probably be last.
The method resolution order is left-to-right, so if you were accessing `additionalcodedescription.foo()`, Python would try to find the `foo` method in `AdditionalCodeDescription` first, then `DescriptionMixin`, then `TrackedModel` and then `ValidityMixin`.
I think in this particular case, the mixins and base model don't interact with each other, so it doesn't make any difference.

2021-04-21 11:27 UTC, andyhd reviewed
Looks good, but some small things to tidy up still

2021-04-21 11:27 UTC, andyhd commented on common/models/mixins.py
> +            print(kwargs)
Print

2021-04-21 11:27 UTC, andyhd commented on common/models/mixins.py
> +            kwargs = self.get_identifying_fields()  # this will be "sid"
Don't need this comment

2021-04-21 11:27 UTC, andyhd commented on common/models/mixins.py
> +                self.get_described_object().get_identifying_fields().items()
Don't call `get_described_object` twice

2021-04-21 11:27 UTC, andyhd commented on footnotes/models.py
> +class FootnoteDescription(DescriptionMixin, TrackedModel, ValidityMixin):
Is this the output of a linter? Seems incorrect behaviour if so.

2021-04-21 11:27 UTC, andyhd commented on workbaskets/views/generic.py
> +        return obj
Is this meant to be here?

2021-04-22 10:37 UTC, DIT-CJWaszczuk commented on common/models/mixins.py
> +                self.get_described_object().get_identifying_fields().items()
I've slightly tweaked this, the issue was predominantly that you could not perform the replace operation in the string format, so now there's a single call but two variables. Think it still retains the clean-ness without making a call for`get_described_object` twice

2021-04-22 10:52 UTC, andyhd approved these changes
Nice, nearly deleted more than you added 👍

2021-04-22 10:52 UTC, andyhd commented on common/models/mixins.py
> +            )
I don't want to hold up this PR any more, so I think we should put a ticket on the backlog to use `described_object._meta.model_name` here instead, and change the `described_{model}` fields in the `{model}Description` classes to match.

2021-04-22 11:12 UTC, simonwo approved these changes

2021-04-22 14:27 UTC, andyhd requested changes

2021-04-22 14:27 UTC, andyhd commented on additional_codes/import_parsers.py
>      described_additional_code__code = TextElement(Tag("additional.code"))
these need changing to `described_additionalcode`

2021-04-22 14:27 UTC, andyhd commented on additional_codes/jinja2/taric/additional_code_description.xml
>      <oub:additional.code>{{ record.described_additional_code.code }}</oub:additional.code>
and these

2021-04-22 14:27 UTC, andyhd commented on additional_codes/jinja2/taric/additional_code_description.xml
>      <oub:additional.code.type.id>{{ record.described_additional_code.type.sid }}</oub:additional.code.type.id>
same

2021-04-22 14:27 UTC, andyhd commented on additional_codes/models.py
>              identifying_fields=("described_additional_code", "valid_between"),
same here

2021-04-22 14:27 UTC, andyhd commented on additional_codes/serializers.py
>      described_additional_code = AdditionalCodeSerializer(read_only=True)
and here

2021-04-22 14:27 UTC, andyhd commented on additional_codes/serializers.py
>              "described_additional_code",
and here

2021-04-22 14:27 UTC, andyhd commented on additional_codes/serializers.py
>      described_additional_code = AdditionalCodeSerializer(required=False)
ditto

2021-04-22 14:27 UTC, andyhd commented on additional_codes/serializers.py
>              "described_additional_code",
ditto

2021-04-22 14:27 UTC, andyhd commented on common/tests/factories.py
>      described_additional_code = factory.SubFactory(AdditionalCodeFactory)
and finally, this one

2021-04-22 14:45 UTC, andyhd approved these changes

2021-04-22 16:37 UTC, stuaxo approved these changes

2021-04-26 13:46 UTC, merged