TP-739 Fix certificate search to find type and code together
uktrade/tamato pull request #292
Opened 2021-04-29 15:34 UTC by DIT-CJWaszczuk

## Summary
Before, if you searched on type and sid, it would fail. Now you can type on type, sid or both.
## Screenshots
![image](https://user-images.githubusercontent.com/76431740/116577818-bc5d5d80-a908-11eb-975e-f1275310adb8.png)

2021-04-29 15:46 UTC, andyhd requested changes

2021-04-29 15:46 UTC, andyhd commented on certificates/filters.py
> +    r"(?P<certificate_type__sid>[A-Z0-9])(?P<sid>[A-Z0-9]{3})",
These regexes should be imported from `certificates.validators`

2021-04-29 16:08 UTC, andyhd requested changes

2021-04-29 16:08 UTC, andyhd commented on certificates/validators.py
> +)
No, I mean you should reuse the existing regexes, eg:
```python
CERTIFICATE_TYPE_SID_REGEX = r"[A-Z0-9]{1}"
certificate_type_sid_validator = RegexValidator(fr"^{CERTIFICATE_TYPE_SID_REGEX}$")

CERTIFICATE_SID_REGEX = r"[A-Z0-9]{3}"
certificate_sid_validator = RegexValidator(fr"^{CERTIFICATE_SID_REGEX}$")

COMBINED_CERTIFICATE_AND_TYPE_ID = re.compile(
    fr"(?P<certificate_type__sid>{CERTIFICATE_TYPE_SID_REGEX})(?P<sid>{CERTIFICATE_SID_REGEX})",
)
```

That way, if we ever had to change them, we would only have to change them in one place.

2021-04-30 12:33 UTC, DIT-CJWaszczuk commented on certificates/validators.py
> +)
My head was not switched on!

2021-04-30 12:46 UTC, simonwo approved these changes
LGTM now.

2021-04-30 13:35 UTC, merged