TP-695 Edit Measure detail
uktrade/tamato pull request #294
Opened 2021-05-11 08:10 UTC by DIT-CJWaszczuk

2021-05-11 08:30 UTC, stuaxo commented on common/static/common/js/autocomplete.js
> +    return fetch(`http://localhost:8000/api/additional_codes/?search=${query}&format=json`)
Do you need a way to get the url for the site to the javascript ?

No idea if how "correct" it is, but one way is outputting these in a django template somewhere that generates a JS file, or just copying it from the django HTML template you include.

2021-05-11 08:32 UTC, stuaxo commented on common/static/common/scss/_accordion.scss
> +// Override GOV.UK accordion having 0 padding on the last child
Probably nit-picking, but it's always nice to include something in the blerb about why or where this is used...

`... on the last child so this can be used inline`  <-- (reason I made up)

2021-05-11 09:33 UTC, DIT-CJWaszczuk commented on measures/forms.py
> +        return cleaned_data
Yeah I haven't started on the clean method yet, I am probably going to need a BE dev to help me with this however!

2021-05-11 09:45 UTC, andyhd commented on common/filters.py
> +]
I expect this is just your linter doing this automatically, but I try to avoid including just formatting changes in a PR unless I have changed the code as it gives reviewers more to read unnecessarily.

2021-05-11 10:28 UTC, andyhd requested changes
I think this case is not workable with Crispy forms. Crispy is good when you can replace a long template with a single call to `{% crispy form %}`, but it is IMO making things worse when you have a massive `Layout` object structure in the form class.

2021-05-11 10:28 UTC, andyhd commented on measures/forms.py
> +        self.fields["end_date"].initial = self.instance.valid_between.upper or ""
The initial values of `start_date` and `end_date` should be a `datetime.date` or `None`, not an empty string. This would be better written as
```python
self.fields["start_date"].initial = self.instance.valid_between.lower
```

2021-05-11 10:28 UTC, andyhd commented on measures/forms.py
> +        )
These ternary expressions are not necessary. It's more straightforward to write them like
```python
initial_goods_nomenclature = ""
if self.instance.goods_nomenclature:
    initial_goods_nomenclature = f"{self.instance.goods_nomenclature} - {self.instance...description}"
```

2021-05-11 10:28 UTC, andyhd commented on measures/forms.py
> +                        "<div id='id_measure_type_hint' class='govuk-hint'>Select the appropriate measure type.</div>",
I think this form is stretching the usefulness of Crispy forms. The MVC separation of concerns is getting lost. The accordion layout is irrelevant to the form class, it is purely presentational and belongs in templates. Using Crispy is not providing a benefit in this case.

2021-05-11 10:32 UTC, stuaxo commented on common/static/common/js/autocomplete.js
> +    return fetch(`http://localhost:8000/api/additional_codes/?search=${query}&format=json`)
@andyhd  ^ yep, this :)   There's always `//` if you really need an absolute url.

2021-05-12 15:12 UTC, andyhd commented on common/jinja2.py
> +            "transform_snake_case": transform_snake_case,
This function name is only half self-documenting - it should be something like `snake_case_to_capwords` or similar, but the name is already long enough that the function doesn't save much typing over using the built-in Jinja filters: `{{ my_snake_case_string|replace("_", " ")|capitalize }}` or using the string methods inline: `{{ my_snake_case_string.replace("_", " ").capitalize() }}`.

2021-05-12 21:52 UTC, stuaxo commented on common/jinja2.py
> +            "transform_snake_case": transform_snake_case,
snake_case_to_capwords is not too bad, if this is used in more than a couple of places.

2021-05-17 15:33 UTC, andyhd commented
Github Actions seems to be wedged. Maybe another push will kickstart it?

2021-05-20 16:47 UTC, stuaxo commented on measures/forms.py
> +        print("CLEANED DATA", cleaned_data)
Print statement.

2021-05-20 16:48 UTC, stuaxo commented on measures/models.py
> +        return f"{self.sid}"
Not sure __unicode__ is used any more in python3.

2021-05-25 19:57 UTC, stuaxo commented on common/forms.py
> +        if value:
Only creating a variable on one branch of an `if` statement and then using it later makes me nervous someone might accidentally introduce a bug here later.

Could we initialise display_string to "" above the if, then always use display_string further down ?

2021-05-25 23:50 UTC, andyhd requested changes
Only one blocking issue, I think - one of the autocomplete URLs is `localhost:8000`

2021-05-25 23:50 UTC, andyhd commented on common/static/common/js/autocomplete.js
> +}
These getXResults functions are all very similar. You could DRY this up a bit like:
```javascript
const autocompletes = {
  "additional_code": {
    "url": "/api/additional_codes/",
    "resultFormatter": (result) => {
      value: result.id,
      string: `${result.type.sid}${result.code} - ${result.descriptions[0].description}`
    },
  },
  ...
}
function autocompleteFetcher(url, resultFormatter) {
  return (query, populateResults) => {
    return fetch(`${url}?search=${query}&format=json`)
      .then(response => populateResults(response.json().results.map(resultFormatter)));
  };
}
function template(result) {
  return result && result.string;
}
const initAutocomplete = () => {
  for (const [elementName, params] of autocompletes) {
    const {url, resultFormatter} = params;
    let element = document.querySelector(`#${elementName}_view_container`);
    let realElement = document.querySelector(`#${elementName}`);
    if (element) {
      accessibleAutocomplete({
        element: element,
        id: elementName,
        source: autocompleteFetcher(url, resultFormatter),
        defaultValue: element.dataset.originalValue,
        name: elementName, 
        templates: {
          inputValue: template,
          suggestion: template
        },
        onConfirm: (val) => {
          realElement.value = val.value
        }
      });
    }
  }
}
```

2021-05-25 23:50 UTC, andyhd commented on measures/forms.py
> +    valid_between = GovukDateRangeField(required=False)
You can use `common.forms.ValidityPeriodForm` as the superclass and remove these lines and the validity period initial values and validation

2021-05-25 23:50 UTC, andyhd commented on measures/models.py
> +        return f"{self.sid}"
This is probably better as `return str(self.sid)`

2021-05-25 23:50 UTC, andyhd commented on measures/views.py
> +from typing import Type
With python 3.9, you can use the builtin `type` for type hints and remove this import, eg:
`model: type[TrackedModel] = Measure`

2021-05-25 23:50 UTC, andyhd commented on regulations/models.py
> +        return f"{self.regulation_id}"
`return str(self.regulation_id)`

2021-05-26 09:02 UTC, andyhd commented on common/static/common/js/autocomplete.js
> +}
Also, why are some functions defined with `function name() {}` and others with `const name = () => {}`?

2021-05-26 11:12 UTC, andyhd approved these changes
👍

2021-05-26 13:14 UTC, merged