Clean up XML and importer tests
uktrade/tamato pull request #298
Opened 2021-05-17 13:01 UTC by simonwo

Here's some self-contained work that has fallen out of the XML performance branch – updates and deduplication of lots of test logic around the import and export features. Merging this now will give a much smaller PR for the XML work later.

> Our importer tests are quite verbose – in particular the same tests are repeated once for creation and again for delete/update. The two tests also have different styles but are functionally equivalent.
>
> There is no real need for this, so this commit removes this duplication. We now instead can simply call `imported_fields_match` once and this will test the importer for all variations of update type.

> Our XML tests validate that the XML we output is valid according to the TARIC3 spec and contain the elements we expect. They do this by checking for tags named correctly. They should also check that the namespace is correct – ultimately, tags that are named correctly but in the wrong namespace are not what we want. 
>
> This commit is a find/replace to add the correct namespaces to all of these checks.

2021-05-17 13:08 UTC, stuaxo commented on common/tests/factories.py
> +        class SpecialisedFactory(cls):
This could use a docstring to say what it is / what it is for.

2021-05-17 13:20 UTC, stuaxo commented on conftest.py
>      Provides a function for checking a model can be imported correctly.
Possibly "Return a function that verifies a ..." may be less ambiguous - though maybe "Provides a .." is a pytest thing ?

2021-05-17 13:23 UTC, stuaxo commented on conftest.py
>      """
If the language here is "previously created object", there should be a comment further down with similar language so it's easy to see where the code that creates the "previously created object".

A hint about the functionality provided that is similar to run_xml_import would be nice here so the user didn't have to immediately go there to check that docstring.

Creates an existing object, then import

2021-05-17 14:02 UTC, simonwo commented on common/tests/factories.py
> +        class SpecialisedFactory(cls):
Actually, there's a far simpler way of doing this so I've just outright deleted this.

2021-05-17 14:04 UTC, simonwo commented on conftest.py
>      """
I have renamed `parent_model` to `previous_version` to reflect this.

2021-05-17 14:46 UTC, andyhd commented on conftest.py
>      Provides a function for checking a model can be imported correctly.
No, that's just the way I wrote it - writing code is often easier than writing comments 😆

2021-05-17 15:29 UTC, andyhd requested changes
I like how much code this removes 👍 I think there might be a logic issue

2021-05-17 15:29 UTC, andyhd commented on conftest.py
> +        if validity:
Should there be an `else:` here? Otherwise, the `valid_between` or `validity_start` kwargs will always be set from `validity[1]`, regardless of `update_type`.

2021-05-17 15:29 UTC, andyhd commented on conftest.py
> +                kwargs["validity_start"] = validity[1].lower
A chunk of similar code here, could be factored out?
```python
def get_validity_kwargs(factory, valid_between):
    kwargs = {}
    if issubclass(factory, factories.ValidityFactoryMixin):
        kwargs["valid_between"] = valid_between
    # don't think we have any factories that subclass both mixins, so don't need elif
    if issubclass(factory, factories.ValidityStartFactoryMixin):
        kwargs["validity_start"] = valid_between.lower
    return kwargs
```
and
```python
if update_type in (...):
    if validity:
        kwargs.update(get_validity_kwargs(factory, validity[0]))
...
if validity:
    kwargs.update(get_validity_kwargs(factory, validity[1]))
```

2021-05-17 17:04 UTC, simonwo commented on conftest.py
> +        dependencies: Dict[str, Union[Any, Type[DjangoModelFactory]]] = None,
Yeah fair enough. I was trying to make clear that something special will happen if you pass in a factory, but I guess this isn't the mechanism for that.

2021-05-17 17:14 UTC, simonwo commented on conftest.py
> +        if validity:
So the logic above line 439 is all about setting up a previous version of the model, which we only need to do if we are running an update or a delete. We still want to set up a current version of the model in all three cases. So `validity[0]` is only ever used for the previous version and `validity[1]` is only ever used for the version to be imported. You're right in that this is a change from the old behaviour, as the CREATE case did not even accept validity ranges at all (and just uses whatever is on the factory). I don't think is necessarily wrong, but it is different and a bit confusing… 

I think perhaps I will spend a bit more time looking at why this logic is even necessary; I think it's only used in 1 place to do with quotas, but to me it doesn't make sense that the previous version and the next version of the model necessarily have to have different date ranges.

2021-05-18 07:52 UTC, simonwo commented on conftest.py
> +        if validity:
So I’ve checked this out. For a start, the tests continue to pass without any specific logic around validity. So no surprises there – it shouldn’t be a requirement to change validity dates when updating or deleting.

This would imply that this logic was only here to prevent some future regression. I can’t find any good reason for what that would be though. If we’re worried about a future bug discarding the content of updates, the sequences and fuzzy choices on the factories should account for that.

So I think we’re justified in removing this validity logic. I’ve factored it as a separate commit so that if we do need to revert then it’ll be easier.

2021-05-18 13:25 UTC, andyhd approved these changes
👍 👍

2021-05-18 13:49 UTC, merged