XML performance refactor: part 1
uktrade/tamato pull request #305
Opened 2021-05-27 14:33 UTC by simonwo

This is the first part of the work (started but not finished in firebreak!) to make better use of the database to generate XML envelope output. I'm trying to get as much stuff out of the way which can be merged early to make the later PR more manageable.

This first set of commits is focused around more accurately representing the XML datamodel in the import parsers. This lets us get rid of some custom logic and provides natural extension points which we will use in a later PR to provide serialisation. On the whole though, not much _behaviour_ has changed here – we are just making the import parsers into more accurate data models.

There is some stuff in here which at first glance seems a bit weird (I'd encourage you to read the commit messages) and that we don't use yet e.g. adding the record and subrecord codes. This all gets used later and I can explain further if the commit messages are not clear enough.

2021-05-27 15:52 UTC, stuaxo commented on importer/parsers.py
> +    less than the specified number of separators occur some values will be `None`.
Maybe specify which values will be None, I'm assuming it's the ones on the end ?

2021-05-27 15:53 UTC, stuaxo commented
Before I start reading this properly - is it worth separating some of the more generic XML parts into their own library, or would that be better done afterwards once this has matured ?

2021-05-27 16:40 UTC, simonwo commented
Yeah, I think it’ll probably be better after, or at least the stuff in the next PR. This is all quite domain specific.

2021-06-02 10:48 UTC, andyhd requested changes
I think there is either a misleading doc comment or some incorrect code in `CompoundElement`. Otherwise, looks great 👍

2021-06-02 10:48 UTC, andyhd commented on importer/parsers.py
> +        super().__init__(tag)
Pylint doesn't like the unused argument. You can suppress the warning in several ways:

```python
# option 1
def __init__(
    self,
    tag: Tag,
    value: str,  # pylint: disable=unused-argument
) -> None:
    ...

# option 2
def __init__(self, tag: Tag, _value: str) -> None:
    ...

# option 3
def __init__(self, tag: Tag, value: str) -> None:
    _ = value
    ...

# option 4
def __init__(self, tag: Tag, **kwargs) -> None:
```

I quite like option 1 because it is very clear what the intention is. But it's just for pylint, so no big deal either way.

2021-06-02 10:48 UTC, andyhd commented on importer/parsers.py
> +        super().__init__(*args)
Is the `format` string meant to be stored?

2021-06-02 10:48 UTC, andyhd commented on importer/parsers.py
> +            self.data = self.native_type([self.text, *(None for _ in self.children)])
If `self.children` has length 3 and `self.text` is `foo|bar`, then `self.data` will be `("foo", "bar")` and not `("foo", "bar", None)`, as described by the doc comment - unless I misunderstood it?

Also, if there are no separators in `self.text` then `self.data` will have length `len(self.children) + 1`, which I think also contradicts the doc comment.

I think this does what the comment says:
```python
parts = self.text.split(self.separator, len(self.children) - 1)
self.data = self.native_type([*parts, *([None] * len(self.children) - len(parts))])
```
Or you could use `itertools` and do something like:
```python
self.data = islice(
    chain(
        self.text.split(self.separator, len(self.children) - 1),
        repeat(None),
    ),
    len(self.children)
)
```

2021-06-02 15:35 UTC, simonwo commented on importer/parsers.py
> +        super().__init__(*args)
I have also marked this as unused. It is used later in the serialization commits but it was just easier to leave it unused and get all the data on the parsers in now.

2021-06-02 15:35 UTC, simonwo commented on importer/parsers.py
> +            self.data = self.native_type([self.text, *(None for _ in self.children)])
You're right, the doc string and the code don't really match. I've added some tests and used your implementation. Thanks!

2021-06-02 15:58 UTC, andyhd approved these changes
🎩

2021-06-02 17:15 UTC, stuaxo commented on importer/parsers.py
> +            self.data = self.native_type([self.text, *(None for _ in self.children)])
Glad you covered this @andyhd I spent a while staring at the part that constructs the data trying to work out if it should work or not.

2021-06-02 17:30 UTC, merged