TP-695 Edit measure geographical area
uktrade/tamato pull request #306
Opened 2021-05-27 17:53 UTC by DIT-CJWaszczuk

## Summary
Adds ability to edit the geographical area of a measure 
## Screenshots 
![image](https://user-images.githubusercontent.com/76431740/119873810-d47ec780-bf1c-11eb-999d-19e244079237.png)

2021-05-27 18:46 UTC, stuaxo commented on geo_areas/models.py
> +    def is_erga_omnes(self):
Would be great to have a short docstring saying what erga_omnes is !

2021-05-27 18:47 UTC, stuaxo commented on measures/forms.py
> +        ].label_from_instance = lambda obj: obj.structure_description
I assume these two are meant to be the same ?

2021-05-27 18:55 UTC, DIT-CJWaszczuk commented on geo_areas/models.py
> +    def is_erga_omnes(self):
I'd rather we just remove the damn phrase all together!

2021-05-27 19:00 UTC, stuaxo commented on measures/forms.py
> +        )[0]
Can the query return multiple objects ?

If it is always one, then `.get(area_code=1, area_id=1011)` may be a better fit than `.filter(....)[0]`.

2021-05-27 19:05 UTC, stuaxo commented on geo_areas/models.py
> +    def is_erga_omnes(self):
Sounds good, I have no idea what it is... yet another cryptic taric thing.

2021-05-28 08:32 UTC, simonwo requested changes
Can't see anything controversial! 😁 Would be good to land a few tweaks though.

Also did we figure out how to write tests for these things yet?

2021-05-28 08:32 UTC, simonwo commented on geo_areas/models.py
> +    def is_erga_omnes(self):
Feel free to use `all_countries` instead.

2021-05-28 08:32 UTC, simonwo commented on geo_areas/models.py
> +        return self.area_code == 0 or self.area_code == 2
The constants in [`geo_areas.validators.AreaCode`](https://github.com/uktrade/tamato/blob/master/geo_areas/validators.py#L10) would help avoid the magic numbers.

2021-05-28 08:32 UTC, simonwo commented on measures/forms.py
> +        )[0]
It's technically possible for this [area code to be reused](https://uktrade.github.io/tamato/docs/business_rules/geo_areas.html#geo_areas.business_rules.GA1) which would result in multiple areas with the area ID 1011, so I would advise adding a call to [`as_at(instance.valid_between.lower)`](https://github.com/uktrade/tamato/blob/master/common/models/records.py#L136) here, and then as Stuart said, calling `get`.

2021-05-28 09:56 UTC, stuaxo commented
> Can't see anything controversial! grin 
Me neither - thought I'd need to reread it as I couldn't see any.

> And I heartily approved of new fields on the model (maybe they could be `@property`?). Would be good to land a few tweaks though.
Had the same thought on property, but wasn't sure I knew the code enough here to write the comment.

> 
> Also did we figure out how to write tests for these things yet?

For the FE ?   Yes, though I need to come back and implement them.

2021-05-28 10:32 UTC, stuaxo commented
@andyhd would this make most sense as part of the QuerySet ?

2021-05-28 11:47 UTC, DIT-CJWaszczuk commented on measures/forms.py
> +        ].label_from_instance = lambda obj: obj.structure_description
yeah i'm concerned of the select populating with an item that shouldn't be in, i.e you previously had turkey as the area, you didn't want Turkey showing in the groups, can probably clean it up

2021-05-28 14:54 UTC, stuaxo commented on measures/forms.py
> +        )[0]
@andyhd would erga_omnes make most sense as part of the QuerySet ?

So this ends up with something like:
GeographicalArea.objects.erga_omnes.latest_approved()

2021-06-08 13:29 UTC, andyhd commented on measures/forms.py
> +            area_code=1,
I wonder about the order of `approved_up_to_transaction` and `filter` - does it matter which way round they go? I haven't looked into the details, but I feel like filtering by `area_code` first will mean the `approved_up_to_transaction` will have fewer rows to operate on and will therefore be quicker? @stuaxo any thoughts?

2021-06-08 13:29 UTC, andyhd approved these changes
Looks good to me 👍

2021-06-08 17:39 UTC, merged