TP-193: Create Measure wizard
uktrade/tamato pull request #308
Opened 2021-06-01 16:38 UTC by andyhd

2021-06-10 10:08 UTC, stuaxo commented on measures/jinja2/measures/create-start.jinja
> +    It is essential to plan your activities in advance of using this measure creation functionality.
Hopefully in future we can have a link here to the tariff manual, or something like a screencast that elaborates on this.

2021-06-10 10:09 UTC, stuaxo approved these changes

2021-07-05 17:46 UTC, simonwo commented
tfw you see minus 11,000 lines and then the relief when it's all in package-lock.json 😂

2021-07-06 08:21 UTC, andyhd commented
Yeah, +3477 -11182 in package-lock.json 🙄 and another +1k for step-by-step-nav css and js, which is just copied from a non-packaged gov.uk source.

2021-07-12 12:09 UTC, stuaxo commented on geo_areas/forms.py
> +        self.fields["geo_group"].queryset = (
^ some commented bits here ^^

2021-07-12 12:09 UTC, stuaxo commented on geo_areas/forms.py
> +        self.fields["geo_area"].queryset = (
^ some commented bits here ^^

2021-07-12 12:10 UTC, stuaxo commented on geo_areas/forms.py
> +        )
^ I guess the distinct is commented here as not sure if it's needed ?

2021-07-12 12:41 UTC, stuaxo commented on regulations/tests/bdd/test_regulations.py
> +    )
Not a blocker - if this does fail, there isn't a clue about what went wrong in the assertion.   It seems a little tricky to come up with a good way of doing this while keeping the test small.

2021-07-12 13:13 UTC, andyhd commented on geo_areas/forms.py
> +        self.fields["geo_group"].queryset = (
Yeah, I had left the geo exclusion stuff for later, but it looks like I need to tackle it now for both create and edit measures.

2021-07-12 13:14 UTC, andyhd commented on geo_areas/forms.py
> +        )
I found it didn't actually make a difference, so left this here as an invitation to tell me what I'm doing wrong :)

2021-07-12 13:15 UTC, andyhd commented on regulations/tests/bdd/test_regulations.py
> +    )
I should make an assertion for each value inside the loop, rather than using `any`

2021-07-12 13:16 UTC, andyhd commented
@stuaxo I'm afraid the comments you left are on code changes in [the other PR TP-703](https://github.com/uktrade/tamato/pull/329) - this PR just builds on top of that one

2021-07-12 13:18 UTC, andyhd commented on regulations/tests/bdd/test_regulations.py
> +    )
@stuaxo I'm afraid this code change is in [the other PR TP-703](https://github.com/uktrade/tamato/pull/329) - this PR builds on top of that one

2021-07-15 12:53 UTC, simonwo approved these changes
Looks good! Some comments about scope of data we return from autocompletes and choices, but won't stop it from working in the immediate term.

Dare I ask about tests? Because I can see a future refactor to e.g. the `MeasureCreationPattern` could break this accidentally…

2021-07-15 12:53 UTC, simonwo commented on measures/views.py
> +                if condition.duty_amount:
Hm, they can sometimes be more complex than just a single amount… how possible would it be to run this field through the DutySentenceParser instead? I appreciate at the moment it only returns MeasureComponents but IIRC it should be reasonably easy to make it return MeasureConditonComponents instead?

2021-07-15 12:53 UTC, simonwo commented on measures/views.py
> +            measure, *_ = list(measure_creation_pattern.create(**measure_data))
Yeah this interface is a bit sucky. I think we can change this to just return the measure (and not as a generator) if that would be better? It was only ever like this so we could get all the models we needed to output for the XML, but we do that in a different way now.

2021-07-15 13:17 UTC, andyhd commented on common/jinja2/components/geographical_area_select/template.jinja
> +{%- endset %}
I will remove these - I'm going to implement exclusions next anyway

2021-07-15 13:22 UTC, andyhd commented on geo_areas/forms.py
> +        queryset=GeographicalArea.objects.all(),
The querysets all depend on the current request, which we only have access to in the view. We pass the request into the form during initialization, but that was a problem for the formsets on the conditions and footnotes forms, so I've resorted to overriding the querysets from outside the form. I don't like it.

2021-08-03 11:35 UTC, stuaxo commented on geo_areas/models.py
> +        return self.filter(area_code=AreaCode.GROUP, area_id=1011)
@simonwo do you have a pointer to what the significance of area_id=1011 is here?
I'll probably add a comment.

2021-08-03 12:06 UTC, simonwo commented on geo_areas/models.py
> +        return self.filter(area_code=AreaCode.GROUP, area_id=1011)
Area ID 1011 is reasonably well defined to be "all countries" aka "erga omnes".

2021-08-04 12:28 UTC, simonwo commented on measures/views.py
> +            measure, *_ = list(measure_creation_pattern.create(**measure_data))
Well it would still need to call all the separate functions, just not `yield from` them. So I think it would be worth keeping the functions just for modularity. But anyway, this is just refactoring so let's not let that get in the way of merging this.

2021-08-04 13:40 UTC, paulpepper-trade requested changes
Labels and help text are repeated on some of the forms.
![image](https://user-images.githubusercontent.com/85895113/128191032-97da49e5-27e2-44cb-90a4-4419efe58d4b.png)

2021-08-04 15:55 UTC, stuaxo approved these changes
> [16:52] stuart.axon (Guest)
    Nice !   And it doesn't effect any of the other screens ?

[16:53] Paul Pepper (Guest)
    The only place that we use the AutoCompleteField is in Create Measures forms, so no further changes necessary.

2021-08-05 08:03 UTC, stuaxo commented on measures/views.py
> +            measure, *_ = list(measure_creation_pattern.create(**measure_data))
Pushed this up - (between Paul and myself we have divided this so I am going from the bottom up and him, the top-down).

2021-08-05 08:05 UTC, stuaxo commented on measures/forms.py
> +        queryset=models.MeasureType.objects.all(),
Does this mean `as_at(measure_start_date)` as above ?

2021-08-05 09:04 UTC, paulpepper-trade commented
> Labels and help text are repeated on some of the forms:
> 
> ![image](https://user-images.githubusercontent.com/85895113/128191032-97da49e5-27e2-44cb-90a4-4419efe58d4b.png)

Fixed.

2021-08-05 09:59 UTC, stuaxo commented on measures/views.py
> +                if condition.duty_amount:
Note: from our conversation earlier that this refactor can be implemented later.

2021-08-05 11:31 UTC, paulpepper-trade commented on geo_areas/forms.py
> +        self.fields["geo_group"].queryset = (
In this first version of create measures it's been decided to delay geographical exclusions. We have a Jira ticket in our backlog to deal with adding the missing features: https://uktrade.atlassian.net/browse/TP-891

2021-08-05 11:31 UTC, paulpepper-trade commented on geo_areas/forms.py
> +        self.fields["geo_area"].queryset = (
In this first version of create measures it's been decided to delay geographical exclusions. We have a Jira ticket in our backlog to deal with adding the missing features: https://uktrade.atlassian.net/browse/TP-891

2021-08-05 11:37 UTC, paulpepper-trade commented on geo_areas/forms.py
> +        )
Commented `.distinct()` now removed: https://github.com/uktrade/tamato/pull/308/commits/2b98bb1eea37bbd12891da3ff37e21efca284bb2

2021-08-05 12:51 UTC, simonwo commented on geo_areas/forms.py
> +        )
Let's create a backlog item for changing this to be `as_at(measure_start_date)`, unless that's trivial now.

2021-08-05 13:41 UTC, paulpepper-trade commented on geo_areas/forms.py
> +        )
Jira ticket created for adding support for "geographic area activation at a future point in time" added, splitting this off from the main create measures requirement: https://uktrade.atlassian.net/browse/TP-893

2021-08-05 13:52 UTC, simonwo commented on measures/forms.py
> +        queryset=models.MeasureType.objects.all(),
Yes, pretty much. But this will probably suffice for an initial deploy.

2021-08-05 14:25 UTC, paulpepper-trade commented on common/jinja2/components/geographical_area_select/template.jinja
> +{%- endset %}
The geographic exclusions requirement has been split out of the Create measures ticket and therefore this PR. See https://uktrade.atlassian.net/browse/TP-891 for the requirement.

2021-08-05 14:34 UTC, paulpepper-trade commented on geo_areas/forms.py
> +        queryset=GeographicalArea.objects.all(),
Similar to previous geographic exclusion, split out on to a new Jira https://uktrade.atlassian.net/browse/TP-891. I've also added a note to that ticket to referencing Simon's remark about filtering with `approved_up_to_transaction()`.

2021-08-05 15:06 UTC, paulpepper-trade commented on measures/forms.py
> +        queryset=models.MeasureType.objects.all(),
It looks as though Andy has scoped down by transaction for all fields that use a queryset within `MeasureCreateWizard.get_form()` https://github.com/uktrade/tamato/blob/8d6a05b8a93e9d2e9dd2b78f2ddbe2ca0078230c/measures/views.py#L226

2021-08-05 15:23 UTC, paulpepper-trade commented on measures/forms.py
> +        queryset=models.MeasureType.objects.all(),
Scoping down available measure types by date within the form may not be possible with the current UI arrangement. If we want to scope down by the measure's start and/or end dates, then they would need entering before the measure type is selected. As it stands, the same form first presents the measure type select then the measure start and end dates.

A couple of possibilities:

- Split the form into two (an extra wizard step) so that the measure start and end dates are collected first. Then present the request for measure type, filtering based upon the dates collected at the previous step.
- Don't filter down the measure type by date, but perform a check date filtered check on measure type when the user completes this step, returning an error message that the measure type is unavailable for the selected measure start and end dates. (It seems likely that this approach would be a bit annoying and potentially mysterious to the user though.)

Any thoughts on this @simonwo and @stuaxo ?

2021-08-05 16:22 UTC, paulpepper-trade commented on measures/views.py
> +                if condition.duty_amount:
Simon's suggestion now split out into a separate Jira ticket: https://uktrade.atlassian.net/browse/TP-897

2021-08-05 17:15 UTC, stuaxo commented on measures/forms.py
> +        queryset=models.MeasureType.objects.all(),
(based conclusions from our chat on teams):

This is a good call, we don't know the valid_between of the measure_type until a user has chosen one from the dropdown.

User experience wise:   I don't think it would be a good experience to have to enter dates before you enter the measure type (though of course I may be wrong here).

We definitely want some validation, the MVP version is probably to implement this when the user hits Continue.

A more useful version would update some information on the validity/invalidity of the dates when the user chooses a measure type with the dropdown.
There are few enough measure types that the info on dates could be embedded into the page, saving the implementation of a new API.

2021-08-05 19:57 UTC, stuaxo commented on geo_areas/forms.py
> +        )
Clarified the comments on these, so someone will know what's up if it breaks in the future.

2021-08-09 13:07 UTC, paulpepper-trade requested changes
The current step number in the page title lags by one (-1) from the correct value displayed in the sidebar.

2021-08-09 13:10 UTC, paulpepper-trade commented
> The current step number in the page title lags by one (-1) from the correct value displayed in the sidebar.

Fixed: https://github.com/uktrade/tamato/pull/308/commits/cbc3dc74ed62229b373be66b7e34e02927de8a77

2021-08-11 16:02 UTC, stuaxo commented on measures/forms.py
> +        queryset=models.MeasureType.objects.all(),
This turned out to be the autocomplete adding entries (it calls an API to get them).

To expedite this I scoped to `as_at(today)` but after this is up will make it call the API with the extra scoping.

2021-08-11 17:30 UTC, stuaxo commented
We definitely want some better test coverage of this once the intial version lands.

2021-08-12 10:19 UTC, simonwo approved these changes
Let's do it.

2021-08-12 10:19 UTC, simonwo commented on commodities/views.py
> +            .as_at(date.today())
As discussed in the other comments, this is not really a final solution because it's possible we are making a measure to start quite a way into the future, so it's still possible to select a commodity that will have expired. However, mostly commodity validity dates are open-ended until right before they're terminated, so this won't actually cause a problem in 99.9% of cases.

But we should revisit this and fix all the places where we've used `.as_at(date.today())` when we should probably be using `.filter(valid_between__contains=TaricDateRange(<measure start date>, <measure end date>)`. I've extended TP-893 to include that.

2021-08-12 10:19 UTC, simonwo commented on geo_areas/models.py
> +    objects = GeographicalAreaQuerySet.as_manager()
Is this right? Normally it's something like `objects = PolymorphicManager.from_queryset(GeographicalAreaQuerySet)()`?

2021-08-12 10:19 UTC, simonwo commented on measures/forms.py
> +        help_text="Select the 10-digit commodity code to which the measure applies.",
I can imagine users asking the question "how do i add measures to a higher level commodity code" – they don't understand that all codes are 10 digit from TAP's perspective. We may need to revisit this content.

2021-08-12 10:30 UTC, paulpepper-trade approved these changes

2021-08-12 10:38 UTC, merged

2021-08-12 10:40 UTC, stuaxo commented on geo_areas/models.py
> +    objects = GeographicalAreaQuerySet.as_manager()
You can do it either way, this way will still have the methods of GeographicalQueryAreaQuerySet available.

Read this *after* hitting merge, so will definitely come back to this.

2021-08-12 10:41 UTC, stuaxo commented on measures/forms.py
> +        help_text="Select the 10-digit commodity code to which the measure applies.",
This can be part of revisiting automcomplete in general.

2021-08-12 10:47 UTC, paulpepper-trade commented on measures/forms.py
> +        help_text="Select the 10-digit commodity code to which the measure applies.",
Jira ticket created to deal with this in a next or future iteration: https://uktrade.atlassian.net/browse/TP-903

2021-08-12 11:17 UTC, stuaxo commented on geo_areas/models.py
> +    objects = GeographicalAreaQuerySet.as_manager()
Looks like there was a reason here: this leaves the .erga_omnes() method available on the created manager, so there is nothing to fix.

2021-08-12 11:35 UTC, paulpepper-trade commented on geo_areas/models.py
> +    objects = GeographicalAreaQuerySet.as_manager()
Stuart and I just did a quick hotfix: https://github.com/uktrade/tamato/pull/355