__str__ don't die if a field has validity_between instead of validity_between
uktrade/tamato pull request #317
Opened 2021-06-10 14:22 UTC by stuaxo

TODO:  Need to add tests for this.

2021-06-10 14:40 UTC, andyhd commented on common/models/mixins/description.py
> +                validity_field,
I'd be tempted to use a ternary condition expression here

2021-06-10 14:51 UTC, simonwo requested changes
Hm, there shouldn’t be any descriptions with a valid_between… so you should be able to just change it without the condition?

Also the ValidityMixin defines a validity_field I think, so maybe you can use `self.validity_field’?

2021-06-10 16:50 UTC, stuaxo commented
> Hm, there shouldn’t be any descriptions with a valid_between… so you should be able to just change it without the condition?
> 
I'll check if this works, I was hoping for a reply like this as maybe it was something that got missed in the refactor ?

> Also the ValidityMixin defines a validity_field I think, so maybe you can use `self.validity_field’?
Will give this a try too...

2021-06-10 17:42 UTC, simonwo commented
> I'll check if this works, I was hoping for a reply like this as maybe it was something that got missed in the refactor ?

Yeah, I think it just got missed.

> TODO: need to add tests for this.

Perhaps you could implement [this test](https://teams.microsoft.com/l/message/19:80f6ef27ef454a87a8c4844d3aa5b3f7@thread.tacv2/1622129986648?groupId=7dec05eb-83aa-4ca6-8bff-bf9b86f579e7)?

2021-06-11 08:59 UTC, stuaxo commented
> > I'll check if this works, I was hoping for a reply like this as maybe it was something that got missed in the refactor ?
> 
> Yeah, I think it just got missed.
> 
> > TODO: need to add tests for this.
> 
> Perhaps you could implement [this test](https://teams.microsoft.com/l/message/19:80f6ef27ef454a87a8c4844d3aa5b3f7@thread.tacv2/1622129986648?groupId=7dec05eb-83aa-4ca6-8bff-bf9b86f579e7)?

That's the one, this ticket is basically adding some code you already wrote and picking your brain !

Managed to get away without it up to now as I had the enclosed patch running locally but needed to come back and do it properly once it came to getting Kristof on an up to date codebase.

2021-06-16 07:08 UTC, simonwo approved these changes

2021-06-16 09:20 UTC, andyhd approved these changes
Nice test!

2021-06-16 09:57 UTC, stuaxo commented
> Nice test!

It should be... Simon wrote the initial version in a teams a conversation... I just tweaked it. 
As usual with code from @simonwo I had to go and learn how some part of it worked (I hadn't used `ids=` in pytest)

2021-06-16 10:15 UTC, merged