TP-92 Create a new foonote
uktrade/tamato pull request #324
Opened 2021-06-22 08:56 UTC by DIT-CJWaszczuk

## Summary 
Allow the user to create footnotes

2021-06-22 09:25 UTC, simonwo reviewed
To answer your question in standup @DIT-CJWaszczuk, the problem with items not appearing anywhere is probably that all our views use `latest_approved` which will ignore draft data in workbaskets. We'll need to change them to use `approved_up_to_transaction(…)`.

2021-06-22 09:25 UTC, simonwo commented on footnotes/models.py
> +            self.footnote_id = new_id
Hm, I think this should actually be done on form load and we should give the user the option to override it. The IDs are public-facing, and whilst they don't normally have any meaning, I can think of a few instances where we might want to specifically pick a certain ID. E.g. if we have a certificate C123 we might want to pick FT123 to match.

2021-06-22 10:01 UTC, DIT-CJWaszczuk commented
Yeah I thought it would be more so to do with `get_descriptions()` not picking up the draft descriptions currently

2021-06-22 13:48 UTC, DIT-CJWaszczuk commented on footnotes/models.py
> +            self.footnote_id = new_id
I'm not quite sure how we would do this, given that we don't know the type beforehand, and given we generate the id  based on the last of each type, we wouldn't be able to generate it correctly on one page.

2021-06-24 11:44 UTC, andyhd requested changes
Looks good, just a typo needs fixing and the auto id increment needs moving. Plus some tidying up if you like.

2021-06-24 11:44 UTC, andyhd commented on common/jinja2/common/confirm_create.jinja
> +      }) }}
This template is essentially the same as `common/confirm_update.jinja`, so they should both extend from the same base template. Move the common code into `layouts/confirm.jinja` and add a new block (maybe `{% block panel %}{% endblock %}`) to override the panel message.

Then `confirm_create.jinja` would look something like
```jinja
{% extends "layouts/confirm.jinja" %}

{% set page_title = "Create a new " ~ object._meta.verbose_name %}

{% block beforeContent %}
  ...
{% endblock %}

{% block panel %}
  {{ govukPanel({
    "titleText": ... ~ " has been created",
    ...
  }) }}
{% endblock %}
```

2021-06-24 11:44 UTC, andyhd commented on common/jinja2/common/confirm_create.jinja
> +      {"text": page_title}
I think there's a missing breadcrumb link here - shouldn't there be a `{"text": "Find and edit " ~ object._meta.verbose_name_plural, "href": object.get_url("list")},` link?

2021-06-24 11:44 UTC, andyhd commented on common/jinja2/components/description_help.jinja
> +      {"html": "This is " ~ "<a href=:\'https://www.gov.uk\'>a hyperlink to gov.uk</a>"|e ~ "<br> becomes <br> <a href=:'https://www.gov.uk'>a hyperlink to gov.uk</a>"},
There seem to be extraneous `:`s in here - `<a href=:` should be `<a href=`

2021-06-24 11:44 UTC, andyhd commented on footnotes/forms.py
> +            Field.textarea("description", label_size=Size.SMALL, rows=5),
If you do `self.helper.label_size = Size.SMALL` and `self.helper.legend_size = Size.SMALL`, you can reduce this to
```python
self.helper.layout = Layout(
    "footnote_type",
    "start_date",
    Field.textarea("description", rows=5),
    ...
```

2021-06-24 11:44 UTC, andyhd commented on footnotes/jinja2/footnotes/create.jinja
> +        "html": description_html
There is a [`HTML.details` layout object in crispy-forms-gds](https://crispy-forms-gds.readthedocs.io/en/latest/components/details.html), which could remove the need for this template.

2021-06-24 11:44 UTC, andyhd commented on footnotes/models.py
> +            )
This should go in the form save method, because that's the only place where trying to save with an empty footnote_id should happen without an error being raised.

2021-06-24 11:44 UTC, andyhd commented on footnotes/views.py
> +        self.object.save()
This should be:
```python
form.instance.update_type = UpdateType.CREATE
with transaction:
    form.save()
```

2021-06-24 11:44 UTC, andyhd commented on footnotes/views.py
> +        self.object_description.save()
And you can put this into the same `with transaction:` block, eg:
```python
with transaction:
    self.object = form.save()

    description = form.cleaned_data["footnote_description"]
    description.described_footnote = self.object
    description.update_type = UpdateType.CREATE
    description.save()
```
I don't see any need to add the description object to the view as an attribute `self.object_description` - is there one?

2021-06-28 12:57 UTC, DIT-CJWaszczuk commented on footnotes/jinja2/footnotes/create.jinja
> +        "html": description_html
I want to do this, but the content of that details is fairly complex, and i'm not sure the method will handle it properly. 
![image](https://user-images.githubusercontent.com/76431740/123640194-d4723000-d818-11eb-9e51-90c2d86c8d8b.png)

2021-06-28 14:34 UTC, andyhd commented on footnotes/models.py
> +            )
Ah, yeah, that would be better in a template

2021-06-28 14:35 UTC, andyhd commented on footnotes/jinja2/footnotes/create.jinja
> +        "html": description_html
Ah yeah, that is better off in a template

2021-06-28 14:47 UTC, DIT-CJWaszczuk commented on common/jinja2/common/confirm_create.jinja
> +      {"text": page_title}
Going off the design, this breadcrumb has been removed for 'creates'

2021-06-29 13:42 UTC, stuaxo commented on footnotes/models.py
> +            self.footnote_id = new_id
Tangent:  I've been thinking about ids, and their generation in the database.

The basic idea, is that one of the identifying keys is labelled as the "sequential key" and this is incremented, while all the other keys are not.

While this could be done for character based keys, for now it's just implemented for integers to keep things simple.

The code above shows some of the complications, other interesting ones are that we have fields with the same name, but different types (worked around in the first version by just checking integers).

2021-06-29 13:42 UTC, stuaxo approved these changes

2021-06-29 15:26 UTC, DIT-CJWaszczuk commented on common/jinja2/components/description_help.jinja
> +      {"text": "Make a piece of content underlined"},
This is what happens when we don't have a dedicated content designer!

2021-06-29 15:43 UTC, merged