TP-92 Create Additional Codes
uktrade/tamato pull request #328
Opened 2021-06-29 18:41 UTC by DIT-CJWaszczuk

2021-06-30 13:11 UTC, simonwo submitted a review, later dismissed
Sorry, but the user does need to be able to manually select the additional code ID (not SID) in this case, because these numbers are decided in advance and also put into CHIEF.

2021-07-12 17:31 UTC, paulpepper-trade requested changes

2021-07-12 17:32 UTC, paulpepper-trade commented on additional_codes/forms.py
> +            .aggregate(Max("sid"))["sid__max"]
Fixed.

2021-07-12 17:32 UTC, paulpepper-trade commented on additional_codes/urls.py
> +        "create",
Done.

2021-07-12 17:32 UTC, paulpepper-trade commented on additional_codes/urls.py
> +        f"{detail}/confirm-create",
Done.

2021-07-13 09:15 UTC, paulpepper-trade approved these changes

2021-07-13 16:47 UTC, stuaxo approved these changes

2021-07-13 17:02 UTC, merged

2021-07-14 10:30 UTC, andyhd reviewed
Sorry for the posthumous review - everything looks good! Just a few suggestions for tidying/DRYing up.

2021-07-14 10:30 UTC, andyhd commented on additional_codes/forms.py
> +        return instance
`ModelForm.save` normally calls `self._save_m2m` after `instance.save` and even though `AdditionalCode` doesn't have any many-to-many fields to worry about, omitting it might lead to mistakes when building new create forms from this example.
If you `return super().save(commit=commit)` here instead of calling it at the top of the method, then we don't have to worry about how it works under the hood.

2021-07-14 10:30 UTC, andyhd commented on additional_codes/forms.py
> +        fields = ("type", "valid_between")
Is this missing `code` and `description`?

2021-07-14 10:30 UTC, andyhd commented on additional_codes/views.py
> +        transaction.save()
This is redundant

2021-07-14 10:30 UTC, andyhd commented on additional_codes/views.py
> +        self.object.save()
This should be moved into `DraftCreateView` since it will be the same for all create views. Although calling `form.save(commit=False)` will not save any many-to-many relations, so we need to call `self.object.save_m2m()` afterwards.

I would be tempted to have a `form_valid` method in `DraftCreateView` like this:
```python
class DraftCreateView(...):
    ...
    def form_valid(self, form):
        with WorkBasket.new_transaction():
            # move setting of update_type to form.save()
            self.object = form.save()

            self.save_dependents(form)

        return HttpResponseRedirect(self.get_success_url())

    def save_dependents(self, form):
        """Hook to save any dependent models"""
```
and then `AdditionalCodeCreate.save_dependents` could look like this:
```python
    def save_dependents(self, form):
        # no need to save object description as an attribute of `self`
        desc = form.cleaned_data["additional_code_description"]
        desc.described_additionalcode = self.object
        desc.update_type = UpdateType.CREATE
        desc.save()
```

2021-07-14 10:30 UTC, andyhd commented on additional_codes/views.py
> +        return kwargs
This could also be moved up into `DraftCreateView`, or maybe a separate mixin class, since it is needed by nearly all create and edit forms.

2021-07-14 10:46 UTC, paulpepper-trade commented
> Sorry for the posthumous review - everything looks good! Just a few suggestions for tidying/DRYing up.

Thanks Andy. All good suggestions. I'll apply these on a new PR.

2021-07-19 17:01 UTC, paulpepper-trade commented on additional_codes/forms.py
> +        instance = super(AdditionalCodeCreateForm, self).save(commit=False)
New PR: https://github.com/uktrade/tamato/pull/340/files

Yep, Python3 style `super()` now applied .

I still think that `super().save(commit=False)` should be called, however. `django.forms.models.BaseModelForm.save()` performs validation checking against `self.errors` and may add other behaviour in future versions that we'd wish to pull into our `save()` method (by calling the base class `save()`).

2021-07-19 17:06 UTC, paulpepper-trade commented on additional_codes/forms.py
> +            tx = workbasket.transactions.order_by("order").last()
Done.

See https://github.com/uktrade/tamato/pull/340/commits/7ae605c7fc29a891400ad2c4e6f6750fb7eff79f

2021-07-19 17:31 UTC, andyhd commented on additional_codes/forms.py
> +        instance = super(AdditionalCodeCreateForm, self).save(commit=False)
That was my point in the next comment- by calling `super().save(commit=False)` at the top and `instance.save()` at the end, we are making an assumption about how `super().save()` is implemented.