Tp 774 - Create regulations (frontend)
uktrade/tamato pull request #335
Opened 2021-07-14 17:38 UTC by paulpepper-trade

This PR adds a Create regulations frontend capability - https://uktrade.atlassian.net/browse/TP-774.

2021-07-15 11:16 UTC, andyhd requested changes
Good stuff, just a couple of issues with where things go and (as usual) some suggestions for tidying up.
Also, you'll need to squash these commits before merging.

2021-07-15 11:16 UTC, andyhd commented on regulations/templates/regulations/help_public_identifiers.html
> +<div class="govuk-!-margin-top-3">
This template should be in `regulations/jinja2/regulations/help_public_identifiers.jinja`. Then you can use the GOV.UK Frontend table component.

2021-07-15 11:16 UTC, andyhd commented on regulations/templates/regulations/help_regulation_group.html
> +<p>The regulation group is used to control what types of measure are allowed to be linked to this regulation. They
Please keep all the templates together in `regulations/jinja2`

2021-07-15 11:16 UTC, andyhd commented on regulations/views.py
> +        # CreateView.get_success_url() override relies upon a valid self.object.
This comment seems out of place

2021-07-15 11:16 UTC, andyhd commented on regulations/views.py
> +        # class generating URLs for the main views.
Not sure this comment is necessary

2021-07-15 11:23 UTC, andyhd commented on regulations/forms.py
> +        help_text=Regulation._meta.get_field("regulation_group").help_text
This field should be a `forms.ModelChoiceField`, I think.

2021-07-15 12:58 UTC, simonwo commented on regulations/forms.py
> +        ),
Agreed it won't ever need to be empty. The default should be "approved". Also it's a Boolean – so should the values be True and False? Also also, "0" should be "not approved" and "1" should be approved. Also also also, there is some validation logic here – "not approved" can only be selected if the regulation usage is "C" – draft.

2021-07-15 13:05 UTC, simonwo commented on regulations/templates/regulations/help_regulation_group.html
> +<p>- Non-preferential quota measures (types 122 or 123) must be linked to the regulation group KON (and they are
If we're doing HTML, can we turn these into proper bullets using `<ul>` etc?

2021-07-15 13:05 UTC, simonwo commented on regulations/validators.py
> +    AGRI_MEASURES = "A", "A: Agri measures"
Could we use this above to define the regex? E.g. `UK_ID = fr"[{u[0] for u in RegulationUsage.values}]\d{2}\d{4}[0-9A-Z]"` or something?

2021-07-15 14:32 UTC, paulpepper-trade commented on regulations/forms.py
> +FIXED_ROLE_TYPE = 1
Done.

2021-07-15 14:32 UTC, paulpepper-trade commented on regulations/forms.py
> +            #   field.".
Done.

2021-07-15 14:33 UTC, paulpepper-trade commented on regulations/forms.py
> +        choices=[("", "")] + RegulationUsage.choices
I was trying to apply the design to the nearest pixel :-)
Done now using "Select a regulation usage" in line with other form choice fields in Tamato.

2021-07-15 14:34 UTC, paulpepper-trade commented on regulations/forms.py
> +        help_text=Regulation._meta.get_field("regulation_group").help_text
Makes sense to move the help text into the form field.
Part of the reason for cooking up a list of choices using the `ChoiceField` was to get human-readable items in the drop-down. I've added a `Group.__str__()` method to do that now as part of resolving this.

2021-07-15 14:34 UTC, paulpepper-trade commented on regulations/forms.py
> +        max_length=4,
I think I ran into a couple of styling issues when I tried using an `IntegerField` - for instance setting `type="int"` on the form field and `field_width=Fixed.FIVE` on the crispy form layout element caused some problems.
I'll take another look at `forms.IntegerField`.

2021-07-15 14:37 UTC, paulpepper-trade commented on regulations/models.py
> +            "of the legislative text."
Done.

2021-07-15 14:38 UTC, paulpepper-trade commented on regulations/views.py
> +        # CreateView.get_success_url() override relies upon a valid self.object.
Done - removed.

2021-07-15 14:38 UTC, paulpepper-trade commented on regulations/views.py
> +        # class generating URLs for the main views.
Done - removed.

2021-07-15 15:35 UTC, andyhd commented on regulations/forms.py
> +        help_text=Regulation._meta.get_field("regulation_group").help_text
You can override `label_from_instance` like we do [in AdditionalCodeForm](https://github.com/uktrade/tamato/blob/1b2e4ac10c42468ee0229ac23572e77f50be7d67/additional_codes/forms.py#L30) for this purpose. I don't think there's anything particularly wrong with using `__str__` for this, though, especially as the base `TrackedModel.__str__` implementation is really only for debug output.

2021-07-15 15:42 UTC, andyhd commented on regulations/forms.py
> +        max_length=4,
You could possibly override the type in the layout where you do `Field.text("sequence_number", type="text", ...)`. But it's just a suggestion, what you have here already works.

2021-07-15 15:44 UTC, andyhd commented on regulations/forms.py
> +        ),
The validation logic won't apply here, because this is a create form.

2021-07-15 16:57 UTC, paulpepper-trade commented on regulations/forms.py
> +        max_length=4,
Yeah, I already had a tussle with that approach. This is what you get:
![image](https://user-images.githubusercontent.com/85895113/125827209-707d2eb3-2242-4b7a-8190-3ebe0282839e.png)
I expect with a bit of CSS fiddling it might be fixable, but as you say, what's there currently works :)

2021-07-15 17:13 UTC, paulpepper-trade commented on regulations/forms.py
> +        validators=[URLValidator],
Same reason as for `sequence_number`. Delving a bit further into what's going on, it looks as though crispy-forms-gds doesn't apply the `govuk-input` class to the widget. A localised fix:

        self.fields["url"].widget.attrs.update({"class": "govuk-input"})

Really this needs fixing in the package. I can see that we have fixes in our code base for other crispy-forms-gds issues.

2021-07-15 17:40 UTC, paulpepper-trade commented on regulations/forms.py
> +        max_length=4,
Okay, I've now done a similar thing here for the `sequence_number` form field as for the `url` form field - use the appropriate type of form field and apply the corrected CSS in widget override.

2021-07-16 13:21 UTC, paulpepper-trade commented on regulations/forms.py
> +        max_length=4,
Fixed in the same manner as for the url attribute.

2021-07-16 13:34 UTC, paulpepper-trade commented on regulations/forms.py
> +        ),
After some faff with custom choices in `regulations.validators` I've ended up using a django `TypedChoiceField` in the form, coercing the 'True' and 'False' values returned in the form's POST to bools.
Also fixed the incorrectly assigned bools to their "Approved" (`True`) and "Not approved" (`False`) representations on the form.

2021-07-16 13:37 UTC, paulpepper-trade commented on regulations/forms.py
> +        ),
I think i understand Simon's remark about validation logic, but don't understand Andy's remark about it not being applicable here (since this is a create form).  @andyhd: could you explain why, please.

2021-07-16 13:47 UTC, andyhd commented on regulations/forms.py
> +        ),
Ah, I misread Simon's comment - yeah, a "C" regulation is a draft regulation and cannot be approved.

I was thinking of the validation around changing from approved to unapproved.

2021-07-16 13:58 UTC, paulpepper-trade commented on regulations/forms.py
> +        sequence_number = "{:0>4}".format(cleaned_data["sequence_number"])
Done.

2021-07-16 13:58 UTC, paulpepper-trade commented on regulations/forms.py
> +                sequence_number=sequence_number,
Done.

2021-07-16 14:07 UTC, andyhd commented on regulations/forms.py
> +        )
Not suggesting that you should do this now, but looking at this code and the validator regex which does the reverse (parsing the regulation ID into parts), perhaps it would be worth encapsulating this in a class. Something like
```python
class RegulationId:
    def __init__(self, value: str) -> None:
        """Parse regulation ID string into object"""

    def __str__(self) -> str:
        """Concatenate object attributes"""

    def validate(self, value: str) -> bool:
        """Check `value` is a regulation ID string"""

    def increment_part(self) -> None:
        """Increment the base 36 part value"""
```

2021-07-16 14:10 UTC, paulpepper-trade commented on regulations/forms.py
> +            highest_part_value = basket_regulations[0].regulation_id[-1]
Applied suggestion to use `.first`.
`last_regulation_part` doesn't seem to fit what the value contains so I've gone with `last_matching_regulation`.

2021-07-16 14:35 UTC, andyhd commented on regulations/forms.py
> +            {"class": "govuk-input govuk-input--width-5"}
I think you can override widget attributes more cleanly (as in, without breaking encapsulation) with crispy forms, eg
`Field("url", css_class="govuk-input")`

2021-07-16 16:40 UTC, paulpepper-trade commented on regulations/forms.py
> +        )
`regulation_id` validation and addition to `self.cleaned_data` now implemented inside the form's `clean()` method.
Also added form-level `ValidationError` when the max number of parts has been exceeded on a regulation.
I'll leave your second suggestion for another time, Andy.

2021-07-16 16:42 UTC, paulpepper-trade commented on regulations/forms.py
> +            return alphanum[alphanum.index(highest_part_value) + 1]
Nice use of base36 casting to int - applied.
Also mentioned against another comment, I've raised a form-level `ValidationError` when the max number of parts has been exceeded on a regulation.

2021-07-16 17:11 UTC, paulpepper-trade commented on regulations/forms.py
> +        ),
As per Simon's point, I've added validation logic to enforce the condition that only draft regulations may have a non-approved status.

2021-07-16 17:28 UTC, paulpepper-trade commented on regulations/forms.py
> +            {"class": "govuk-input govuk-input--width-5"}
Done.

2021-07-19 08:47 UTC, paulpepper-trade commented on regulations/forms.py
> +        sequence_number = "{:0>4}".format(cleaned_data["sequence_number"])
> Also are you running the pre-commit hooks?

I haven't forgotten this remark, Simon. I'll be coming back to it.

2021-07-19 10:14 UTC, paulpepper-trade commented on regulations/templates/regulations/help_regulation_group.html
> +<p>The regulation group is used to control what types of measure are allowed to be linked to this regulation. They
Done.
If we're not using Django's default `templates/` directory under the apps directories, then perhaps `APP_DIRS` under the `DjangoTemplates` engine should be `False`?
https://github.com/uktrade/tamato/blob/TP-774/settings/common.py#L138

2021-07-19 10:21 UTC, paulpepper-trade commented on regulations/templates/regulations/help_regulation_group.html
> +<p>- Non-preferential quota measures (types 122 or 123) must be linked to the regulation group KON (and they are
I was absolutely following the UI design. Applied Simon's suggestion to use real `<ul>` bullets now.

2021-07-19 10:39 UTC, paulpepper-trade commented on regulations/templates/regulations/help_public_identifiers.html
> +<div class="govuk-!-margin-top-3">
Moved the template now.

Using `crispy_forms_gds.layout.content.HTML.table()` and combining it with `crispy_forms_gds.layout.content.HTML.details()` was something that I had implemented initially to deal with this bit of help text (I think we may have spoken about it, Andy). It was messy, verbose and not as clear in my view as just popping the table details in the HTML template / partial as has been done here.

2021-07-19 10:40 UTC, paulpepper-trade commented on regulations/forms.py
> +                ),
Unless you have a strong view on this, Andy, I leave this as it is. It's a bit half a dozen of one...

2021-07-19 10:55 UTC, andyhd commented on regulations/templates/regulations/help_regulation_group.html
> +<p>The regulation group is used to control what types of measure are allowed to be linked to this regulation. They
`{app_name}/jinja2` is Django’s default for Jinja templates. Django’s own template engine does not work with the GOV.UK Frontend Nunjucks templates.

2021-07-19 14:01 UTC, paulpepper-trade reviewed
@simonwo re. your suggestion for using `RegulationUsage` to generate UK_ID prefixes (https://github.com/uktrade/tamato/pull/335#discussion_r670441792) - how about:

```
UK_ID_PREFIXES = "".join([ru for ru in RegulationUsage.values if ru is not None])
UK_ID = fr"[{UK_ID_PREFIXES}]" + r"\d{2}\d{4}[0-9A-Z]"
```

A fair bit of escaping would be necessary to pull the prefix generation into the main expression, hence why I've separately created `UK_ID_PREFIXES` above.

2021-07-19 14:49 UTC, paulpepper-trade commented on regulations/validators.py
> +    AGRI_MEASURES = "A", "A: Agri measures"
Done.
Now applied as per https://github.com/uktrade/tamato/pull/335#pullrequestreview-709444125.

2021-07-19 14:56 UTC, simonwo commented
> 
> 
> @simonwo re. your suggestion for using `RegulationUsage` to generate UK_ID prefixes ([#335 (comment)](https://github.com/uktrade/tamato/pull/335#discussion_r670441792)) - how about:
> 
> ```
> UK_ID_PREFIXES = "".join([ru for ru in RegulationUsage.values if ru is not None])
> UK_ID = fr"[{UK_ID_PREFIXES}]" + r"\d{2}\d{4}[0-9A-Z]"
> ```
> 
> A fair bit of escaping would be necessary to pull the prefix generation into the main expression, hence why I've separately created `UK_ID_PREFIXES` above.

Works for me!

2021-07-21 09:57 UTC, simonwo approved these changes

2021-07-21 09:57 UTC, simonwo commented on regulations/forms.py
> +    )
Would it accept negative numbers? I.e. does it need a min value?

2021-07-21 10:09 UTC, paulpepper-trade commented on regulations/forms.py
> +    )
A previous incarnation of this field enforced positive values, yes. I've now applied a `min_value`. Reading of https://www.legislation.gov.uk/understanding-legislation#citationandnumbering it isn't clear what a minimum value should be so I've used a value of one (1). Does that seem reasonable?

2021-07-21 10:51 UTC, merged