Method that can copy a model
uktrade/tamato pull request #336
Opened 2021-07-15 11:42 UTC by simonwo

Producing a copy of a model is a common operation in data work. E.g. it's common to create a new quota definition for a year by copying the definition of the previous year and adding a new validity range. It's also common to copy a measure and change e.g. the commodity code, to replicate one set of preferences to another place.

When copying a measure, it's not enough to just produce a single record – the components and conditions have to be replicated as well. This `copy` method makes doing that easy - it will find any models within the same TARIC record that would need to duplicated and creates all of the new data automatically, applying any specified overrides.

This is useful enough to warrant sharing between people doing data migration and may also prove useful in the user interface at some point.

2021-07-22 11:00 UTC, paulpepper-trade requested changes
Looks pretty good.

Are there any graph cycle concerns you had when designing and implementing this, Simon? Or is it as straightforward as: the source model instance manages cycles and therefore the destination instance inherits this characteristic. (Btw, I haven't so far identifed any specific cycle issues.) Perhaps it would be useful to add a note to the `copy` method about that type of correctness or caveats, if any apply.

2021-07-22 11:19 UTC, simonwo commented on common/models/records.py
> +        this model and any dependent models. If ``copy`` is to be called in a
Good point, yes – two threads doing this at once might try and allocate the same SIDs (which won't crash, but would be wrong). Really the user needs to call `get_sid_counters` and all of their `copy` calls in a write-blocking atomic transaction. Not sure if that is just something that can be fixed with documentation? Putting `@atomic` on `copy` wouldn't be enough.

2021-07-22 11:20 UTC, simonwo commented on common/models/records.py
> +        Returns a set of relations to this model's subrecords.
No, subrecords in a "TARIC" sense. I.e. e.g. a Measure and a MeasureComponent are in the same "logical record" but are different data models because they are many-to-one. I will clarify the comment.

2021-07-22 11:22 UTC, simonwo commented
No real graph concerns – the only data model that can introduce cycles is the `parent` field on the `GeographicalArea`, and there's a business rule that prevents that from happening (and also, the parent geo area won't be included in the copy because it specifically removes self). All the others have a finite depth. So yes, I'm pretty confident that doing a copy on any model won't balloon out or infinitely recurse.

2021-07-22 12:53 UTC, paulpepper-trade commented on common/models/records.py
> +        this model and any dependent models. If ``copy`` is to be called in a
I suppose you're thinking about the types of data update that you do when referring to multi-thread race issues? Wouldn't the same race conditions apply in a multi-process environment too? I'm thinking about, say, more than one user performing updates through the web client, or a web-based update while one of our team is applying a data update. I don't think documentation would fix that.

Perhaps the race window is diminishingly small, and chances of encountering that scenario perhaps smaller still. I'm not sure. But, thinking about scenarios where that race is more likely, it could include, say, several tariff managers blitzing the system with policy updates at the same time.

If wrapping `copy` with `@atomic` won't work then could the work of generating SIDs be centrally managed for each pool (per model) of SIDs? I probably don't know enough about how SIDs are used...

2021-07-23 07:32 UTC, simonwo commented on common/models/records.py
> +        this model and any dependent models. If ``copy`` is to be called in a
So yeah, the main issue is that if two people use `get_sid_counters` at about the same time, they will allocate measures with the same SIDs (and the database won't stop them, because we can't use UNIQUE constraints). The issue is that once the counters dictionary has been returned there is nothing to stop another instance from using it.

One option would be to do a table lock and ensure that all copies are done in one transaction with the lock. When I meant documentation, I basically meant whoever implements that in the UI will have to know to do that.

But you've got me thinking, and another solution is this:

```
from sql_util.utils import SubqueryMax
m = Measure()
m.sid = SubqueryMax("sid")  + Value(1)
m.save()
```

Django allows model fields to be database expressions which then get converted into SQL and passed directly to Postgres. This essentially embeds `SELECT MAX(sid) + 1 FROM measures` into the `INSERT` statement. It's really fast because "sid" is indexed, and gets executed along with the query so I think that means Postgres knows how to lock everything appropriately. That would mean we could delete `sid_counters` as a concept completely and just have this executed in the DB.

What do you think?

2021-07-23 12:39 UTC, paulpepper-trade commented on common/models/records.py
> +        this model and any dependent models. If ``copy`` is to be called in a
Yes, looks good, though I know you've tweaked this slightly from our backchannel chat.

2021-07-27 08:35 UTC, stuaxo commented on common/models/records.py
> +        this model and any dependent models. If ``copy`` is to be called in a
+1 on this, the per-threadness, along with the fact it's hard to reset the current counter (a Counter, wrapped in a lambda), makes this hard to control in unit tests [1].

[1] running with a pytest-random-order will cause these to fail from time to time and similarly for pytest-xdist.

2021-07-27 08:38 UTC, stuaxo commented on common/models/records.py
> +        Returns a set of relations to this model's subrecords.
^ Probably worth amending the docstring to mention this.

2021-07-28 16:22 UTC, simonwo reviewed
@paulpepper-trade @stuaxo

2021-07-28 16:22 UTC, simonwo commented on common/fields.py
> +    )
I've added a default value for SIDs to be an SQL expression; it will get executed at the moment the `INSERT` query is executed. E.g. it'll end up as something like 

```sql
INSERT INTO measures_measure (sid, …) VALUES ((SELECT MAX(sid) + 1 FROM measures_measure), …);
```

This doesn't completely solve the race condition as I think this can still result in duplication if executed truly concurrently? The answer is that we should be using either serialisable transactions for writes or using locks… I don't think either is really sensible to set generally at a low level – we will have to take care when writing code that commits to the database to ensure we've used either method appropriately.

2021-07-28 16:22 UTC, simonwo commented on common/util.py
> +def lock(*models: type[Model], mode: LockMode = LockMode.ACCESS_EXCLUSIVE):
I have also updated the way we handle locks, because the old way lulled you into a false sense of security about when the lock gets released if nested inside another transaction.

2021-07-30 12:59 UTC, paulpepper-trade commented on measures/models.py
> +        it's to a model we don't have in our schema."""
I'm unclear what this means. I suspect that qualifying which type of "schema" would help clearify?

2021-07-30 13:01 UTC, paulpepper-trade approved these changes
LGTM

2021-07-30 14:55 UTC, merged