Tp 803 - Commodity Tree Change Handler
uktrade/tamato pull request #371
Opened 2021-09-02 09:37 UTC by kintisheff

This ticket is part of the [HS22 Epic](https://uktrade.atlassian.net/browse/TP-911?atlOrigin=eyJpIjoiODE4ZmQ5ZjhmY2FiNGQxOTg0ZDZlMzQ1NzMxMGYwNjMiLCJwIjoiaiJ9).

A previous ticket implemented a selective xml commodity importer.
This ticket is responsible for evaluating any side effects of pending changes to the commodity tree, and providing remedies
A subsequent feature (see TP-931) will provide functionality to implement the sum of commodity changes and remedies

Notes:
- Please read the docs included in `commodities/__init__.py` before you start your review in order to understand the context of the significant changes to commodity tree change handler logic introduced with this ticket
- Please consider reviewing the 60 or so new tests included in `commodities/tests` as a key part of your review - esp. the scenario tests, which reflect ADR13; before reviewing the tests, please read the module-level docs on fixtures in `commodities/tests/conftest.py`

2021-09-02 15:43 UTC, stuaxo commented on conftest.py
> +        raise AssertionError(f"Raised exception {error} when it should not!")
I wonder if raise `AssertionError(f"Raised exception {error} when it should not!") from error` would be good here, to perserve the stacktrace?

Same with the next exception.

2021-09-02 16:07 UTC, simonwo commented on conftest.py
> +        raise AssertionError(f"Raised exception {error} when it should not!")
I'm not sure I understand the point of `not_raises`… surely a raised exception will simply bubble up and fail the test? And why declare the `ExpectedException` specifically if we then also raise an assertion on any `Exception` below?

2021-09-02 16:13 UTC, kintisheff commented on conftest.py
> +        raise AssertionError(f"Raised exception {error} when it should not!")
the only motivation is code readability

2021-09-06 14:45 UTC, rachaelcodes commented on commodities/__init__.py
> +    resulting form the changes made to the commodity tree
Should this be 'resulting from'?

2021-09-06 14:49 UTC, rachaelcodes commented on commodities/__init__.py
> +    -- a calendar clock (what goods where in effect as of date x)
'what goods were in effect'?

2021-09-06 14:57 UTC, rachaelcodes commented on commodities/migrations/0009_auto_20210902_1002.py
> +# Generated by Django 3.1.12 on 2021-09-02 10:02
Are we naming our migrations files now? It looks like a lot of the recent ones have been named.

2021-09-07 16:33 UTC, andyhd reviewed
There's a lot here - I'm still reviewing, but I thought I'd submit some of my feedback so far

2021-09-07 16:33 UTC, andyhd commented on commodities/models/dc.py
> +        return code + "0" * (10 - len(code))
`return f"{code:0<10}"`

2021-09-07 16:33 UTC, andyhd commented on commodities/models/dc.py
> +from typing import Tuple
If you `from __future__ import annotations`, I think you can use `dict[]`, `list[]`, and `tuple[]` instead of these soon-to-be-deprecated types from `typing`

2021-09-07 16:33 UTC, andyhd commented on commodities/models/dc.py
> +    indent: int = None
Must be `Optional[int]` if the default value is `None` - `None` is not an `int`.

2021-09-07 16:33 UTC, andyhd commented on commodities/models/dc.py
> +        version_group_id: int = None,
These all need to be `Optional` because the default value is `None`

2021-09-07 16:33 UTC, andyhd commented on commodities/models/dc.py
> +    edges: Dict[str, Commodity] = None
`Optional`

2021-09-07 16:33 UTC, andyhd commented on commodities/models/dc.py
> +            raise
Should this be an `assert`? Why not
```python
if not len(chapters) == 1:
    raise CommodityTreeSnapshotException("All commodities in a group must be from the same HS chapter.")
```

2021-09-07 16:33 UTC, andyhd commented on commodities/models/dc.py
> +        snapshot: "CommodityTreeSnapshot",
If you `from __future__ import annotations`, I think you can do `snapshot: CommodityTreeSnapshot`.

2021-09-07 16:33 UTC, andyhd commented on commodities/models/dc.py
> +    def snapshot_date(self) -> date:
`Optional`

2021-09-08 14:59 UTC, andyhd reviewed
Still going! More comments to come, but here are a bunch for now.

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/conftest.py
> +    transactions = [factory.create(workbasket=workbasket) for _ in range(50)][::-1]
This would be clearer (and more performant) as
```python
transactions = reversed([factory.create(workbasket=workbasket) for _ in range(50)])
```
and if you don't need to create the transactions in advance of stepping through the iterator, you could do
```python
transactions = reversed(factory.create(workbasket=workbasket) for _ in range(50))
```
which might be more memory efficient.

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/conftest.py
> +    return dict(zip(keys, commodities))
`zip` isn't especially esoteric, but this would probably be clearer as
```python
return {
    f"{c.trimmed_do_code}_{c.suffix}_{c.indent}": c
    for c in commodities
}
```

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/conftest.py
> +    print(1)
👀

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/conftest.py
> +    print(measure)
`print`

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/test_dataclasses.py
> +        raise AssertionError(f"Raised exception {error} when it should not!")
I think you could use `pytest.fail` here instead of `raise AssertionError`.

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/test_dataclasses.py
> +        raise AssertionError(f"An unexpected exception {error} raised.")
This seems redundant - an uncaught exception is unexpected by definition.

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/test_dataclasses.py
> +            match = next(re_identifier.finditer(commodity.identifier))
I think this might be clearer without the context manager, eg:
```python
try:
    match = next(re_indentifier.finditer(commodity.identifier))
except StopIteration:
    pytest.fail("Raised StopIteration when it should not!")
```

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/test_dataclasses.py
> +            code, suffix, indent, version = match.groups()
`code, suffix, indent, version = groups`

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/conftest.py
> +    commodities: List[Commodity],
Looks like this should be `Union[List[Commodity], Dict[str, Commodity]]]`

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/conftest.py
> +        ("9900.00.00.00", "80", 0, date_ranges.normal),
You could potentially parametrize this fixture, eg:
```python
@pytest.fixture(params=(
    ("9900.00.00.00", "80", 0),
    ...
))
def commodity(date_ranges, transaction_pool, request):
    return create_commodity(transaction_pool, *request.param, *(date_ranges.normal,)) # a bit ugly
```
which would mean your test functions would be automatically parameterized and could be like
```python
def test_commodity_code(commodity):
    assert commodity.code == commodity.obj.item_id
```
but it looks like this `commodities` fixture is being passed to `create_collection` too, so perhaps a no-go.

2021-09-08 14:59 UTC, andyhd commented on commodities/tests/conftest.py
> +    return dict(zip(keys, commodities))
Since the key is computed from the commodity attributes, you don't really need to return a `dict` here, do you?

2021-09-08 19:55 UTC, stuaxo commented on commodities/migrations/0009_auto_20210902_1002.py
> +# Generated by Django 3.1.12 on 2021-09-02 10:02
@andyhd maybe ?

They are often squashed as a result of something else - releasing, should we start releasing often, or even all the time ?

Things probably get a bit more interesting when data migrations are in the mix (though if we were to do a seed import they go away).

2021-09-08 20:07 UTC, stuaxo commented on commodities/tests/conftest.py
> +    transactions = [factory.create(workbasket=workbasket) for _ in range(50)][::-1]
It's also probably worth using create_batch here:

```python
... factory.create_batch(50, workbasket=workbasket) ...
```

2021-09-09 11:23 UTC, andyhd reviewed
Still going!

2021-09-09 11:23 UTC, andyhd commented on commodities/models/dc.py
> +                msg = "The operation is CREATE but no commodity was provided."
These messages follow a similar pattern, perhaps you could construct them in `_handle_validation_issue` like
```python
self._handle_validation_issue("no commodity was provided")
```
and
```python
def _handle_validation_issue(self, msg: str) -> None:
    """Logs a warning message or raises an error."""
    msg = f"The operation is {self.update_type} but {msg}"
    if self.ignore_validation_rules is True:
        logger.warn(msg)
    else:
        raise ValueError(msg)
```
and perhaps this should be an `Exception` subclass, eg
```python
class CommodityChangeException(ValueError):
    def __init__(self, msg: str, change: CommodityChange) -> None:
        super().__init__(f"Commodity {change.update_type} error: {msg}")
```
which would look like `CommodityChangeException: Commodity Create error: no commodity was provided` in the traceback. Or perhaps even better -
```python
class CommodityChangeException(ValueError):
    pass

class CommodityCreateException(CommodityChangeException):
    pass

class CommodityUpdateException...
```
which would look like `CommodityCreateException: no commodity was provided` in the traceback

2021-09-09 11:23 UTC, andyhd commented on commodities/models/dc.py
> +    def handle_side_effects(self) -> None:
I'd be tempted to rename this something like `collect_side_effects`, or maybe `infer_side_effects`? Because "handle" is quite vague and, to me, implies that something is going to be done with the side effects, rather than just collecting a list of them.

2021-09-09 11:23 UTC, andyhd commented on commodities/models/dc.py
> +          there is no need to strict need to invoke them
there is no need to invoke them

2021-09-09 15:09 UTC, andyhd reviewed
I made it to the end! Still digesting, but looks good to me on first impressions. 💥

2021-09-09 15:09 UTC, andyhd commented on common/models/meta/wrappers.py
> +    "Regulations.Group": "group_id",
We have the concept of "identifying fields" on `TrackedModel` already. Are these keys used differently? I thought that some models could not be uniquely identified by a single field - for example a quota order number can be reused at a later date and can potentially represent an entirely different quota.

2021-09-09 15:09 UTC, andyhd commented on common/models/meta/wrappers.py
> +        envelope = workbasket.title.rsplit(" ", 1)[1]
👀

2021-09-09 15:09 UTC, andyhd commented on common/models/meta/wrappers.py
> +    "Regulations.Group": "group_id",
Are these just for display?

2021-09-09 15:09 UTC, andyhd commented on common/models/meta/wrappers.py
> +        transaction_id: int = None,
`Optional`

2021-09-09 15:09 UTC, andyhd commented on common/models/meta/wrappers.py
> +    def is_current_as_of_transaction_id(self, transaction_id: int = None) -> bool:
`Optional`

2021-09-10 07:32 UTC, kintisheff commented on commodities/migrations/0009_auto_20210902_1002.py
> +# Generated by Django 3.1.12 on 2021-09-02 10:02
^ what is the preference, naming them or not? i'm agnostic

2021-09-10 07:34 UTC, kintisheff commented on commodities/models/dc.py
> +            return
it's `Optional[int]`

2021-09-10 07:57 UTC, kintisheff commented on commodities/models/dc.py
> +            raise
readibility

2021-09-10 08:05 UTC, kintisheff commented on commodities/tests/conftest.py
> +    factory = factories.MeasureFactory
I think that's just black reformatting it this way

2021-09-10 08:07 UTC, kintisheff commented on commodities/tests/conftest.py
> +    transactions = [factory.create(workbasket=workbasket) for _ in range(50)][::-1]
good shout on readability/performance with reversed and on use of create batch. unfortunately, the pool is needed in advance so that will need to stay

2021-09-10 08:28 UTC, kintisheff commented on commodities/tests/conftest.py
> +    return dict(zip(keys, commodities))
using a mapping here makes the tests code more readable elsewhere

2021-09-10 08:32 UTC, kintisheff commented on commodities/tests/test_dataclasses.py
> +            match = next(re_identifier.finditer(commodity.identifier))
three people don't like the context manager by now. ok :) it's just for readability

2021-09-10 08:39 UTC, kintisheff commented on commodities/tests/conftest.py
> +        ("9900.00.00.00", "80", 0, date_ranges.normal),
yep that's the reason (your latest point)

2021-09-10 08:40 UTC, kintisheff commented on commodities/models/dc.py
> +    commodities: List[Commodity]
anything is allowed, the order is not significant (unless in the case of `CommodityTreeSnapshot`, where order is ensured in post_init)

2021-09-10 08:42 UTC, kintisheff commented on commodities/models/dc.py
> +            raise ValueError("Unknown relation")
ah true

2021-09-10 08:48 UTC, kintisheff commented on commodities/models/dc.py
> +        return CommodityCollection(self.commodities[:])
agnostic. i'll use `copy`

2021-09-10 08:50 UTC, kintisheff commented on commodities/models/dc.py
> +    attrs: Dict[Any, Any] = None
it's `dict[str, Any]` def

2021-09-10 08:54 UTC, kintisheff commented on commodities/models/dc.py
> +    side_effects: Dict[Union[str, int], SideEffect] = None
adding the type will improve readability, yes!

2021-09-10 08:59 UTC, kintisheff commented on commodities/models/dc.py
> +                msg = "The operation is CREATE but no commodity was provided."
^ yes to all

2021-09-10 09:05 UTC, kintisheff commented on commodities/models/dc.py
> +                msg = "The operation is CREATE but no commodity was provided."
actually i'll stop with `CommodityChangeException`

2021-09-10 09:07 UTC, kintisheff commented on commodities/models/dc.py
> +    def handle_side_effects(self) -> None:
agreed! i will go with `preempt_side_effects`

2021-09-10 09:14 UTC, kintisheff commented on commodities/models/dc.py
> +            gvb.upper and gvb.upper < ovb.lower
agree in principle. Postgres' daterange supports all sorts of contains, overlaps, etc, but that can only be leveraged in django db query constructs, but the psycopg2 Range only provides __contains__ (but perhaps because overlaps can be constructed from the other dundrs of Range

2021-09-10 09:16 UTC, kintisheff commented on commodities/models/dc.py
> +        # Mark the object for update with trimmed validity
also agree. won't touch it for now but re this and above comment, will add a ticket to attach some reusable convenience methods not just to TaricDateRange but other frequently used classes - and cleanup related DRY violations in our code

2021-09-10 09:18 UTC, kintisheff commented on commodities/models/dc.py
> +            )
a bit controversial though as we might need a separate ticket to refactor and unify ME32 uses (I think i pinned a TODO somewhere there). so would defer to that separate ticket.

2021-09-10 09:19 UTC, kintisheff commented on commodities/models/dc.py
> +            )
^ same remark as above, i'll punch in a separate ticket (which actually will partially revolve around wrappers and the introduction on ModelMeta from labs as previously discussed last week during deep dive)

2021-09-10 09:20 UTC, kintisheff commented on commodities/models/dc.py
> +        clone = self.collection.clone()
neat

2021-09-10 09:23 UTC, kintisheff commented on commodities/models/dc.py
> +                        if _validities_overlap(measure, related_measure):
^ potentially yes, see reply to earlier comment re ME32

2021-09-10 09:25 UTC, kintisheff commented on commodities/tests/test_dataclasses.py
> +    re_identifier = re.compile(r"([0-9\.]{13})-([1-8]{1}0)-([0-9]{1,2})/([0-9]{1})")
true it's an rstring already

2021-09-10 09:28 UTC, kintisheff commented on commodities/tests/test_dataclasses.py
> +    commodities = set(map(lambda x: x.identifier, snapshot.commodities))
agree

2021-09-10 09:31 UTC, kintisheff commented on commodities/tests/test_dataclasses.py
> +                assert groups[0] == str(snapshot.moment)
yes, except using `hash_` since hash is a reserved keyword

2021-09-10 09:36 UTC, kintisheff commented on common/models/meta/wrappers.py
> +TRACKEDMODEL_PRIMARY_KEY = "id"
yes, that would be safer even though as you point out by definition this wrapper only wraps models that inherit from `TrackedModel`

2021-09-10 09:38 UTC, kintisheff commented on common/models/meta/wrappers.py
> +    "Regulations.Group": "group_id",
yes they are used differently, and these are used in viz displays primarily yes (their use will become more apparent in coming tickets, for now i've just chucked them in there as I already need to ref them in the wrapper

2021-09-10 09:39 UTC, kintisheff commented on common/models/meta/wrappers.py
> +        envelope = workbasket.title.rsplit(" ", 1)[1]
ah yes, we did this to ourselves :) /unless i'm missing something/

2021-09-10 09:40 UTC, andyhd commented on commodities/models/dc.py
> +            raise
Also `assert` should generally be avoided for non-test code, as it is not executed if optimization is turned on.

But even if you want to keep this as `assert`, you can replace this with
```python
assert len(chapters) == 1, "All commodities in a group must be from the same HS chapter."
```

2021-09-10 10:00 UTC, kintisheff commented on commodities/models/__init__.py
> +]
it's related to how `manage.py` handles these imports

2021-09-10 10:07 UTC, kintisheff commented on commodities/models/dc.py
> +            raise
^agree with this

2021-09-10 10:08 UTC, kintisheff commented on common/models/meta/wrappers.py
> +        envelope = workbasket.title.rsplit(" ", 1)[1]
(therefore the TODO)

2021-09-10 10:22 UTC, andyhd commented on common/models/meta/wrappers.py
> +        envelope = workbasket.title.rsplit(" ", 1)[1]
I was just checking you meant to leave that TODO there. I thought the logic looks sketchy, but then I realised that these properties may only be used for display.

2021-09-10 10:52 UTC, andyhd approved these changes
Very nice 👍

2021-09-10 12:41 UTC, stuaxo commented on commodities/tests/conftest.py
> +    return dict(zip(keys, commodities))
+1 on the dict comprehension @andyhd suggested above.

2021-09-10 12:44 UTC, stuaxo commented on commodities/tests/conftest.py
> +def commodities_spanned(date_ranges, transaction_pool):
A docstring would be nice here, and in the fixtures below.

2021-09-10 12:46 UTC, stuaxo commented on commodities/tests/test_dataclasses.py
> +# from conftest import not_raises
Old commented code.

2021-09-15 16:24 UTC, simonwo requested changes
You already know I agree with the design in principle :)

I'm a little unsure if the testing is thorough enough – I feel like I've found a bunch of places where tests are needed. E.g. did you get all the test cases associated with `commodities/tests/test_import_handlers.py`? There are some tricky cases in there of e.g three levels of zero indent, and of children arriving before their parents, that we have added by observation when fixing bugs, and I this code will need to pass them.

I'm also not happy about much of the code in `common/models/meta/*` because it seems like it is repeating a lot of the things we have elsewhere or should live elsewhere (e.g. most of this could live in `common/models/records.py`). It also seems to be taking a lot of shortcuts and returning data that is incorrect in lots of places. I'm not clear on why we need much of this? "For display in a data engineer's notebook" is fine, but that doesn't mean it has to live in the main repo. Or if we're really keen on it being in the main repo, then I'm not happy committing things that return misleading results in some circumstances and not finding the right place in the code base for them to live.

Keen to hear thoughts.

2021-09-15 16:24 UTC, simonwo commented on common/models/meta/wrappers.py
> +    "Regulations.Group": "group_id",
Agreed that this should be delegated to each individual model. But what are they used for? Is `IDENTIFIER KEYS` a good name… because as Andy points out, they are not unique.

2021-09-15 16:24 UTC, simonwo commented on common/models/meta/wrappers.py
> +        field."""
This docstring doesn't tell me what this does or what properties these identifiers have. As above, they are not unique from model to model, so what are they for?

2021-09-15 16:24 UTC, simonwo commented on common/models/meta/wrappers.py
> +        return key
Why is this not just the `__str__` of the model?

2021-09-15 16:24 UTC, simonwo commented on common/models/meta/wrappers.py
> +        except self.model.DoesNotExist:
Shouldn't this only get raised if the object itself does not exist? Why would that be raised here?

2021-09-15 16:24 UTC, simonwo commented on common/models/meta/wrappers.py
> +                return f"{validity_start.strftime(DATE_FORMAT)} - inf"
But this isn't correct – an object with a validity start date is not valid for unlimited time, it's valid up until the start of the next model. See the docstring on `ValidityStartMixin`.

2021-09-15 16:24 UTC, simonwo commented on common/models/meta/wrappers.py
> +            record_type = "0"
This is surely not ok

2021-09-15 16:47 UTC, kintisheff commented
> You already know I agree with the design in principle :)
> 
> I'm a little unsure if the testing is thorough enough – I feel like I've found a bunch of places where tests are needed. E.g. did you get all the test cases associated with `commodities/tests/test_import_handlers.py`? There are some tricky cases in there of e.g three levels of zero indent, and of children arriving before their parents, that we have added by observation when fixing bugs, and I this code will need to pass them.
> 
> I'm also not happy about much of the code in `common/models/meta/*` because it seems like it is repeating a lot of the things we have elsewhere or should live elsewhere (e.g. most of this could live in `common/models/records.py`). It also seems to be taking a lot of shortcuts and returning data that is incorrect in lots of places. I'm not clear on why we need much of this? "For display in a data engineer's notebook" is fine, but that doesn't mean it has to live in the main repo. Or if we're really keen on it being in the main repo, then I'm not happy committing things that return misleading results in some circumstances and not finding the right place in the code base for them to live.
> 
> Keen to hear thoughts.

Yes to both:
1) I picked up a few more scenarios while doing the plumbing (TP-931) - and will add a few more tests in scenarios as a result; however we can't predict them all and ultimately my suggestion would be to ensure some extra coverage here, but then ensure more scenario coverage in separate tickets down the road as we encounter more outlier cases.
2) We also had the same chat with Stuart and agreed that `TrackedModelWrapper` is overkill and/or redundant for now (it would become more relevant when we start doing the model meta facades - so i'll clean it up from this PR as we actually don't need it here)

2021-09-15 16:48 UTC, kintisheff commented on commodities/business_rules.py
> +            return
ah that's a good shout!

2021-09-15 16:48 UTC, kintisheff commented on commodities/business_rules.py
> +                good.transaction,
happy to change

2021-09-15 16:49 UTC, kintisheff commented on commodities/models/constants.py
> +    TRANSACTION = auto()
good question; we can move it there; since we're doing more work down the line on clocks, might make sense indeed.

2021-09-15 16:50 UTC, kintisheff commented on commodities/models/dc.py
> +        return self.code[:8]
one reason alone - wanted to see if people want them in model first (didn't want to presume and pollute), if yes, than i'm totally for it

2021-09-15 16:51 UTC, kintisheff commented on commodities/models/dc.py
> +        return self.trimmed_code == self.code
same reply as above, will do that

2021-09-15 16:53 UTC, kintisheff commented on commodities/models/dc.py
> +        obj = self.obj.indents.order_by("validity_start").last()
i've changed it! will push the changes with the commit that reflects all your other comments

2021-09-15 16:56 UTC, kintisheff commented on commodities/models/dc.py
> +        )
We're comparing the wrapper states, not the underlying obj states here.
`Commodity.identifier` will be a function of code, suffix, indent and version
E.g. in an `UpdateType.UPDATE` scenario, the indent (e.g.) might be changed on the wrapper to simulate a new snapshot and look for side effects, but the underlying obj will continue to have the same sid. so this __eq__ needs to be more detailed than sid

2021-09-15 16:57 UTC, kintisheff commented on commodities/models/dc.py
> +        return f"{code:0<10}"
wasn't aware of that method, will check it

2021-09-15 16:59 UTC, kintisheff commented on commodities/models/dc.py
> +    values: dict[str, Union[Commodity, list[Commodity]]]
good spot, remnants from a prior iteration:
`exists` is redundant now
`values` can be a list now indeed

2021-09-15 17:00 UTC, kintisheff commented on commodities/models/orm.py
>          )
exactly! also a remnant from a prior iteration - thanks for spotting

2021-09-15 17:01 UTC, kintisheff commented on commodities/tests/test_dataclasses.py
> +        pytest.fail(f"Raised exception {error} when it should not!")
i don't think we use it anymore actually in the tests; will remove

2021-09-15 17:02 UTC, kintisheff commented on common/models/meta/wrappers.py
> +TRACKEDMODEL_IDENTIFIER_FALLBACK_KEY = "sid"
i'll check

2021-09-15 17:03 UTC, kintisheff commented on commodities/models/dc.py
> +            generation = children
yes `get_descendants` is expensive at the moment. didn't want to pre-materilize it either though; i'll fish for smarter algorithms

2021-09-15 17:06 UTC, kintisheff commented on commodities/models/dc.py
> +            ),
just in case :)

2021-09-15 17:07 UTC, kintisheff commented on commodities/models/dc.py
> +                    parent = None
YES!! noticed that as well - also fixed and I'll push in the commit that reflects your other comments.

2021-09-15 17:08 UTC, kintisheff commented on commodities/models/dc.py
> +                indents[indent] = commodity
no, just the latest commodity in the sorted order. we don't need to remember the prior ones (therefore the pre-sort). except when the indent is `0` of course

2021-09-15 17:15 UTC, kintisheff commented on commodities/models/dc.py
> +                pass
`remove` rasies a `ValueError` if it receives `None` as value. this is another way of saying, you can't do an update if there is no `current` commodity in the `CommodityChange` object. 
The algo then is this:
1. always try to delete the current commodity - this will only work if the op is `DELETE` or `UPDATE` because only in those cases do you have `self.current != None` (CommodityChange validates the sanity of the op with respect to the provided attributes in `__post__init__`)
2. if op is `DELETE`, nothing else to do, leave
3. if op is `UPDATE` or `CREATE`, there will be a `candidate`, add it to the `CommodityCollection`

Does this answer it sufficiently?

2021-09-15 17:17 UTC, kintisheff commented on commodities/models/dc.py
> +        today = date.today()
we agree in a conversation not to allow that to happen at the moment  (taking both a transaction and a calendar snapshot at the same time) - I can bring that capability back of course

2021-09-15 17:18 UTC, kintisheff commented on commodities/models/dc.py
> +        today = date.today()
(or am I misunderstanding your point here?)

2021-09-15 17:19 UTC, kintisheff commented on commodities/models/dc.py
> +                )
fair, we can allow it then - should we not still issue a warning though at least?

2021-09-15 17:21 UTC, kintisheff commented on commodities/models/dc.py
> +        affected commodity collection c) ensure that the requested changes do
via preemption of side effects

2021-09-15 17:21 UTC, kintisheff commented on commodities/models/dc.py
> +            )
YES! please suggest something, my muse has been obdurate on this one

2021-09-15 17:22 UTC, kintisheff commented on commodities/models/dc.py
> +            for measure in good.measures.latest_approved().all():
measures should be enough I think, yes

2021-09-15 17:26 UTC, kintisheff commented on commodities/models/dc.py
> +            )
yes to actual values! it's changed pending commit already
re the other potential issue, need to factor that in, good shout!

2021-09-15 17:37 UTC, kintisheff commented on commodities/models/dc.py
> +            gvb.upper and gvb.upper < ovb.lower
no - we're only checking if a measure end date is before the `start_date` of a commodity, we're not comparing measure end date to commodity end date

if a measure end date is before the start date of the commodity, there is no date range overlap at all
if a measure start date is after the end date of the commodity, there is no date range overlap at all

thus if a measure end date is only before the _end date_ of a commodity (and not before the _start date_ as well)
(e. g. `gvb.upper and ovb.upper and ovb.upper < gvb.upper`), 
this `or` condition will not trigger and the measure will not be deleted (at least not for this reason, it may be deleted for other reasons down the line)

I could always be going senile of course, so pls shout if this doesn't make sense

2021-09-15 17:38 UTC, kintisheff commented on commodities/tests/conftest.py
> +    return factory.create(transaction=transaction, **kwargs)
yep i think so

2021-09-15 17:40 UTC, kintisheff commented on commodities/tests/conftest.py
> +  where needed, retaining the ability to add delayed_transactions as well
ME type business rules will check on commodities up to their own transaction often.
NG type business rules will check on measures up to their own transaction in some cases too.
In order to avoid not triggering some rules incidentally, I needed this. (this is an issue arising in testing only)

2021-09-15 17:41 UTC, kintisheff commented on common/models/meta/wrappers.py
> +        field."""
for visialization purposes only, but as per prior comments, this is not needed here and will go away for this PR

2021-09-15 17:42 UTC, kintisheff commented on common/models/meta/wrappers.py
> +        return key
`TrackedModelWrapper` is being removed, but yes, that could be the str dundr

2021-09-15 17:42 UTC, kintisheff commented on common/models/meta/wrappers.py
> +        except self.model.DoesNotExist:
good point

2021-09-15 17:43 UTC, kintisheff commented on common/models/meta/wrappers.py
> +                return f"{validity_start.strftime(DATE_FORMAT)} - inf"
true; also this has been removed by now, just need to commit and push

2021-09-15 17:43 UTC, kintisheff commented on common/models/meta/wrappers.py
> +            record_type = "0"
indeed - and has been removed :)

2021-09-15 17:48 UTC, kintisheff commented on commodities/models/dc.py
> +            gvb.upper and gvb.upper < ovb.lower
there's a broader issue here: should perhaps make these checks stand alone functions and surround them with the appropriate entourage of tests

2021-09-16 09:06 UTC, stuaxo commented on commodities/business_rules.py
>      # XXX this is redundant - NIG34 will be violated first
^ For some future PR, these sort of things point to something we can encode in the machinery itself (either it knows and optimises them away, or we can add tests or something (hand waves ))

2021-09-16 09:13 UTC, stuaxo commented on common/models/meta/wrappers.py
> +            record_type = "0"
I remember seeing somehow rationalising it like "oh, there must be a good reason" before it even got to the front of my mind properly !???

2021-09-16 09:18 UTC, stuaxo commented on common/models/meta/wrappers.py
> +    def version(self) -> int:
Transaction.id won't work as a version.

You won't be able to get one int, the best you can do once my TP-841 is merged is a tuple of `(transaction.partition, transaction.order)`

For current master things are a little more complex, though if you transactions from the seed import and non approved workbaskets you could get away with it.

2021-09-16 09:43 UTC, simonwo commented on commodities/models/dc.py
> +                indents[indent] = commodity
Ahh yes, of course!

2021-09-16 09:44 UTC, simonwo commented on commodities/models/dc.py
> +        today = date.today()
I do remember the conversation but can't remember why now … 🤦‍♂️

2021-09-16 09:45 UTC, simonwo commented on commodities/models/dc.py
> +        affected commodity collection c) ensure that the requested changes do
Ah yeah fair enough

2021-09-16 11:39 UTC, kintisheff commented on commodities/models/dc.py
> +        return f"{code:0<10}"
yep will use that

2021-09-16 12:08 UTC, kintisheff commented on commodities/models/dc.py
> +            return False
turns out it's better to leave it returning `False` as there are many cases where we are comparing a missing current or candidate commodity to another commodity (legitimately)

2021-09-16 12:30 UTC, kintisheff commented on commodities/models/orm.py
>          )
i think we didn't want the devs to have too much freedom at first, before we hash clocks out better - and I continue to agree with your point there!

2021-09-16 12:32 UTC, kintisheff commented on commodities/models/dc.py
> +        today = date.today()
i think we didn't want the devs to have too much freedom at first, before we hash clocks out better - and I continue to agree with your point there!

2021-09-16 13:05 UTC, kintisheff commented on common/models/meta/wrappers.py
> +TRACKEDMODEL_IDENTIFIER_FALLBACK_KEY = "sid"
yep switching to that

2021-09-16 13:07 UTC, kintisheff commented on commodities/models/dc.py
> +                )
i'm changing it as a log warning only, not raising error

2021-09-20 09:57 UTC, simonwo commented on commodities/models/dc.py
> +    def snapshot_transaction(self) -> Optional[int]:
Returns a `Transaction` object, not `int`

2021-09-22 09:41 UTC, kintisheff commented
`c1ef6ff` also fixes the handling of parent-child relations for cases with multiple 0-indent headings

2021-09-22 11:37 UTC, simonwo approved these changes

2021-09-22 11:37 UTC, simonwo commented on commodities/models/orm.py
> +
This is defined twice?

2021-09-22 11:37 UTC, simonwo commented on commodities/models/orm.py
> +        if not self.code.is_taric_code:
We have changed all the call sites of this but we still have a functioning `is_taric_code` property, so can we revert these back to `self.is_taric_code`?

2021-09-22 11:37 UTC, simonwo commented on commodities/models/orm.py
> +        ).approved_up_to_transaction(self.transaction)
I think this is a little wrong in the same way that `in_use` is wrong, in that it should be a function of a user-supplied transaction rather than `self.transaction`. The latter will only tell you the measures that are there at the point the commodity was created or updated…

2021-09-22 11:38 UTC, simonwo commented
Can we make sure to squash this branch when merging :)

2021-09-22 11:49 UTC, kintisheff commented on commodities/models/orm.py
> +        if not self.code.is_taric_code:
done

2021-09-22 11:55 UTC, kintisheff commented on commodities/models/orm.py
> +        ).approved_up_to_transaction(self.transaction)
that's just how the original `in_use` was written - happy to write a separate ticket to investigate if that needs improvement. in TP-803, we only use dependent measures in the context of a snapshot (except in some tests where it is more convenient).

2021-09-22 11:56 UTC, kintisheff commented
> Can we make sure to squash this branch when merging :)

I thought we typically squash

2021-09-22 11:58 UTC, kintisheff commented on commodities/models/orm.py
> +
fixed

2021-09-23 07:06 UTC, merged