Tp 794 install google tag manager in to service
uktrade/tamato pull request #377
Opened 2021-09-08 11:19 UTC by gabelton

## Why

This change is required, in order to support go-live for the service

## What

- In _generic.jinja conditionally add Google Tag Manager script into <head> and noscript into <body> on the basis of whether GOOGLE_ANALYTICS_ID environment variable has been set.
- In settings/common.py add GOOGLE_ANALYTICS_ID environment variable. This should be set in AWS EBS for production only.

## Checklist
- Needs GOOGLE_ANALYTICS_ID to be set as environment variable in AWS EBS prod before deployment.

(Original ticket https://uktrade.atlassian.net/browse/TP-794)

2021-09-08 14:02 UTC, simonwo commented on common/jinja2/layouts/_generic.jinja
> +        })(window,document,'script','dataLayer', {{settings.GOOGLE_ANALYTICS_ID}});
Does the `{{ … }}` need to have string quotes around it? Or does Jinja know to do that automatically?

2021-09-08 14:53 UTC, gabelton commented on common/jinja2/layouts/_generic.jinja
> +        })(window,document,'script','dataLayer', {{settings.GOOGLE_ANALYTICS_ID}});
I think Jinja does it automatically. After adding this I had a play around in my local and I was able to pass through a value.

2021-09-10 10:28 UTC, stuaxo commented
Make sure to add any new environment variables note in the environment variables section in the README.md.

2021-09-10 10:30 UTC, stuaxo commented on settings/common.py
> +# -- Google Tag Manager
Make sure to document this in the README as well.

If we have a page on our RTFM docs, it's worth making a link to it, from here or from the README.

2021-09-10 10:31 UTC, stuaxo approved these changes

2021-09-10 10:32 UTC, stuaxo commented on common/jinja2/layouts/_generic.jinja
> +        })(window,document,'script','dataLayer', {{settings.GOOGLE_ANALYTICS_ID}});
To make the indentation consistent, I think it should be `{{ settings.GOOGLE_ANALYTICS_ID }}`

2021-09-10 10:38 UTC, andyhd requested changes
I think @simonwo was right

2021-09-10 10:38 UTC, andyhd commented on common/jinja2/layouts/_generic.jinja
> +        })(window,document,'script','dataLayer', {{settings.GOOGLE_ANALYTICS_ID}});
I think it should have quotes. I'm pretty sure Jinja does not do it automatically.
```python
>>> jinja2.Template("""<script>var some_var = {{value}};</script>""").render({"value": "a_string"})
'<script>var some_var = a_string;</script>'
```

2021-09-10 10:38 UTC, andyhd commented on settings/common.py
> +GOOGLE_ANALYTICS_ID = os.environ.get("GOOGLE_ANALYTICS_ID", None)
`None` is the default default value, so you can just do `.get("GOOGLE_ANALYTICS_ID")`

Obviously doesn't need fixing, I just wanted to write "default default" 😄

2021-09-10 10:45 UTC, andyhd commented on common/jinja2/layouts/_generic.jinja
> +        })(window,document,'script','dataLayer', {{settings.GOOGLE_ANALYTICS_ID}});
I just thought - maybe check whether you have quotes in the `settings.GOOGLE_ANALYTICS_ID` string value (eg: your env var is `GOOGLE_ANALYTICS_ID="'some-id-string'"`)

2021-09-10 11:22 UTC, simonwo commented on common/jinja2/layouts/_generic.jinja
> +        <iframe src="https://www.googletagmanager.com/ns.html?id="{{ settings.GOOGLE_ANALYTICS_ID }}""height="0" width="0" style="display:none;visibility:hidden"></iframe>
Nah, not this one… the quotes will end up ending the `href` element. It should have just been as it was in the previous version.

2021-09-10 14:45 UTC, gabelton commented on common/jinja2/layouts/_generic.jinja
> +        })(window,document,'script','dataLayer', {{settings.GOOGLE_ANALYTICS_ID}});
The env var in Vault doesn't have quotes around it

2021-09-10 14:54 UTC, andyhd approved these changes

2021-09-10 15:24 UTC, merged