TP-857 Newly created descriptions don't appear on the Descriptions tab
uktrade/tamato pull request #387
Opened 2021-09-24 10:35 UTC by gabelton

## Why
The descriptions tab isn't displaying descriptions for footnotes after creating a footnote or editing one.

## What
- Updates the descriptions.jinja template to use object.descriptions.all() instead of object.get_descriptions(), as this was returning an empty queryset for footnotes.

<img width="756" alt="Screenshot 2021-09-24 at 11 28 53" src="https://user-images.githubusercontent.com/46938749/134661099-ce99fb32-e0d1-4d43-ad50-8a4103d8daab.png">

2021-09-24 11:14 UTC, andyhd requested changes

2021-09-24 11:14 UTC, andyhd commented on common/jinja2/includes/common/tabs/descriptions.jinja
> +{% for description in object.descriptions.all() %}
This will fetch all versions of descriptions. You want at least `object.descriptions.latest_approved()` or object.descriptions.approved_up_to_transaction(transaction)`.

Is it possible that no descriptions were returned because there are no currently approved descriptions?

2021-09-24 13:21 UTC, simonwo commented on common/jinja2/includes/common/tabs/descriptions.jinja
> +{% for description in object.descriptions.all() %}
The latter one – so that the user can see the descriptions or changes to them that are contained in the draft workbasket they have open, which may not be approved yet.

It's possible there are no approved descriptions because you can create an object and an it's description, and neither will be approved until the workbasket is submitted.

2021-09-24 13:49 UTC, gabelton commented on common/jinja2/includes/common/tabs/descriptions.jinja
> +{% for description in object.descriptions.all() %}
I think the problem is with get_descriptions. In this case it's returning query.latest_approved() which is empty because the footnote and description have only just been created and haven't been approved yet.

2021-09-24 15:32 UTC, gabelton commented on common/jinja2/includes/common/tabs/descriptions.jinja
> +{% for description in object.descriptions.all() %}
(I wrote the above before I saw that you'd already summed it much more eloquently, Simon!)

2021-09-24 15:46 UTC, stuaxo commented on common/jinja2/includes/common/tabs/descriptions.jinja
> +{% for description in object.descriptions.all() %}
The `Workbasket.from_session(…).last_transaction` to get the last_transaction of the current session seems like something we will want in other places, it's may be worth thinking about what an API for that should look like.

2021-09-27 09:25 UTC, gabelton commented on common/jinja2/includes/common/tabs/descriptions.jinja
> +{% for description in object.descriptions.all() %}
I've just pushed some changes and a test now. Is there a scenario where we would want to return query.latest_approved() instead of query.approved_up_to_transaction(transaction=WorkBasket.get_current_transaction(request),)? I've been poking around in my local and it seems that either the two querysets are the same or query.approved_up_to_transaction covers the user's most recent change, which we want to display to them, even if it's not been approved yet.

2021-09-27 10:18 UTC, andyhd approved these changes
This is part of what I'm working on right now. It would be nice to not have to pass the request to `get_descriptions`, and have it be able to get the current transaction from the session itself.

2021-09-27 10:21 UTC, andyhd commented on common/jinja2/includes/common/tabs/descriptions.jinja
> +{% for description in object.descriptions.all() %}
`latest_approved` only really makes sense if there is no current workbasket/transaction, but we've changed the design so that there is always a workbasket. Perhaps if we allow non-authenticated users to browse (but not edit), or switch back to multiple concurrent workbaskets in future.

2021-10-05 15:52 UTC, merged