TP-977 Update, restructure and GOV.UK style code docs
uktrade/tamato pull request #399
Opened 2021-10-19 16:41 UTC by andyhd

# TP-977 Update, restructure and GOV.UK style code docs

## Why

Keeping the codebase documentation up to date is important for knowledge sharing, both for getting new starters up to speed and for keeping ongoing development and maintenance flowing without interruption when knowledge is held only by certain individuals who are absent or leave the project. As changes to the codebase are made, it is often the case that the documentation falls behind, until it is inaccurate, misleading or irrelevant.

This PR is a first in a number of updates across the various components of the codebase, to structure the documentation for ease of use and to identify under-documented, missing or out-of-date areas.

## What

* Added CONTRIBUTING and CODE_OF_CONDUCT documents
* Restructure README to the following:
    1. Introduction
    2. Getting started (install and run with Docker)
    3. Development environment
    4. Using the importer
    5. Using the exporter
    6. How to contribute
    7. How to deploy
* Move detailed information on running tests to separate document
* Move environment variable glossary to separate document
* Remove deprecated documentation of PaaS SSH tunnel Makefile targets
* General table of contents restructuring
* Small fixes to prevent 500 errors with uninitialized database
* Small fixes to Docker compose file
* Add GOV.UK Sphinx theme
  Before: 
<img width="862" alt="Screenshot 2021-11-01 at 11 29 34" src="https://user-images.githubusercontent.com/35194/139665785-da155b99-cf35-495a-832d-0eaeda069a7d.png">

  After: 
<img width="1134" alt="Screenshot 2021-11-01 at 11 29 06" src="https://user-images.githubusercontent.com/35194/139665805-23d15a99-9850-4b38-9650-5c2ed76e85f3.png">

2021-11-01 15:30 UTC, stuaxo commented on commodities/__init__.py
> +classification, is the name for the full list of products in the UK Tariff.
Is it mentioning the tree like structure of the commodity codes here, since the next section is about altering it ?

2021-11-01 15:34 UTC, stuaxo commented on commodities/__init__.py
> +
Maybe more for @kintisheff who wrote the OG of this: this throws us straight into the benefits of the Commodity Wrapper without a tiny sentence to say what it is.

2021-11-01 15:42 UTC, paulpepper-trade requested changes

2021-11-01 15:42 UTC, paulpepper-trade commented on README.rst
> +    $ cp sample.env .env
Does the `sample.env` just work or are some edits necessary to get a docker instance running? I don't run Tamato in a container, so I'm unsure, but had to make some changes to do a local `runserver` (for instance `SSO_ENABLED=false`).

2021-11-01 15:42 UTC, paulpepper-trade commented on README.rst
> +
There's a deployment section within the Tamato playbook (https://readme.trade.gov.uk/docs/playbooks/trade-tariff-management.html), which could be referenced here.

2021-11-01 15:42 UTC, paulpepper-trade commented on README.rst
> +Accessing databases in GOV.UK PaaS
There's a section in tamato playbook for this too (https://readme.trade.gov.uk/docs/playbooks/trade-tariff-management.html#specific-support-tasks). The playbook is out of date in quite a few areas and we should probably only keep this information in one place. I'd usually consider closest to the source code to be the better option, though I'm uncertain whether there reasons to do otherwise here.

2021-11-01 15:53 UTC, andyhd commented on README.rst
> +    $ cp sample.env .env
Hm, I changed `SSO_ENABLED` to `False` in `sample.env` - must have forgotten to commit it.

2021-11-02 10:21 UTC, andyhd commented on commodities/__init__.py
> +
Yeah, I'll be editing the component documentation in later tasks

2021-11-02 10:23 UTC, andyhd commented on README.rst
> +
Yes, I was wondering about avoiding the duplication of effort. Perhaps we can move the playbook documentation into the code documentation and add a step to the master branch Github Actions / Jenkins pipeline to publish to readme.trade.gov.uk? Perhaps something for another task.

2021-11-05 15:41 UTC, andyhd commented on README.rst
> +
This may be a higher priority task than I originally though, as the playbook looks to be confused between this project and the previous prototype.

2021-11-05 15:51 UTC, andyhd commented on README.rst
> +
Created a task in Jira https://uktrade.atlassian.net/browse/TP-1054

2021-11-08 12:34 UTC, paulpepper-trade approved these changes

2021-11-08 14:10 UTC, merged