Tp 1015 mvp tariff managers are presented with the ability to download an envelope
uktrade/tamato pull request #476
Opened 2022-01-25 17:59 UTC by gabelton

## Why
To enable Tariff Managers to self service and make changes to the tariff, they need to be able to download the envelope to send to HMRC

## What
- Updates upload_workbasket_envelopes task to accept workbasket_ids param
- Updates WorkBasketSubmitView so that that task is called for the workbasket being submitted
- Updates DashboardView so that most recently approved workbasket dates are passed in to jinja download template
- Creates download_workbasket function view which gets the most recently uploaded envelope from s3 and serves it as attachment on the response.
- Adds view tests

Original design ticket https://uktrade.atlassian.net/browse/TP-1014

<img width="1330" alt="Screenshot 2022-01-25 at 17 58 49" src="https://user-images.githubusercontent.com/46938749/151032803-d6efdf5a-7c08-44a5-a0d3-8f8d23dd1e7a.png">

2022-01-25 21:44 UTC, stuaxo commented on exporter/tasks.py
> +        workbaskets = WorkBasket.objects.is_approved().filter(id__in=workbasket_ids)
It looks like like the line 114 does the same thing as the first part of this, could it be re-used and filtered by id ?

```python
workbaskets = workbaskets.filter(id__in=workbasket_ids)
```

2022-01-25 21:45 UTC, stuaxo commented on workbaskets/tests/test_views.py
> +@patch("exporter.tasks.send_upload_notifications.s")
Patching the celery task signature will work, but feels a brittle, I think we set celery to "always eager" during tests, so we can call the tasks, we need to make sure they don't *actually* upload anything to S3 or call APIs.

2022-01-25 21:46 UTC, stuaxo commented on workbaskets/tests/test_views.py
> +    assert envelopes.called
It's best to check things were called with expected arguments, where possible.

2022-01-25 21:56 UTC, stuaxo commented on workbaskets/views/__init__.py
> +    Creates lambda function for sorting s3 objects by `last_modified` attribute.
Instead of grabbing the whole list of s3 objects and finding the oldest one, we could use information in our database.

We have an Upload object with a FileField, for every Envelope.
If there isn't a date for last modified, one could be added.

If you need further tracking of s3 objects, then the etag is a unique id for every s3 object, you can use it to request a particular object as needed.

2022-01-25 22:03 UTC, stuaxo commented on workbaskets/views/__init__.py
> +            ] = "attachment; filename=" + os.path.basename(last_added.key)
I'm assuming the bucket isn't accessible on the client side, for security (otherwise you could just send a redirect pointing at it).

Streaming the file is probably more optimal than downloading the whole thing.

boto has StreamingBody and iter_lines which allow you to stream, from s3.
On the django side [StreamingHttpResponse](https://docs.djangoproject.com/en/3.2/ref/request-response/#streaminghttpresponse-objects) sends data out as it's received.

2022-01-25 22:08 UTC, stuaxo commented on common/views.py
> +    def approved_workbasket(self):
There is only one approved workbasket now, but in the future there may be many, maybe the name could reflect that this is the last approved_workbasket.

Definitely add a docstring too :)

2022-01-25 22:13 UTC, stuaxo commented on exporter/tasks.py
> +def upload_workbasket_envelopes(self, upload_status_data, workbasket_ids=None) -> Dict:
There's something to think about, re: failure modes and ordering.

When things are working OK:
- the user activates the job (e.g. by clicking a button),
- celery queues the job
- the job runs straight away
- everything is OK.

If there are issues with celery tasks may queue up and order may not be guaranteed.
It makes me wonder if we need to separately store the ordered list of manually queued workbaskets[1] ?

As a side effect it could make the task idempotent again.

[1] - Although this gets closer to Bos "task" design.

2022-01-25 22:24 UTC, stuaxo commented on workbaskets/views/__init__.py
> +        upload.delay()
It looks like `upload` wants to be a task itself.

2022-01-25 22:27 UTC, stuaxo requested changes
Looking good so far, with a few tweaks todo.

2022-01-26 10:10 UTC, gabelton commented on exporter/tasks.py
> +        workbaskets = WorkBasket.objects.is_approved().filter(id__in=workbasket_ids)
I was unsure on this one because `is_approved` allows for workbaskets with SENT, PUBLISHED, and ERRORED status. I needed to access PUBLISHED. Maybe it would be worth adding another method to WorkBasketQueryset that doesn't include the ERRORED status?

2022-01-26 11:07 UTC, simonwo commented on exporter/tasks.py
> +        workbaskets = WorkBasket.objects.is_approved().filter(id__in=workbasket_ids)
The answer might actually be that `ERRORED` should not be in `is_approved` or that we have a different method like `is_current` or something like that? Basically `ERRORED` data should be treated as not visible to the rest of the system?

2022-01-26 11:09 UTC, simonwo commented on workbaskets/jinja2/includes/workbaskets/workbasket-selectable-items.jinja
> +          "We've created an envelope which contains your published changes between {{ "{:%d %b %Y}".format(approved_dates.start) }} and {{ "{:%d %b %Y}".format(approved_dates.end) }}. It's ready for
Can we not have the quotes around the test?

2022-01-26 11:12 UTC, simonwo commented on workbaskets/views/__init__.py
> +    Creates lambda function for sorting s3 objects by `last_modified` attribute.
I agree that this idea sounds like it will be easier to scale into letting TMs download other (not the most recent) envelopes later.

2022-01-26 16:07 UTC, gabelton commented on workbaskets/views/__init__.py
> +            ] = "attachment; filename=" + os.path.basename(last_added.key)
Actually I've just realised that I can redirect to the bucket. Do you know how to trigger download from that redirect? I thought I could just add the download attribute in the <a> tag. At the moment I'm seeing this view :

<img width="1360" alt="Screenshot 2022-01-26 at 16 01 29" src="https://user-images.githubusercontent.com/46938749/151200387-d9adfb8c-b888-4477-9fe7-aad729646b64.png">

2022-01-26 16:21 UTC, gabelton commented on workbaskets/views/__init__.py
> +        upload.delay()
I was looking for a way to update upload_workbaskets, so as to pass in the workbasket_ids kwarg to the first task, but couldn't find a way to do this.

2022-01-26 17:55 UTC, stuaxo commented on exporter/tasks.py
> +        workbaskets = WorkBasket.objects.is_approved().filter(id__in=workbasket_ids)
In that case it sounds like we really just want `(status=WorkflowStatus.APPROVED)`.

SENT is later in `upload_and_create_envelopes` so we shouldn't' be resending these, we shouldn't be resending PUBLISHED - as in theory that would get sent at the end of this process, though I can't seem to find it - maybe it went when we removed the code that automatically triggers the upload task ?

2022-01-26 17:57 UTC, stuaxo commented on workbaskets/views/__init__.py
> +            ] = "attachment; filename=" + os.path.basename(last_added.key)
I realised after that, you could probably just have an ordinary link to the bucket.

If the browser complains then we may need to add cross-domain rule to get it working.

2022-01-26 17:58 UTC, stuaxo commented on workbaskets/views/__init__.py
> +        upload.delay()
We can pair on this, sometimes it's not 100% intuitive, which things should be tasks vs which should just be functions.

2022-01-27 10:40 UTC, simonwo commented on workbaskets/views/__init__.py
> +            ] = "attachment; filename=" + os.path.basename(last_added.key)
http://iwantmyreal.name/s3-download-only-presigned-upload

You might be able to add the content disposition header as metadata?

2022-01-28 14:08 UTC, gabelton commented on exporter/tasks.py
> +        workbaskets = WorkBasket.objects.is_approved().filter(id__in=workbasket_ids)
I don't think we'd be resending PUBLISHED in this current workflow. I think currently once the user clicks "submit all changes" the workbasket becomes PUBLISHED and I wanted to send the envelope at that same stage, which I needed is_approved for

2022-02-04 09:49 UTC, simonwo commented on common/views.py
> +        return WorkBasket.objects.is_approved().last()
I'm guessing these are sorted by primary key – is there any possibility we might need to order by e.g. created time instead?

2022-02-04 09:49 UTC, simonwo commented on common/views.py
> +        return Upload.objects.count() > 0
Does the message need to disappear whilst a workbasket is being generated? E.g. should we be filtering the Upload to just the last_approved_workbasket?

2022-02-04 09:49 UTC, simonwo commented on exporter/storages.py
> +        return super().get_object_parameters(name)
👌

2022-02-04 09:49 UTC, simonwo commented on exporter/tasks.py
> +
Does it definitely need to take specific IDs? Orginally when this was built the idea was that it would just upload "any workbaskets that are ready to send". Our assumption is that it'd be only one at a time until we build more task features. So is this necessary? Or could we stick with just "upload any that are ready"?

2022-02-04 09:49 UTC, simonwo commented on workbaskets/jinja2/includes/workbaskets/workbasket-selectable-items.jinja
> +          This is a place holder for help text about tariff managers' actions and/or next steps
Looks like we need to fill this out… something to bring up with PM?

2022-02-04 16:34 UTC, gabelton commented on common/views.py
> +        return WorkBasket.objects.is_approved().last()
I was forgetting that WorkBasket has a created_at field. Updated to order_by this

2022-02-04 16:58 UTC, gabelton commented on exporter/tasks.py
> +
I can't remember why I did it this way now... I think I was imagining that loads could end up being sent, forgetting that the status gets set to SENT, so there would only ever be one sent with the way we have it setup currently. I don't know why I needed is_approved even because I should only have been sending an approved basket not PUBLISHED ?

Long way of saying: I think you're right and we shouldn't need this.

2022-02-04 17:08 UTC, gabelton commented on common/views.py
> +        return Upload.objects.count() > 0
Could we possibly have a quick call at some point next week to discuss the workflow logic? I think I need to write down exactly when the WorkBasket is meant to change states in this workflow and what the user should be seeing in terms of download options at each point

2022-02-06 14:27 UTC, SteveCN7 commented on workbaskets/jinja2/includes/workbaskets/workbasket-selectable-items.jinja
> +          This is a place holder for help text about tariff managers' actions and/or next steps
Definitely worth a quick passover with a content person.

2022-02-07 10:07 UTC, simonwo commented on workbaskets/jinja2/includes/workbaskets/workbasket-selectable-items.jinja
> +          This is a place holder for help text about tariff managers' actions and/or next steps
Or if we don't have anything to put here, we can just remove this and not block the PR.

2022-02-07 10:54 UTC, SteveCN7 commented on workbaskets/jinja2/includes/workbaskets/workbasket-selectable-items.jinja
> +          This is a place holder for help text about tariff managers' actions and/or next steps
I can accept that - would be good to be clear this - I want to do a full content review of the pages at sometime

2022-02-08 17:26 UTC, simonwo commented on exporter/management/commands/quota_export.py
> +from collections import defaultdict
Did you mean to commit this?

2022-02-09 11:01 UTC, simonwo approved these changes

2022-02-09 11:01 UTC, simonwo commented on workbaskets/views/__init__.py
> +    )
Do we gain anything by referring to the `HMRCStorage` instead of setting this up manually?
https://github.com/uktrade/tamato/blob/74381ac3dfa2542c4d539939d01a342011b3453a/exporter/storages.py#L9

2022-02-09 14:38 UTC, merged