TP2000-411 ON10 doesn't support creating an origin for a later period
uktrade/tamato pull request #634
Opened 2022-07-28 16:04 UTC by gabelton

# TP2000-411 ON10 doesn't support creating an origin for a later period 

## Why

We want to be able to end date a measure with a quota attached. We then want to be able to copy that measure for a later start date with different exclusions. Our current implementation of ON10 and ME119 prevents this because they see the origins / measures for a later period as not contained by the origins / measures for the earlier period. Each measure should be contained by one origin, but not by every origin.

## What

Update ON10 and ME119 to reflect above logic and add scenario tests for both.

2022-08-02 07:58 UTC, simonwo commented on measures/business_rules.py
> +        contained by more than one origin.
Does b) hold for all historical data too? Or does this rule need a "not before" property on it?

2022-08-02 07:58 UTC, simonwo commented on measures/business_rules.py
>              )
If you wanted to, you could also use `measure.follow_path("order_number__origins")`

2022-08-02 07:58 UTC, simonwo commented on measures/tests/test_business_rules.py
> +    ON10(later_origin.transaction).validate(later_origin)
Should this be in the quotas business rule test file?

2022-08-02 07:58 UTC, simonwo commented on quotas/business_rules.py
> +            if self.violating_models(model).exists() and not self.valid_origin(model):
What does `valid_origin` check for? It seems to return `True` if any of the measures on the origin is contained by it? So I think this is finding origins that don't contain all of their measures and excluding any that don't contain any measures? What about if origin X contains measure A and origin Y contains measure B, but they don't overlap with each other? Won't `valid_origin` return `True` for that and it'll still fail?

2022-08-02 11:38 UTC, gabelton commented on measures/business_rules.py
> +        contained by more than one origin.
It's got `@only_applicable_after("2007-12-31")`, but I'm running a script now to check if that's the right date or if there are exceptions

2022-08-02 13:46 UTC, gabelton commented on measures/tests/test_business_rules.py
> +    ON10(later_origin.transaction).validate(later_origin)
I guess it tests both ON10 and ME119 and could go in either. Or did you mean that I should have the same test in both files?

2022-08-02 13:57 UTC, gabelton commented on measures/business_rules.py
>              )
I think maybe this rule was buggy before because, when l checked the output of follow_path, it was returning the GeographicalArea objects rather than the QuotaOrderNumberOrigin objects themselves

2022-08-05 09:06 UTC, simonwo requested changes

2022-08-05 09:06 UTC, simonwo commented on measures/business_rules.py
> +                    raise self.violation(measure)
This looks like ajob for `sets`. E.g. put these things into a set by doing `area_sids = area_sids & …` and then comapre them with `if any(area_sids - origin_sids):`

2022-08-05 09:06 UTC, simonwo commented on measures/tests/test_business_rules.py
> +    ON10(later_origin.transaction).validate(later_origin)
I guess I'm saying that importing business rules from the quotas module as part of measure tests feels unhygenic and is tying the modules closer together… the tests should be testing things in their own module only?

2022-08-05 09:06 UTC, simonwo commented on quotas/business_rules.py
> +                    raise self.violation(order_number_origin)
This doesn't look quite right, because you raise that the violation is with `order_number_origin` even if a different origin was at fault.

But anyway, you are checking all of the origins on the measure. You should only be checking `order_number_origin` because that was the one passed into the rule. So I don't think you need the origins loop – just check the one origin against all the measures. The reason why is that this rule will only be called if the origin itself has changed – so checking all the other origins is redundant as they haven't changed. ME119 exists to do this the other way around for when the measure changes.

2022-08-05 09:06 UTC, simonwo commented on quotas/tests/test_business_rules.py
> +    ME119(later_origin.transaction).validate(measure)
Again, I think it's bad for circular referencing that we are importing stuff from measures into the quotas module. `measures` is dependent on `quotas` because a measure contains a quota, but that other way around is not true. So 'quotas' module should not be depending on 'measures'.

2022-08-08 17:01 UTC, gabelton commented on quotas/business_rules.py
> +                    raise self.violation(order_number_origin)
This entire rule now seems unnecessary to me. I want to be able to create an order number origin that spans a new time period, one not yet covered by any measures. In that scenario, if I just loop over the measures, not the origins, `contained_count` will be 0. ME119 takes care of the scenario where a measure is created with a quota order number but no origin and ON5 covers me against overlapping origins for the same quota.

2022-08-09 08:30 UTC, simonwo commented on quotas/business_rules.py
> +                    raise self.violation(order_number_origin)
I guess the rule is mainly here for if the origin date gets updated, and then no longer spans the measures it used to span. How to handle that one is indeed tricky. Maybe you do need this rule, but instead you just loop over the measures and call ME119 on each of them??

2022-08-09 09:06 UTC, gabelton commented on measures/business_rules.py
>      container_field_name = "order_number__quotaordernumberorigin"
I've removed it because it was returning the geo areas, rather than the origins themselves

2022-08-16 10:01 UTC, simonwo approved these changes

2022-08-17 08:01 UTC, merged