TP2000-513: Rule violations sorting
uktrade/tamato pull request #685
Opened 2022-09-20 10:41 UTC by eadpearce

# TP2000-513: Rule violations sorting

## Why

* We want users to be able to sort by certain fields in the rule violations list view

## What

* Adds clickable sort icons to columns on the violations page to sort by that field
* Clicking the sort icon/column heading a second time will toggle the sort order between ascending/descending

<img width="1184" alt="Screenshot 2022-09-20 at 11 37 46" src="https://user-images.githubusercontent.com/25905279/191236846-adcd6351-6e7c-49b9-8886-5fe9090b606d.png">

## Checklist
- Requires migrations? No
- Requires dependency updates? No

2022-09-20 16:55 UTC, paulpepper-trade requested changes

2022-09-20 16:55 UTC, paulpepper-trade commented on common/jinja2/components/sort_icon.jinja
> +<svg width="20" height="19" viewBox="0 0 20 19" fill="none" xmlns="http://www.w3.org/2000/svg">
Would this be better located in a .svg file - akin to keeping CSS in stylesheets. I think [our webpack bundling](https://github.com/uktrade/tamato/blob/1be2498a2ea094b9fad04f8b26b5d6b208bb3bc0/webpack.config.js#L36) should handle that.

2022-09-20 16:55 UTC, paulpepper-trade commented on workbaskets/jinja2/workbaskets/violations.jinja
> +{% macro sort_by(sort_by, title) %}
Indentation to help with readability?

2022-09-20 16:55 UTC, paulpepper-trade commented on workbaskets/views/ui.py
> +        direction = self.request.GET.get("d")
For readability and to self-doc this param, perhaps name it "direction" or "order".

2022-09-20 16:55 UTC, paulpepper-trade commented on workbaskets/views/ui.py
> +                qs = qs.order_by(sort_by)
Won't this 500 error if a non-sortable attribute value is given (unvalidated input)?

2022-09-21 10:17 UTC, eadpearce commented on workbaskets/views/ui.py
> +                qs = qs.order_by(sort_by)
no `if sort_by and sort_by in sort_by_fields:`. there is a test for this too

2022-09-21 10:39 UTC, paulpepper-trade approved these changes

2022-09-21 11:02 UTC, merged