Measure tweaks and UKGT import script
uktrade/tamato pull request #70
Opened 2020-09-23 13:55 UTC by simonwo

-  Make measurement unit qualifiers optional.
- Serializers for measures and associated models.
- Store abbreviations and prefixes for duty sentence objects
- Duty expression IDs should be integers
- Include national measurement units which can be numeric.
- Parser for duty sentences
- Set a default community code for regulations
- Split out envelope start and end for composition
- Script for importing sheets of reference data
- Script for importing the UKGT
- Allow measure and transaction IDs to be started from anywhere.

2020-09-23 16:09 UTC, stuaxo approved these changes
Wow, there is a lot here !

2020-10-12 16:35 UTC, stuaxo commented
I guess going via XLSX has some advantages over CSV, in that you don't need to worry about what kind of delimiter is used etc  OTOH, it adds extra complexity.

If this stuck with CSV you might be able to just use postgres COPY for both input and output of the database.

2020-10-13 08:52 UTC, simonwo commented
For the `import_sheet` stuff, yeah we could probably have used CSV. The main reason I went with XLSX was that we're already consuming XLSX from policy teams for all of the other stuff so thought I'd stick with the pattern already established for that.

2020-10-13 08:53 UTC, simonwo commented
Also I guess I wanted to put it through the models to make sure everything validates.

2020-10-13 09:34 UTC, stuaxo commented
I probably should have written that in future tense, not past-tense.

It may be good to make this also work with CSV in the future, to simplify the workflow of export TAP->import TaMaTo,

2020-10-23 09:37 UTC, stuaxo approved these changes

2020-10-26 11:30 UTC, andyhd reviewed
I haven't read through all the code yet, but here are my comments so far

2020-10-26 11:35 UTC, andyhd commented on importer/management/commands/import_sheet.py
> +                instance.full_clean()
This is on line 253 now https://github.com/uktrade/tamato/pull/70/files#diff-a8b47d049487d1bc49a6b10426ef2e72fa3a4afc30514a6c49ee4e8fe24b4bf4R253

2020-10-26 11:49 UTC, stuaxo commented on importer/duty_sentence_parser.py
> +Amount = float
(If I could give more than one thumbup for this I would)

2020-10-26 15:32 UTC, NDevox requested changes
Lots to digest here!

I have a couple recurring themes and one thought on where this is going.

1) There is some weird stuff going on with typing here. Lots of casting and, in some cases, classes inheriting from types. Neither make sense in python really - casting does absolutely nothing (might help your IDE linter, but nothing else and that will be IDE specific). Inheriting from types suggests that the classes you are making are intended for type hinting, but that's clearly not the case. So that looks relatively confusing and probably needs to be cleaned up.

2) Lots of asserts. This is generally not done in python outside of testing. The logic I've seen is that asserts should only really be used for corrupt states (i.e. something you would never expect to actually happen). If the problem is a possibility you should define your own errors and raise those. It's worth keeping in mind that it is possible to run python in a way that completely silents all asserts and they're generally taken less seriously than standard exceptions (which are also more explicit).

My other main thought is how we're using this compared to the nursery/import handler system. This does feel a lot like we're duplicating logic and creating multiple competing systems to do the same thing, when surely we should be letting them work together? The nursery/handler system is designed to be input agnostic, it only wants a structured dictionary with the data to work. And from there it will run all the logic to collect the actual DB objects and combine them.

That said I can't actually see where anything is saved to the DB (with the exception of indents). It looks like, for the most part, everything is written to XML instead, I guess to be imported through the importer later?

2020-10-26 15:32 UTC, NDevox commented on importer/management/commands/import_suspensions.py
> +        yield list(
Do we really want to `yield` here? Why not `return`?

2020-10-26 15:32 UTC, NDevox commented on importer/management/commands/utils.py
> +def clean_item_id(cell: Cell) -> str:
This duplicates code above in the commit, should replace it

2020-10-26 15:32 UTC, NDevox commented on importer/management/commands/utils.py
> +                        .get()
replace `filter` with `get`

2020-10-26 15:32 UTC, NDevox commented on importer/management/commands/utils.py
> +                .get()
replace `filter` with `get`

2020-10-26 15:49 UTC, andyhd commented on importer/management/commands/import_suspensions.py
> +        footnote_ids = set(*[r.footnotes for r in matched_old_rows])
or the `[]`

2020-10-26 16:49 UTC, andyhd requested changes

2020-10-26 16:49 UTC, andyhd commented on common/tests/util.py
> +                    ), f"Elements out of order in XML: {full_code} came after {last_code}"
Should this be `full_code >= last_code`?

2020-11-06 20:07 UTC, simonwo commented on common/tests/util.py
> +                    ), f"Elements out of order in XML: {full_code} came after {last_code}"
@kristof-bb has fixed this.

2020-11-06 20:09 UTC, simonwo commented on importer/management/commands/doc_importer.py
> +            Measurement.objects.as_at(forward_time)
Apparently this caused @kristof-bb to get no measurements. This maybe an artifact of the sheets importer. Suggest we leave as is and revisit later.

2020-11-06 20:09 UTC, simonwo commented on importer/management/commands/doc_importer.py
> +        return iter([])
@kristof-bb has correctly replaced them with `@abstractmethod`.

2020-11-06 20:39 UTC, simonwo commented on importer/management/commands/import_sheet.py
> +Transformer = Callable[[Any], Any]
No – [the indicies on `Callable` specify first the arguments and then the return type](https://docs.python.org/3/library/typing.html#typing.Callable). So `Transformer` is anything that matches:

    def func(x: Any) -> Any:
      return …

Not that helpful other than it's a function of 1 argument.

2020-11-06 20:40 UTC, simonwo commented on importer/management/commands/import_sheet.py
> +        num_rows = 0
If `worksheet.get_rows()` return zero values then num_rows is undefined.

2020-11-06 20:44 UTC, simonwo commented on importer/management/commands/import_ukgt.py
> +            str(a.type.sid + a.code): a
Yes, but this does help the type system understand the type of the dict.

2020-11-06 21:27 UTC, simonwo commented on importer/duty_sentence_parser.py
> +        # followed optionally by a decimal point and a number of digits (we have seen
Yep, I've moved them all to module scope.

2020-11-06 21:30 UTC, simonwo commented on importer/management/commands/doc_importer.py
> +class RowsImporter(Generic[OldRow, NewRow]):
This is (apparently) [how `Generic` is meant to be used](https://docs.python.org/3/library/typing.html#typing.Generic). `Generic` becomes a parent type of the class and type checkers recognise this as it being customisable with the passed `TypeVars`.

2020-11-06 21:30 UTC, simonwo commented on importer/management/commands/doc_importer.py
> +        else:
@kristof-bb fixed this.

2020-11-06 21:31 UTC, simonwo commented on importer/management/commands/doc_importer.py
> +        with django.db.transaction.atomic():
@kristof-bb fixed this.

2020-11-06 21:31 UTC, simonwo commented on importer/management/commands/doc_importer.py
> +            while new_row or old_row:
Thanks – we've removed this anyway!

2020-11-06 21:34 UTC, simonwo commented on importer/management/commands/doc_importer.py
> +                    new_row = None
I'm not sure… the point of this bit is that we don't move the two iterators in tandem with each other. We only consume from an iterator if it is behind or equal with the other iterator. So we can't consume both rows at once… we may take them independently of each other.

2020-11-06 21:34 UTC, simonwo commented on importer/management/commands/import_countries.py
> +import settings
@kristof-bb fixed this.

2020-11-06 21:36 UTC, simonwo commented on importer/management/commands/import_countries.py
> +            area = cast(GeographicalArea, area)
Indeed, it's just for the type checker. Fair enough. Personally I've got a lot of value out of the system knowing what types things are, and (for me at least) Django code isn't sufficiently typed to allow the type checker to understand what comes out. But maybe there's a different configuration that would make that work?

2020-11-06 21:37 UTC, simonwo commented on importer/management/commands/import_countries.py
> +                    env.render_transaction([model])
Yes – it only outputs XML.

2020-11-06 21:38 UTC, simonwo commented on importer/management/commands/import_gsp.py
> +            self.item_id += "00"
I'm not smart enough to understand your snippet! I guess I don't know enough about the string formatting options. In any case, I'd probably rather know if the thing is less than 8 digits at this point with an error.

2020-11-06 21:40 UTC, simonwo commented on importer/management/commands/import_gsp.py
> +        self.old_rows = NomenclatureTreeCollector[List[OldMeasureRow]](BREXIT)
Indeed it's pretty weird! Apparently using `Generic` as a parent class also causes the class to become subscriptable and allows you to declare the types that you want to use in the type slots.

2020-11-06 21:46 UTC, simonwo commented on importer/management/commands/import_gsp.py
> +                    .all(),
It works as intended! I thought `all()` just got all the results into a list from whatever `QuerySet` it is called on?

2020-11-06 21:48 UTC, simonwo commented on importer/management/commands/patterns.py
> +            yield
Yes – it's odd, but it's using yield as a signalling mechnaism. The calling method needs to call `flush` each time that the method yields. It might yield from 0 to 2 times depending on what is in the buffer and what rows are passed in.

2020-11-06 21:49 UTC, simonwo commented on importer/management/commands/utils.py
> +def blank(value: Any, convert: Callable[[Any], TypeVar("T")]) -> Optional[TypeVar("T")]:
They are similar, but one is designed for the sheets system whereas the other is for general importers. I don't think there's much mileage in combining them.

2020-11-11 14:10 UTC, andyhd commented on common/jinja2/common/taric/base.xml
> +{% include "common/taric/start_file.xml" %}
Not sure what this change gains, because the `<?xml>` tag is about the same length as the `{% include %}`, so you're better off inlining it.

2020-11-12 11:15 UTC, simonwo commented on common/jinja2/common/taric/base.xml
> +{% include "common/taric/start_file.xml" %}
I think @kristof-bb made this change to allow us to generate multiple envelopes in a single file? And then they are split later?

2020-11-12 11:16 UTC, simonwo commented on requirements-dev.txt
> +xmldiff
I think this needs to move into `requirements.txt` to be used in tests.

2020-11-12 12:05 UTC, andyhd commented on common/jinja2/common/taric/base.xml
> +{% include "common/taric/start_file.xml" %}
Never mind, I didn't immediately get that the templates were deliberately split to allow streaming.

2020-11-12 12:08 UTC, andyhd commented on importer/management/commands/import_ukgt.py
> +            str(a.type.sid + a.code): a
Probably better to use `f"{a.type.sid}{a.code}"`

2020-11-12 12:15 UTC, andyhd approved these changes
This PR is too big and too old. It should really be split into smaller, more cohesive PRs, but I think it is probably more expedient to merge it and keep subsequent PRs small.

2020-11-17 19:51 UTC, simonwo commented
We have discussed this on Teams and there was a decision to merge this and deal with the tech debt later.

2020-11-17 19:52 UTC, merged