TP-272: Implement importer for Goods Nomenclature and Indents.
uktrade/tamato pull request #71
Opened 2020-09-23 16:05 UTC by NDevox

It is a requirement for the project to be able to import Goods Nomenclature,
Goods Nomenclature descriptions and Indents from legacy TARIC3 XML data.

This commit introduces the import parsers and handlers for these models.
Most of the models are straightforward and follow the predefined patterns
set out in other importers. However indents, being a materialized path in the
new data models but only a pseudo materialized path in the old data models,
has some divergence.

It has been necessary to find the appropriate parent of any new indents
coming in using only the limited dataset given. To this end the following
algorithm has been used:

- If top level indent, assign indent as root with no parents.
- If 1 < indent < 6, the parent item ID can be ascertained from the given
  data, use this to find the parent indent and assign the current indent
  as its child.
- if indent >= 6, the parent item ID can not be immediately ascertained
  from the given data. Find the indent that:
    1) has an item ID starting with the first 8 chars of the current item ID.
    2) has an item ID that is less than the current item ID.
    3) has an indent level of the current one - 1.
    4) has the largest item ID of those that satisfy criteria 1-3.

There is at least one corner case not currently handled. This is where an indent
is introduced that should be the parent of a pre-existing indent. This could
reasonably be handled in the post_save method of the handler - but would require
the update system to be implemented for the append only log on Goods Nomenclature
first.

2020-09-23 16:14 UTC, stuaxo approved these changes

2020-09-24 17:57 UTC, simonwo requested changes
Sorry :(

2020-09-24 17:57 UTC, simonwo commented on commodities/import_handlers.py
> +        if indent == 1:  # This is a root indent (i.e. a chapter heading)
Have you manually nudged the indents somewhere? Because both root nodes and first level children have indent 0 in the XML.

2020-09-24 17:57 UTC, simonwo commented on commodities/import_handlers.py
> +        ):  # The indent is short enough for us to directly use the item ID to find a parent
Alas, this is sadly not strictly true 😥

Indents even as high as 4 digits have phantom parents where the item id is the same but the suffix is different:

SID | Commodity code | Suffix | Indent | HS Level | Description | Parent SID | Parent commodity code | Parent suffix | Parent indent |
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
93473 | 9905000000 | 80 | 1 | 4 | Personal property belonging to natural persons transferring their normal place of residence | 93477 | 9905000000 | 10 | 0
93474 | 9919000000 | 80 | 1 | 4 | The following goods, other than those mentioned above:<br>–- Trousseaux and household effects belonging to a person transferring his or her normal place of residence on the occasion of his or her marriage; personal property acquired by inheritance;<br>–- School outfits, educational materials and related household effects;<br>–- Coffins containing bodies, funerary urns containing the ashes of deceased persons and ornamental funerary articles;<br>–- Goods for charitable or philanthropic organisations and goods for the benefit of disaster victims. | 93477 | 9905000000 | 10 | 0

Is it not possible to use the algorithm for > 6 in all cases?

2020-09-24 17:58 UTC, simonwo commented on commodities/import_handlers.py
> +        ):  # The indent is short enough for us to directly use the item ID to find a parent
For the interested onlooker, this is because the EU have extended the Harmonised System by adding chapters that are EU specific, hence their creation of phantom codes in these places.

2020-09-24 18:20 UTC, stuaxo commented on commodities/import_handlers.py
> +        ):  # The indent is short enough for us to directly use the item ID to find a parent
I'm interested but at this stage I need someone to explain what indents are all about in this context (and probably not as a reply to this comment :))

2020-09-24 18:33 UTC, simonwo commented
Also, how much extra work is the updating importer?

2020-09-25 08:13 UTC, NDevox commented on commodities/import_handlers.py
> +        ):  # The indent is short enough for us to directly use the item ID to find a parent
Welcome to who's Commodity is it anyway!? Where the indents are made up and the codes don't even matter.

^ This about covers what you need to know @stuaxo 😉 

I may be bitter.

2020-09-25 08:16 UTC, NDevox commented on commodities/import_handlers.py
> +        ):  # The indent is short enough for us to directly use the item ID to find a parent
@simonwo I did know this, I may have blotted it out of my memory however during implementation 😞 .

I believe this means we have to use the >6 algorithm for everything as a result (given we can't trust things even at indent 2). With a slight tweak that the parent code doesn't have to be lesser than, but lesser than or equal to (wonder if that would lead to any weird corner cases?). Not a problem, makes the update need more urgent... but still not really a problem as we need to do it anyway.

2020-09-25 08:20 UTC, NDevox commented on commodities/import_handlers.py
> +        if indent == 1:  # This is a root indent (i.e. a chapter heading)
Cunningham's law in play here (semi-intentional).

I had a think about this a few weeks back and reckoned we should input indents into the system as I've intentioned here (if we don't then the tree won't be a proper tree because the roots are just too gnarly).

How we output the indents can be how you explain them (e.g. `return 0 if indent < 3 else indent - 2`).

And the importer will have to do the reverse of that to get the data in correctly (`return num_steps if indent == 0 else indent + 2`).

Do you see any issues with that?

2020-09-25 08:25 UTC, NDevox commented
I've specifically not thought about the updating importer as I've wanted to get through creation first. Creation is "easy".

Realistically we should have a common mechanism across all `TrackedModels` for updates.

e.g. we override the `save` method on `TrackedModel` which does some specific logic around whether it's an update or a create. If it's an update we implement the AO logic.

Once that is done I reckon updating will be almost no different than create (but it would have the added step of finding the pre-existing object).

2020-09-25 08:27 UTC, NDevox commented
i.e. I don't think it's an importer job as much as it is a whole project job.

@simonwo

2020-09-25 08:27 UTC, stuaxo commented on commodities/import_handlers.py
> +        ):  # The indent is short enough for us to directly use the item ID to find a parent
This diagram makes a little more sense on a laptop vs a phone :)

2020-09-25 08:34 UTC, simonwo commented on commodities/import_handlers.py
> +        ):  # The indent is short enough for us to directly use the item ID to find a parent
It will also need to have suffix >= parent I believe

2020-09-25 08:38 UTC, simonwo commented on commodities/import_handlers.py
> +        if indent == 1:  # This is a root indent (i.e. a chapter heading)
I think that makes sense? Just so long as we’re not expecting it to be right in the XML!

The code I’ve used elsewhere has checked if it’s a 2-digit code and just assumed the indent as -1, which gets the ordering correct and doesn’t require anything more complicated for the children.

2020-09-25 14:01 UTC, NDevox commented on commodities/import_handlers.py
> +        ):  # The indent is short enough for us to directly use the item ID to find a parent
Not convinced suffix is needed.

Surely it's just indent above and code is less than or equal to? Or will we get two goods with the same code at the same level with different suffixes, as well as another good one indent down with the same code? i.e. 3 goods with the same code spread across just 2 levels?

2020-09-25 14:01 UTC, NDevox commented on commodities/import_handlers.py
> +        if indent == 1:  # This is a root indent (i.e. a chapter heading)
I've updated to handle this.

2020-09-25 14:02 UTC, NDevox commented on commodities/import_handlers.py
> +        ):  # The indent is short enough for us to directly use the item ID to find a parent
I've updated to handle the above. Negative point from this is that the `check_indent` method can't really be done anymore as we can't base any assumptions on the code at all.

2020-10-02 07:20 UTC, simonwo commented on commodities/import_handlers.py
> +            ).current(),
I've tried out
```python
parent = GoodsNomenclatureIndent.objects.filter(
     indented_goods_nomenclature__item_id__lte=item_id,
     indented_goods_nomenclature__valid_between__contains=(new_row.start_date, new_row.start_date),
     valid_between__contains=(new_row.start_date, new_row.start_date),
     depth=parent_indent,
).order_by('indented_goods_nomenclature__item_id').reverse()[0]
```
and it seems to do the correct job, but that might assume that you're doing the end-dating described in the other comment and that parents are always guaranteed to be before children. What do you think?

2020-10-02 08:17 UTC, NDevox commented on commodities/import_handlers.py
> +                indented_goods_nomenclature__item_id__startswith=trimmed_id,
Hmmmm. You raise a very good point.

I like the idea of doing it because it should be slightly more performant and a bit less error prone. The alternative raises the possibility of getting _every_ comm code including ones which blatantly shouldn't be parents (e.g. ones under completely different chapters). So I would like to have it. I guess the question is how far back do we need to trim to have confidence in it?

2020-10-02 08:20 UTC, NDevox commented on commodities/import_handlers.py
> +        return parent.add_child(**data)
I'm not sure what the issue is with having a null end date? if we don't have an end date provided then it is effectively seen as null. Until we are provided an end date.

2020-10-02 08:20 UTC, NDevox commented on commodities/import_handlers.py
> +            ).current(),
This situation would be an update in this case would it not? so wouldn't fall under the current creation scheme and would have different logic applied (especially to children).

I do think we should add validity dates as part of the query though, that makes a lot of sense.

2020-10-02 08:22 UTC, NDevox commented on commodities/import_handlers.py
> +        return parent.add_child(**data)
Oh wait are you talking about when we get an update?

This is the same as anything else with a valid_between field, going by the AO log idea we can't directly update the row with an end date. We're going to have to do some magic around introducing a new row with a start and end date and figure out a query that gives us that one instead of the other (I can see this being done with a dense rank...)

2020-10-02 08:45 UTC, simonwo commented on commodities/import_handlers.py
> +        return parent.add_child(**data)
I guess more I'm thinking about how this will actually get used… e.g. a code SID can have many indents over it's lifespan, so how do we pick the correct one when we're doing a query? When we want to know what the parent or children of a code is/are, we need to specify a point in time so that the correct indents get picked up. If we have the end date, we can just use `my_goods_nomenclature.indents.as_at(…).get()` and then go from there. But if we don't have the end date set, we'll have to use some sort of `SELECT MAX(valid_between)…` or something, which we were trying to avoid?

2020-10-02 08:48 UTC, simonwo commented on commodities/import_handlers.py
> +                indented_goods_nomenclature__item_id__startswith=trimmed_id,
I think it's basically the same issue [as above](https://github.com/uktrade/tamato/pull/71#discussion_r494504143) i.e. you can't really rely on them even at the highest levels. You could probably limit it to the first two digits safely, but not sure how much impact that makes!

2020-10-02 09:09 UTC, NDevox commented on commodities/import_handlers.py
> +        return parent.add_child(**data)
I agree with this entirely. But this is unavoidable without disregarding the AO log isn't it?

2020-10-02 09:10 UTC, NDevox commented on commodities/import_handlers.py
> +                indented_goods_nomenclature__item_id__startswith=trimmed_id,
😬  This makes me uncomfortable. But guess we can remove.

2020-10-02 10:19 UTC, stuaxo commented on commodities/import_handlers.py
> +                indented_goods_nomenclature__item_id__startswith=trimmed_id,
These hierarchical IDs look like just thing for a TRIE, I think Postgres has support, I wonder if anyone every plumbed it up into django.

2020-10-02 11:02 UTC, NDevox commented on commodities/import_handlers.py
> +                indented_goods_nomenclature__item_id__startswith=trimmed_id,
They kind of are a TRIE - but the legacy system has so many caveats and exceptions that it just kinda breaksdown eventually. Which is more or less why we've taken a step back and applied MP structure with treebeard to the indents - so that the indents can follow a proper TRIE structure (I think I'm right in assuming MP nodes follow a TRIE architecture).

Annoyingly whilst the item IDs look like they should have been what we use for this, the mis(ab)use of them in the TARIC has made it virtually impossible

2020-10-02 13:53 UTC, stuaxo commented on commodities/import_handlers.py
> +                indented_goods_nomenclature__item_id__startswith=trimmed_id,
Later on it'll be worth seeing if different types of Postgres index are worth it, they've got SP-GiST with Radix Tree seems pretty tree like + might have a benefit, it doesn't matter that the hierarchy aren't a tree.

2020-10-09 13:23 UTC, NDevox commented on commodities/import_handlers.py
> +            ).current(),
Added validity dates

2020-10-09 13:23 UTC, NDevox commented on commodities/import_handlers.py
> +                indented_goods_nomenclature__item_id__startswith=trimmed_id,
I've reduced this to just the chapter heading now.

2020-10-09 16:56 UTC, simonwo commented
So I've done lots of thinking about indents in the process of writing the importers because I've needed a good understanding of the nomenclature hierarchy to prevent ME32 errors from occuring. As a result, I think I've understood how indents really work, and what we need to do to get a proper tree of them.

Here's a list of things that are True Facts:

- The indent records the time the goods nomenclature is at the given depth in the hierarchy.
- The indent is correct for as long the code is at that depth. What happens _above_ that code is irrelevant – if the code receives a new parent but the depth remains the same, there is no new indent.
- In our tree model, each indent model has a specific parent for all time. This is in contrast to the above.
- So one indent in TARIC3 actually maps to multiple indents in TaMaTo – each time the indent gets a new parent, we need a new TaMaTo tree node.

A good exmaple of this is 0304909700/80 at depth 4, represented by a single indent in TARIC3 even though:
- parent is 0304902100/10 between 1994 and 1996, when that code ends
- parent is 0304902000/10 between 1996 and 2001, when that code ends
- parent is 0304902200/10 between 2001 and 2007, when the indented code ends

What this means is that we will have multiple `GoodsNomenclatureIndent` models with the same `sid` but different validity periods and parents. The alternative is to not use the tree model and just record the indents as is, and do the resolution of the tree at use-time. I think our way is still better (so much easier to use!) but requires careful importing and creating up front.

I've taken the code you did here and implemented it as [a spreadsheet importer](https://github.com/uktrade/tamato/blob/ukgt-import/importer/management/commands/import_indents.py#L47) which is not bad but has some niggles. The version in this PR will I think only capture one of the parents for the indent whereas we definitely need to find all of them. Feels like we should update the version here to do that, if you can stomach that after a week away from this!

________

This doesn't really impact whether to populate the end-date on the indent – that's still trading off convenience for potentially breaking or at least complicating our append-only log concept (because upon creating a new indent we'd have to go back to potentially many other indents and update their end and start times). But the alternative is we'd have to do that `MAX(…)` query whenever we wanted to use anything indent related (so that we got the right indent for the time period under question), and I think we're going to need the hierarchy in an easy to use manner for lots of use cases. But I'm open to being convinced the append-only log is more important.

One solution we could do is have some data on each `TrackedModel` instance which indicates the fields that are append-only (or those that are not, as that's less common). And then the system will not allow you to update fields that are append-only but will allow you to update the others, and will only emit XML for the former. We should ensure that only fields that are TaMaTo-specific (i.e. do not appear in TARIC XML) appear as "modifiable fields". But there might be better ideas.

I suggest we take this discussion elsewhere (around an ADR, maybe?) and implement some solution in a later PR.

2020-10-12 12:57 UTC, simonwo approved these changes
We've discussed and we're going to make some more changes in a future PR.

2020-10-12 13:24 UTC, merged