fix for ON12 not allowing origin to be removed, even if no measures are attached
uktrade/tamato pull request #722
Opened 2022-11-15 13:10 UTC by dougmills-DIT

# TOPS-824 - cant remove the required origin from order number, which has no measures attached. 

The rule states : The quota order number origin cannot be deleted if it is used in a measure.

## Why
 * Rule would reject removal if any measures existed on the order, without checking specific measures for the geographical area

## What
* Updated rule, added test

Links to relevant material
See: https://uktrade.atlassian.net/browse/TOPS-824

2022-11-16 18:30 UTC, paulpepper-trade requested changes

2022-11-16 18:30 UTC, paulpepper-trade commented on quotas/business_rules.py
> +        on_query = m_query.filter(
`order_numbers` in place of `on_query`?

2022-11-17 08:29 UTC, dougmills-DIT commented on quotas/business_rules.py
> +        )
There are issues referencing ORM objects in business rules. It raises an exception relating to partially loaded classes.  I could not see an example where direct calls to ORM classes are used in this file.

2022-11-17 08:32 UTC, dougmills-DIT commented on quotas/tests/test_business_rules.py
> +    assert business_rules.ON12(deleted.transaction).validate(deleted) is None
sure, can remove, wanted to be consistant about asserts in each test - but if its fine not to i can remove

2022-11-17 08:36 UTC, dougmills-DIT commented on quotas/business_rules.py
> +        )
exact error : ImportError: cannot import name 'Measure' from partially initialized module 'measures.models' (most likely due to a circular import) (/Users/dougmills/PycharmProjects/tamato/measures/models.py)

2022-11-17 08:38 UTC, dougmills-DIT commented on quotas/business_rules.py
> +                    "measure."
good spot! done

2022-11-17 09:55 UTC, dougmills-DIT commented on quotas/business_rules.py
> +        )
Good shout, thanks. Updated

2022-11-17 10:02 UTC, gabelton commented
Does the rule only get called when an origin is being deleted? Should it have the `skip_when_not_deleted` decorator?

2022-11-17 10:03 UTC, paulpepper-trade requested changes

2022-11-17 10:03 UTC, paulpepper-trade commented on quotas/business_rules.py
> +        )
A comment around this section is showing as resolved, but the code looks unchanged with no response. I think the suggested change was this:
```suggestion
        order_numbers = measures.filter(
            geographical_area=order_number_origin.geographical_area,
            order_number=order_number_origin.order_number,
        )
```

2022-11-17 10:05 UTC, paulpepper-trade commented on quotas/business_rules.py
> +        )
... but Gabe's question about filtering by SID is also relevant.

2022-11-17 10:08 UTC, paulpepper-trade commented on quotas/business_rules.py
> +                    "measure."
I don't see the change reflected in the source code, unless you've yet to push the change?

2022-11-17 10:09 UTC, dougmills-DIT commented on quotas/business_rules.py
> +        )
I am going to favour the SID update, since it has potential for a wider catchment

2022-11-17 11:27 UTC, dougmills-DIT commented on quotas/business_rules.py
> +        )
ok - getting to SID is erroring. Not sure why - falling back to object (which under the hood i expect goes on PK anyway)

2022-11-17 11:29 UTC, dougmills-DIT commented on quotas/business_rules.py
> +        )
ok worked it out - referencing SID working now

2022-11-17 11:30 UTC, dougmills-DIT commented on quotas/business_rules.py
> +            geographical_area_id=order_number_origin.geographical_area_id,
now using SID for query

2022-11-17 11:31 UTC, dougmills-DIT commented on quotas/business_rules.py
> +        )
@paulpepper-trade resolve if you are ok with this update ˆ

2022-11-17 12:10 UTC, dougmills-DIT commented on quotas/business_rules.py
> +                    "measure."
its there - not sure why didn't show - i saw old version also

2022-11-17 12:10 UTC, dougmills-DIT commented on quotas/business_rules.py
> +                    "measure."
i can see space now

2022-11-22 14:48 UTC, paulpepper-trade commented on quotas/business_rules.py
> +                    "measure."
Looks as though it's still missing the space after `" measure."`.

2022-11-22 14:49 UTC, paulpepper-trade approved these changes

2022-11-22 15:20 UTC, gabelton approved these changes

2022-11-23 08:17 UTC, merged