Tp2000 611 send wb to packaging queue
uktrade/tamato pull request #751
Opened 2022-12-19 10:03 UTC by a-gleeson

# TP2000-611 

This PR:
    - Correctly manage new form action in workbasket detail
    - Added Package workbasket create view with form 
    - Packaged workbasket create view contains appropriate error handling and State tranisition for a workbasket.
    - Correctly style rule check summary page.
    - Added an SVG provided by our UI designer.
    - Added view unit tests.

2022-12-19 11:44 UTC, gabelton commented on publishing/views.py
> +    permission_required = "workbaskets.add_workbasket"
Is this the right perm? Shouldn't it be "publishing.add_packaged_workbasket" or similar?

2022-12-19 11:44 UTC, gabelton commented on publishing/views.py
> +    def form_valid(self, form):
Might be worth a docstring and/or some comments

2022-12-19 11:44 UTC, gabelton commented on publishing/views.py
> +        """Return all items that are awaiting processing or are actively being
Is this docstring accurate?

2022-12-19 11:47 UTC, a-gleeson commented on publishing/views.py
> +    permission_required = "workbaskets.add_workbasket"
supposed to be common.tracked model I can update this thanks

2022-12-19 13:57 UTC, gabelton commented on publishing/views.py
> +    permission_required = "common.add_trackedmodel"
I'm not sure this is right either because PackagedWorkBasket doesn't inherit from TrackedModel. I think it will need to be something like "publishing.add_packagedworkbasket". Test doc string will also need updating

2022-12-19 15:44 UTC, paulpepper-trade requested changes

2022-12-19 15:44 UTC, paulpepper-trade commented on common/jinja2/layouts/form.jinja
> +  {% if page_label %}
There isn't much to structure here, but indents would still be good style.

2022-12-19 15:44 UTC, paulpepper-trade commented on publishing/jinja2/includes/warning_help.jinja
> +{{ govukWarningText({
I don't think you need a separate template with this warning. Would the GDS crispy forms library allow you to include this warning in your Layout? https://crispy-forms-gds.readthedocs.io/en/latest/components/warning.html

2022-12-19 15:44 UTC, paulpepper-trade commented on publishing/views.py
> +                reverse(
I think `redirect()` may allow you to provide the view name and args without need for `reverse()`.

2022-12-19 15:44 UTC, paulpepper-trade commented on publishing/views.py
> +    def form_valid(self, form):
There's more than one `save()` in this method. I think it may need to be decorated with `django.db.transaction.atomic` to ensure it either all succeeds or all fails.

2022-12-19 15:44 UTC, paulpepper-trade commented on publishing/views.py
> +                reverse(
Ditch the `reverse`?

2022-12-19 15:44 UTC, paulpepper-trade commented on publishing/forms.py
> +        self.request = kwargs.pop("request", None)
I know this pattern is used in other parts of TAP, but is `self.request` ever referenced by the form? if not, then it should probably be removed.

2022-12-19 15:44 UTC, paulpepper-trade commented on publishing/views.py
> +        kwargs["request"] = self.request
Needed?

2022-12-19 15:52 UTC, a-gleeson commented on publishing/jinja2/includes/warning_help.jinja
> +{{ govukWarningText({
I'll try that, was just thinking it was good to have template logic in jinja

2022-12-19 20:25 UTC, a-gleeson commented on publishing/jinja2/includes/warning_help.jinja
> +{{ govukWarningText({
Made changes although template logic is now in forms.py, is having template logic here suitable?

2022-12-20 12:07 UTC, paulpepper-trade approved these changes

2022-12-20 12:43 UTC, gabelton approved these changes

2022-12-20 12:45 UTC, merged