Tp2000 656  - Implement envelope creation, storage and retrieval from S3
uktrade/tamato pull request #786
Opened 2023-01-24 10:41 UTC by a-gleeson

# TP2000-656 - Implement envelope creation, storage and retrieval from S3

## Why
We want to upload files that we want HMRC users to download and process. 

It's necessary to:
    Implement the subsystem and task that supports creating the Envelope within the model for reporting purposes.
    Generate the xml from the packaged workbaskets transactions 
    Upload the valid xml to a file system
    Read the file system when downloading the file

## What

- updated publishing s3 environment variables for enveople & loading reports. Now in a single bucket with multiple directories
- set up s3 storage for envelope file
- added envelope model to publishing system that includes creation and deletion of envelopes
- integrated envelope creation with celery tasks
- integrated envelope file read to the download envelope view
- added tests, skipping current ones which do not work
- Updated envelope id value in hmrc envelope confirm pages
- refactored models structure to a folder
- updated intial.py migration

## Checklist
- Requires migrations? - yes
- Requires dependency updates? - no

See: [Django s3 storage](https://django-storages.readthedocs.io/en/1.13.2/backends/amazon-S3.html)

2023-01-24 19:34 UTC, paulpepper-trade requested changes

2023-01-24 19:34 UTC, paulpepper-trade commented on publishing/models/envelope.py
> +            )[0]
This looks as though it will silently throw away envelopes beyond the first one when the total size exceeds `EXPORTER_MAXIMUM_ENVELOPE_SIZE`, which will has the potential to create problems that are hard to trace.

I think a good first effort here, since we're not initially catering for multiple envelopes per workbasket, would be to impose no maximum size, and let our envelope consumer (HMRC) reject. The associated workbasket can then be reworked / decomposed into something that fits within consumer size constraints and resubmitted to the packaging queue.

Either that, or raise an exception if multiple envelopes are created. But I'm not sure what provision we have for dealing with that situation in the UI at the moment.

2023-01-24 19:34 UTC, paulpepper-trade commented on publishing/models/envelope.py
> +                raise EnvelopeNoTransactions(msg)
Do we have provision to deal with this exception in the UI?

2023-01-24 19:34 UTC, paulpepper-trade commented on publishing/models/envelope.py
> +                    logger.error(f"{envelope_file.name}  is Envelope invalid !")
Won't this allow the envelope generation failure to go unnoticed in the UI? It so, then it would be better to let the original exception bubble up or catch it, add more info, and re-raise.

2023-01-24 19:34 UTC, paulpepper-trade commented on publishing/models/packaged_workbasket.py
> -from django.db.models.functions import Coalesce
Maybe it's a matter of taste, but it may have been easier to leave these in place - it reduces the `models.` prefix clutter where these functions are used.

2023-01-24 19:34 UTC, paulpepper-trade commented on publishing/models/packaged_workbasket.py
> +            logger.info(
Good catch!

2023-01-24 19:34 UTC, paulpepper-trade commented on publishing/views.py
> +from publishing.models.state import ProcessingState
Your taste in individual imports has changed earlier^^ ;-)

2023-01-24 19:34 UTC, paulpepper-trade commented on publishing/views.py
> +        data["message"] = f" Envelope ID {envelope.envelope_id} was accepted."
Is that an unnecessary space / typo at the start of the message?

2023-01-24 19:34 UTC, paulpepper-trade commented on publishing/views.py
> +        ] = f" Envelope ID {envelope.envelope_id} was rejected and queue was paused."
Space typo?

2023-01-25 10:15 UTC, a-gleeson commented on common/tests/factories.py
> +        model = "publishing.Envelope"
added models into init as suggested

2023-01-25 10:16 UTC, a-gleeson commented on publishing/migrations/0001_initial.py
> +                        upload_to="",
migration had initially set this to blank, tested with it removed and it worked

2023-01-25 10:16 UTC, a-gleeson commented on publishing/models/envelope.py
> +            counter = 1
Implemented and tested

2023-01-25 10:16 UTC, a-gleeson commented on publishing/models/envelope.py
> +            counter = int(envelope.envelope_id[2:]) + 1
Implemented

2023-01-25 10:17 UTC, a-gleeson commented on publishing/models/envelope.py
> +            )[0]
Removed for the team being but can be raised as something we should be aware of!

2023-01-25 10:18 UTC, a-gleeson commented on publishing/views.py
> +        data["message"] = f" Envelope ID {envelope.envelope_id} was accepted."
Was for a Panel Title removed space

2023-01-25 10:18 UTC, a-gleeson commented on publishing/views.py
> +        ] = f" Envelope ID {envelope.envelope_id} was rejected and queue was paused."
Was for a Panel Title removed space

2023-01-25 10:18 UTC, a-gleeson commented on publishing/models/envelope.py
> +    def envelopes_by_year(self, year: Optional[int] = None):
updated as suggest :)

2023-01-25 22:04 UTC, paulpepper-trade requested changes

2023-01-25 22:04 UTC, paulpepper-trade commented on publishing/views.py
> +from publishing.models.state import ProcessingState
```suggestion
from publishing.models import PackagedWorkBasketDuplication
from publishing.models import PackagedWorkBasketInvalidCheckStatus
from publishing.models import PackagedWorkBasketInvalidQueueOperation
from publishing.models import OperationalStatus
from publishing.models import PackagedWorkBasket
from publishing.models import ProcessingState
```

2023-01-25 22:04 UTC, paulpepper-trade commented on sample.env
> +HMRC_PACKAGING_SEED_ENVELOPE_ID=230000
If we don't need the year portion of this ID (as previous comment), then:
```suggestion
HMRC_PACKAGING_SEED_ENVELOPE_ID=0001
```

2023-01-26 10:54 UTC, a-gleeson commented on publishing/admin.py
> +#   Envelope.objects.for_year()
Will remove

2023-01-26 10:55 UTC, a-gleeson commented on publishing/management/commands/create_envelope_for_top.py
> +from publishing.models.packaged_workbasket import PackagedWorkBasket
Will make changes

2023-01-26 10:57 UTC, a-gleeson commented on publishing/jinja2/includes/packaged-workbasket-queue.jinja
> +        (not obj.envelope or not obj.envelope.xml_file)
I was thinking that, more than happy to implement this

2023-01-26 10:59 UTC, a-gleeson commented on publishing/models/envelope.py
> +            counter = max(1, int(settings.HMRC_PACKAGING_SEED_ENVELOPE_ID[2:]))
When the env was implemented the default was a string like "230000" should I update this to just the sufix of the ID?

2023-01-26 11:35 UTC, paulpepper-trade commented on publishing/models/envelope.py
> +            counter = max(1, int(settings.HMRC_PACKAGING_SEED_ENVELOPE_ID[2:]))
Yes, because we don't use the year part in the code, and always slice it off, then I think just the ID is needed.

2023-01-26 12:00 UTC, a-gleeson commented on sample.env
> +HMRC_PACKAGING_SEED_ENVELOPE_ID=230000
Ah I missed this we can update that and the default in the settings

2023-01-26 12:18 UTC, paulpepper-trade commented on sample.env
> +HMRC_PACKAGING_SEED_ENVELOPE_ID=230000
Yeah, go for it.

2023-01-26 16:27 UTC, paulpepper-trade approved these changes

2023-01-26 16:29 UTC, merged