TP2000-731: Persist measure selections across pages
uktrade/tamato pull request #809
Opened 2023-02-07 12:55 UTC by eadpearce

# TP2000-731: Persist measure selections across pages

## Why

* If measure search results span multiple pages, users need a way to select measures from all pages

## What

* Adds a view for ajax post requests from the frontend to update the session
* Extends the preexisting checkboxes JS to track checkbox state and uses ajax to sync this with the session state

2023-02-07 13:25 UTC, paulpepper-trade requested changes

2023-02-07 13:25 UTC, paulpepper-trade commented on common/static/common/js/checkboxes.js
> +class CheckBoxes {
Does this offer a progressive enhancement?

2023-02-07 16:22 UTC, eadpearce commented on common/static/common/js/checkboxes.js
> +class CheckBoxes {
The checkboxes don't disappear when JS is disabled but it will revert back to previous functionality where checked items don't persist across pages

2023-02-09 11:16 UTC, eadpearce commented on common/static/common/js/checkboxes.js
> +class CheckBoxes {
Added an extra button for no JS solution

2023-02-13 09:40 UTC, a-gleeson commented on measures/views.py
> +            selected_objects = {k: v for k, v in form.cleaned_data.items() if v}
Is this repeated line required?

2023-02-13 09:54 UTC, eadpearce commented on measures/views.py
> +            selected_objects = {k: v for k, v in form.cleaned_data.items() if v}
oh yeah oops. i can get rid of that

2023-02-13 10:01 UTC, a-gleeson commented on common/static/common/js/application.js
> +initCheckboxes();
Is this where this initialisation belongs? Would this not set up the event listeners on every page? 
Would that possibly effect page performance?

2023-02-13 10:12 UTC, eadpearce commented on common/static/common/js/application.js
> +initCheckboxes();
Here it checks if the script element exists on the page, otherwise it doesn't run it https://github.com/uktrade/tamato/pull/809/files/108cb51bb52ca6d6d1e57247be5d1dd17a51a3bd#diff-7ddd91f71ff729075d86689c0edde6ccaad476adc5942d4c88372200786750b5R105

2023-02-13 10:16 UTC, a-gleeson commented on common/static/common/js/checkboxes.js
> +class CheckBoxes {
Should we rename this script? Checkbox is specific to measures so would not be reusable for other integrations unless parameterised?

2023-02-13 10:23 UTC, a-gleeson commented on common/static/common/js/application.js
> +initCheckboxes();
Thanks, that looks good! Happy with this. Would have to have a deeper dive but would this integration be useful to use htmx? https://htmx.org/attributes/hx-trigger/ . I think the integration with htmx would be a little more complicated in this case due to "multiple page"  persistence of checkboxies and noy required for this PR.

2023-02-13 10:24 UTC, a-gleeson approved these changes

2023-02-13 11:22 UTC, eadpearce commented on common/static/common/js/checkboxes.js
> +class CheckBoxes {
Now that you've said that I've realised this has broken the checkboxes on the workbasket page. I'll go and fix that

2023-02-13 11:54 UTC, a-gleeson commented on common/static/common/js/checkboxes.js
> +class CheckBoxes {
Good catch!

2023-02-13 12:16 UTC, a-gleeson approved these changes

2023-02-14 12:07 UTC, paulpepper-trade approved these changes

2023-02-14 12:58 UTC, merged