TP2000-743 Edit multiple measures start and end dates
uktrade/tamato pull request #824
Opened 2023-02-17 13:51 UTC by eadpearce

# TP2000-743 Edit multiple measures start and end dates

## Why

* Users want to be able to edit start dates as well as end dates on measures

## What

* Adds the end date form and a new start date form to a form wizard
* Users can select which fields they wish to edit at the start of the form

![FireShot Capture 050 - Edit measures - Manage Trade Tariffs - localhost](https://user-images.githubusercontent.com/25905279/219672620-459eebcd-7dc0-46fb-a886-5f32d344c24a.png)
<img width="448" alt="Screenshot 2023-02-17 at 13 48 19" src="https://user-images.githubusercontent.com/25905279/219672729-5aab8ea8-0f5e-4ac2-9e60-2dc7443f46b3.png">
<img width="431" alt="Screenshot 2023-02-17 at 13 48 32" src="https://user-images.githubusercontent.com/25905279/219672750-e9c87e07-1e12-4570-b8ab-c5b43ad8c720.png">

2023-02-21 12:27 UTC, a-gleeson commented on measures/views.py
> +        """Get the measures that are candidates for deletion."""
Just for deletion or is it selected candiates?

2023-02-21 12:30 UTC, a-gleeson commented on measures/forms.py
> +class MeasureStartDateForm(forms.Form):
Could the edit fields form be abstracted and reused? Or is it not worth the effort?

2023-02-21 12:32 UTC, a-gleeson commented on measures/views.py
> +            "measures/edit-wizard-step.jinja",
Should the default be the start/landing page for edits?

2023-02-21 12:38 UTC, a-gleeson commented
Do you think having the form start labeled as just "Start" is clear? When I started reviewing I got a little tripped up between start and start date. Maybe something like "landing" is good although that still may not be clear

2023-02-21 13:15 UTC, eadpearce commented on measures/views.py
> +        """Get the measures that are candidates for deletion."""
oop sorry this is a copypaste error. it's selection/editing

2023-02-21 13:16 UTC, eadpearce commented on measures/forms.py
> +class MeasureStartDateForm(forms.Form):
Yeah not worth it I think. The forms are going to be very slightly different

2023-02-21 13:20 UTC, eadpearce commented on measures/views.py
> +            "measures/edit-wizard-step.jinja",
Doesn't really matter. This is only a fallback in case it can't find the given key in the dict

2023-02-21 13:22 UTC, eadpearce commented
@a-gleeson Yeah that's a good point. I can change it to something like MeasuresEditFieldsForm ?

2023-02-21 14:11 UTC, a-gleeson commented
> @a-gleeson Yeah that's a good point. I can change it to something like MeasuresEditFieldsForm ?

Sounds good to me :)

2023-02-21 14:32 UTC, paulpepper-trade requested changes

2023-02-21 14:32 UTC, paulpepper-trade commented on measures/views.py
> +):
I think we need a docstring on this class to explain what it does and how it works. It's an important addition to the way that we manage measures through the UI and we should do our best to minimise the chances of running into those difficulties that we've encountered recently around this area.

2023-02-21 14:39 UTC, paulpepper-trade commented on measures/views.py
> +):
A docstring would also help us in reviewing this PR.

2023-02-22 10:12 UTC, eadpearce commented on measures/views.py
> +):
Done

2023-02-23 11:10 UTC, paulpepper-trade approved these changes
I think we'd benefit from more docs about how the wizard is used in this specific case, but it appears we may have a separate activity for that now.

@a-gleeson has given some good comments, so worth getting his approval too?

2023-02-23 11:19 UTC, a-gleeson approved these changes

2023-02-23 11:19 UTC, eadpearce commented
@paulpepper-trade Not sure why since everything I've done with the wizard is covered in the django form-tools docs

2023-02-23 14:47 UTC, merged