WIP: Session expiry constants added
uktrade/tamato pull request #827
Opened 2023-02-23 14:13 UTC by LaurenQurashi

# TP-??? Your PR title here

## Why

## What

2023-03-01 13:24 UTC, eadpearce commented
@LaurenQurashi are SESSION_SAVE_EVERY_REQUEST and SESSION_EXPIRE_AT_BROWSER_CLOSE settings used in the sso library? we don't need to do anything extra and the library just handles it?

2023-03-06 14:18 UTC, paulpepper-trade requested changes

2023-03-06 14:18 UTC, paulpepper-trade commented on common/tests/test_views.py
> +def test_index_displays_login_buttons_correctly_SSO_off_logged_in(valid_user_client):
Should this actually be named test_index_displays_**logout**_button_correctly_SSO_off_logged_in() since it's testing for the presence of a logout link?

2023-03-06 14:18 UTC, paulpepper-trade commented on common/tests/test_views.py
> +def test_index_displays_login_buttons_correctly_SSO_off_logged_out(client):
This isn't testing for the display of any login buttons, so perhaps could be named to describe the "can't access home page if logged out and SSO disabled" behaviour.

2023-03-06 14:18 UTC, paulpepper-trade commented on common/tests/test_views.py
> +    assert response.status_code == 302
I suppose we know the Location value of where this redirects to. Is it worth checking that value in an assert?

2023-03-08 14:54 UTC, paulpepper-trade commented on common/tests/test_views.py
> +    assert response.url == "/auth/login/?next=%2F"
Perhaps a little more robust:
```suggestion
    assert response.url.startswith(reverse('admin:login'))
```

2023-03-08 16:31 UTC, paulpepper-trade approved these changes

2023-03-09 09:31 UTC, merged