Measure exporter and updates
uktrade/tamato pull request #83
Opened 2020-10-09 16:24 UTC by simonwo

This pull request is an amalgam of all the various model, validator and serialiser fixes I have made as a result of building importers. We can split this down if we want, but the commits are faily logical so it might best to review on a commit-by-commit basis.

- The main event is all of the serialisers necessary to output measures. 
- This also includes tweaks to the measure models to handle prefixes and abbreviations used in duty sentences, which power the duty sentence parser coming in a later PR.
- There are also some fixes for other XML output.
- And there are some fixes to handle National Schema models and legacy data where rules are violated.

There are not enough tests, but I thought I would get some input on where coverage needs to be improved by creating this PR.

2020-10-12 13:26 UTC, NDevox requested changes
All looks OK to me, as mentioned, only thing that seems to be missing are tests

2020-10-23 10:13 UTC, NDevox reviewed
Nothing major, just a couple thoughts to keep things a _tad_ tidier.

2020-10-23 10:13 UTC, NDevox commented on measures/migrations/0008_measuretype_origin_destination_code.py
> +            reverse_code=do_nothing,
You can just omit this argument entirely - otherwise it's just noise.

2020-10-23 10:13 UTC, NDevox commented on measures/migrations/0007_measurements_have_optional_measurement_unit.py
> +                to="measures.MeasurementUnitQualifier",
Could we merge these migrations? would be nice to reduce the amount we have early on.

Can just copy the code from the operations and shift it into the migration before (and the ones after the same).

While no one else has run them this should work without issue.

2020-10-23 10:13 UTC, NDevox commented on regulations/validators.py
>  regulation_id_validator = RegexValidator(
One of the nicer looking regexes I've seen 👍

2020-10-23 13:49 UTC, NDevox approved these changes

2020-10-23 13:50 UTC, merged

2020-10-23 14:00 UTC, stuaxo commented
:+1:  :+1: :+1:  :+1: :+1:  :+1: