Updated ME16 more like ME32 than ME1 with lots of tests. Passes all p…
uktrade/tamato pull request #863
Opened 2023-03-16 08:44 UTC by dougmills-DIT

Updated ME16 more like ME32 than ME1 with lots of tests. Passes all previous defined tests and a chunk of new ones stolen from ME32. 

# TP2000-389 - Update ME16 to look at hierarchy and history 
 * TP2000-389
 * The ME16 rule definition is poorly worded and vague, it was interpreted in its most basic way initially, but after scrutiny by Steve, Matt Lavis and myself, we have concluded that this was incorrect (and probably a friday night job) as far as the TARIC3 spec is concerned. The initial implementation respected the wording but not the underlying intent. This update addresses the underlying intent of the rule, very similar to ME32 but checking for the inverted presence of an additional code. 

## Why
Why is this change happening, e.g. goals, use cases, stories, etc.?
 * Update ME16 to correctly check for matching measures in in the hierarchy but for one difference, if the additional code for the measure being verified is null, that a measure clashes but with an additional code (and the reverse), 
 * More testing added around the rulew
 * Existing tests still pass

## What
What is this PR doing, e.g. implementations, algorithms, etc.?
 * Update ME16 to be like ME32 but invert the check for the presence of additional code for the measure being validated

## Checklist
- Requires migrations? No
- Requires dependency updates? No

Links to relevant material
See: [Jira Ticket](https://uktrade.atlassian.net/browse/TP2000-389)
--->

2023-03-30 10:44 UTC, paulpepper-trade requested changes

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/business_rules.py
> +#             )
Any reason to leave this in here?

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/business_rules.py
> +        for snapshot in MeasureSnapshot.get_snapshots(measure, self.transaction):
This will introduce a shared issue with the ME32 check. Perhaps it's worth waiting for that to be resolved before this PR (or at least this approach to finding clashing measures) is integrated into production?

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/tests/test_buinsess_rules/test_ME16.py
> +    callable, date_overlap = request.param
A more descriptive name for `callable` would be better. One that says what it does rather that what it is.

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/tests/test_buinsess_rules/test_ME16.py
> +def test_ME16(existing_code, overlapping_code, error_expected):
Nice.

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/tests/test_buinsess_rules/test_ME16.py
> +def updated_goods_nomenclature(e):
Could `e` have a more descriptive name.

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/tests/test_buinsess_rules/test_ME16.py
> +def updated_goods_nomenclature(e):
Maybe worth prefixing the function name with `create_`?

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/tests/test_buinsess_rules/test_ME16.py
> +def updated_goods_nomenclature(e):
Maybe add a docstring to say what this does - create a new `GoodsNomenclature` instance with a TARIC update type of `UPDATE`.

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/tests/test_buinsess_rules/test_ME16.py
> +    return callable(existing_goods_nomenclature), expected
A more descriptive name for callable would be better. One that says what it does rather that what it is.

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/tests/test_buinsess_rules/test_ME16.py
> +    This is an extension of the previously described ME1 to all commodity codes
> described ME1 to all

Typo - ME16?

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/tests/test_buinsess_rules/test_ME16.py
> +    in the upward hierarchy and all commodity codes in the downward hierarchy.
It would be useful to have a bit more explanation here. What does it mean to apply the ME16 check to include all commodity codes in the upward and downward hierarchy?

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/business_rules.py
> +    def compile_query(self, measure):
I know this is a copy from the ME32 check, but there could either be a more descriptive name for `compile_query()` or perhaps a docstring.

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/tests/test_buinsess_rules/test_ME16.py
> +def measure_data_for_compile_query(request):
Suggestion: `measure_instance_for_compile_query`.

2023-03-30 10:44 UTC, paulpepper-trade commented on measures/tests/test_buinsess_rules/test_ME16.py
> +def test_ME16_works_with_wonky_archived_measure(seed_database_with_indented_goods):
Could you use something more specific than wonky?

2023-03-30 11:45 UTC, dougmills-DIT commented on measures/business_rules.py
> +    This rule is not applicable for Meursing additional codes.
updated, yes this was a copy

2023-03-30 11:45 UTC, dougmills-DIT commented on measures/business_rules.py
> +#             )
removed

2023-03-30 11:45 UTC, dougmills-DIT commented on measures/business_rules.py
> +        for snapshot in MeasureSnapshot.get_snapshots(measure, self.transaction):
very true, will have to wait

2023-03-30 11:54 UTC, dougmills-DIT commented on measures/tests/test_buinsess_rules/test_ME16.py
> +    callable, date_overlap = request.param
not my code, but agree (was a move not create) - have attempted to name better

2023-03-30 13:41 UTC, dougmills-DIT commented on measures/tests/test_buinsess_rules/test_ME16.py
> +def updated_goods_nomenclature(e):
done

2023-03-30 13:41 UTC, dougmills-DIT commented on measures/tests/test_buinsess_rules/test_ME16.py
> +def updated_goods_nomenclature(e):
done

2023-03-30 14:48 UTC, dougmills-DIT commented on measures/tests/test_buinsess_rules/test_ME16.py
> +def updated_goods_nomenclature(e):
done

2023-03-30 14:48 UTC, dougmills-DIT commented on measures/tests/test_buinsess_rules/test_ME16.py
> +    return callable(existing_goods_nomenclature), expected
done

2023-03-30 14:49 UTC, dougmills-DIT commented on measures/tests/test_buinsess_rules/test_ME16.py
> +def measure_data_for_compile_query(request):
done

2023-03-31 09:10 UTC, a-gleeson commented on measures/business_rules.py
> +        Two measures clash if any of their fields listed in this business rule
I may be misunderstanding but from the query I picked up that all fields must be equal (Query is using 'and' conditions), is this correct?
If so is the language "clash if any of their fields" describing more of an 'or' condition where a clash occurs if any field is equal within the measure and not all of them? I may be misunderstanding the rule check but just validating my understanding here.

2023-04-03 09:12 UTC, dougmills-DIT commented on measures/business_rules.py
> +        Two measures clash if any of their fields listed in this business rule
fair point, will update

2023-04-03 09:13 UTC, dougmills-DIT commented on measures/business_rules.py
> +        Two measures clash if any of their fields listed in this business rule
should be all (except additional code)

2023-04-03 12:54 UTC, a-gleeson commented on measures/business_rules.py
> +        Two measures clash if any of their fields listed in this business rule
Thanks, that helps clear it up. I just wanted to double check :)

2023-04-05 07:10 UTC, dougmills-DIT commented on measures/business_rules.py
> +        Two measures clash if any of their fields listed in this business rule
updated

2023-04-13 09:47 UTC, paulpepper-trade approved these changes

2023-04-13 10:38 UTC, merged