Tp2000 766  Measure condition validations & Automatic negative action generation
uktrade/tamato pull request #877
Opened 2023-04-03 09:38 UTC by a-gleeson

# TP2000-766 Measure condition validations & Automatic negative action generation

## Why
Condition codes always require 1 or more positive actions and no more than 1 negative action eg you can have three positive condition actions in a B code, but there must be 1 negative action code. If there is 1 positive action in the condition code then there must be one negative action code in the same condition code. For all positive actions under the same condition code the action code must be equal.
The only time you can have more than negative action code is if different condition codes are applied, both B codes and E codes for example.
To make the journey simpler for users, and to correct issues with the create measure conditions page in the create measure wizards validation improvements have been made at field, form and formset level. We also no longer create the negative actions in the form and they are generated on the creation of the measure and can be viewed from the workbasket details page.

This PR does not include negative action generation when importing conditions via the importer.
This PR does not include displaying the negative actions generated in the create measures review page, the edit measures view or the create measure conditions step in the create measures journey.
This PR does not edit negative actions.

## What
This PR includes:
- validation on the create measure conditions form page
    - Inline errors will now appear inline for field errors in the form set
    - Non field errors in a form will now also appear at the top of the individual form in the formset
    - Add accross form formset validation
        - Validation to ensure certificates are not duplicated across the same condition
        - Validation to ensure prices cannot be duplicated across the same condition
        - Validation to ensure action codes are equal across the same condition
        - Validation to ensure conditions are added in alphabetical order
- MeasureActionPair model added
    - save constraints to ensure invalid pairs cannot be created
    - data migration to create exisiting pairs based on existing action codes
    - uses this model to filter out negative action codes out of the queryset for the action field in the Measure condition form, so only positive and neutral actions can be created from the drop down.
    - autogenerates the negative actions at the end of the sequence of positive actions when creating measure conditions at the create measure journey.
- Includes a couple docker changes (small) 

## Checklist

Requires migrations - Yes
Required to create measureActionPair model in db and then migrate the data from the existing MeasureAction model.

2023-04-05 12:43 UTC, paulpepper-trade requested changes

2023-04-05 12:43 UTC, paulpepper-trade commented on measures/jinja2/measures/create-conditions-formset.jinja
> +        </button>
:-0

2023-04-05 12:43 UTC, paulpepper-trade commented on measures/tests/test_forms.py
> +def test_measure_formset_conditions_invalid(
This looks as though it contains four tests. Could they be split out so that the tests can be given descriptive names, perhaps breaking out some of the reused data into fixtures. It would make failing test diagnosys quicker and possibly easier.

2023-04-05 12:43 UTC, paulpepper-trade commented on measures/views.py
> +                component_sequence_number += 1
This `create_measures()` function is getting quite long now. Could you factor out the condition code portion of the create into a separate, helper function, perhaps?

2023-04-06 11:45 UTC, a-gleeson commented on Dockerfile
> +############################################################
So within the dockerfile there are multiple sections, this just helps visually split it

2023-04-06 11:46 UTC, a-gleeson commented on README.rst
> +    # to overwrite default db dump name pass in DUMP_FILE=tamato_db.sql
just a make variable you can pass in to specific the file you are importing

2023-04-06 11:47 UTC, a-gleeson commented on common/jinja2/components/measure_condition_action_code/template.jinja
> +<div class="govuk-form-group govuk-form-group--error">
Well spotted I can do that here

2023-04-06 11:47 UTC, a-gleeson commented on measures/forms.py
> +        # Filters out negative actions
I can be more explicit

2023-04-06 11:59 UTC, a-gleeson commented on measures/forms.py
> +        # Choose all rows that aren't negative actions, this would be a single query
I haven't found a simple way to do it in the django ORM it always comes out as 2 queries.
I guess if we are happy with it remaining as a 2 query process then I am happy to remove the comment. I just wasn't sure if we should use raw SQL or put too much more time into this for the value gained

2023-04-06 11:59 UTC, a-gleeson commented on measures/jinja2/measures/create-conditions-formset.jinja
> +        </button>
I am surprised too!

2023-04-06 12:00 UTC, a-gleeson commented on measures/tests/test_forms.py
> +def test_measure_formset_conditions_invalid(
I forgot to refector the tests other than just getting them to test the code. I can add the refector in

2023-04-11 10:50 UTC, a-gleeson commented on README.rst
> +    # to overwrite default db dump name pass in DUMP_FILE=tamato_db.sql
I can do that

2023-04-13 08:43 UTC, merged