TP2000 926 Enforce a maximum of one active import per service instance
uktrade/tamato pull request #986
Opened 2023-07-25 14:54 UTC by a-gleeson

# TP2000-926 Enforce a maximum of one active import per service instance

## Why
The current parser capability relies on a shared caching resource (referred to as the nursery in the TAP codebase), which is not name-spaced between import processor. This is an issue when imports run in parallel, causing invalid objects to appear in an importer’s cache (nursery).

## What
- A seperate worker for importing has been set up to process importing tasks
- worker set up with a concurrency of 1 so tasks are only processed one at a time in the order they are recieved
- local celery worker set up

2023-07-25 14:59 UTC, paulpepper-trade commented on docker-compose.yml
> +        - "ENV=${ENV:-prod}"
Some sneaky white space crept in at the end of this line. I think there's no change to this file if it gets deleted.

2023-07-25 15:11 UTC, paulpepper-trade requested changes

2023-07-25 15:11 UTC, paulpepper-trade commented on common/celery.py
> +)
There may be some risk in applying retries this across all of our tasks. Could we roll this out to tasks gradually to allow us to observe and manage that risk? Maybe the importer's `importer.tasks.import_chunk()` and, say, the rule checker's `workbasket.tasks.call_check_workbasket_sync()` would be good, low-ish risk initial trial tasks?

2023-07-25 15:11 UTC, paulpepper-trade commented on docker-compose.yml
> +    image: tamato
Trailing white space.

2023-07-25 15:42 UTC, a-gleeson commented on common/celery.py
> +)
Hi, I will make these changes as it could be a risk putting it accross the board. I'll need to update the configuration a bit but shouldn't be an issue. This isn't exactly retry but instead more will replay the task it was in the process of processing.

2023-07-31 10:30 UTC, paulpepper-trade approved these changes
LGTM

2023-07-31 10:50 UTC, merged